const pageData = {
    infoBox: {
        type: 'info',
        title: '💡 Wskazówka',
        content: 'Jeśli szukasz komiksów lub mangi, sprawdź nasze dedykowane sekcje <a href="komiksy.html">Komiksy</a> i <a href="manga.html">Manga</a>.<br>Dla lepszego doświadczenia używaj VPN (sprawdź sekcję <a href="vpn.html">VPN</a>) i AdBlockera (<a href="adblock.html">AdBlock</a>).'
    },
    warningBox: {
        type: 'warning',
        title: '⚠️ Uwaga',
        content: 'Niektóre strony mogą zawierać malware lub agresywne reklamy. Zawsze używaj uBlock Origin i NoScript. Unikaj pobierania plików .exe z nieznanych źródeł. Wspieraj autorów poprzez legalne zakupy tam, gdzie to możliwe.'
    },
    sections: [
        {
            id: 'glowne-biblioteki-ebookow',
            title: '📚 Główne Biblioteki eBooków',
            links: [
                { name: "AllBooksWorld", url: "https://allbooksworld.com/" },
                { name: "AllFreeBooks", url: "https://allfreebooks.org/" },
                { name: "Anna's Archive .es (Mirror)", url: "https://annas-archive.es/" },
                { name: "Anna's Archive .is (Mirror)", url: "https://annas-archive.is/" },
                { name: "Anna's Archive .li (Mirror)", url: "https://annas-archive.li/" },
                { name: "Anna's Archive .se (Mirror)", url: "https://annas-archive.se/" },
                { name: "Anna's Archive (Największa meta-biblioteka)", url: "https://annas-archive.org/" },
                { name: "Archive.org Texts", url: "https://archive.org/details/texts" },
                { name: "B-OK (BookOS)", url: "https://b-ok.cc/" },
                { name: "B-OK Asia", url: "https://b-ok.asia/" },
                { name: "B-OK Global", url: "https://b-ok.global/" },
                { name: "Book4You", url: "https://book4you.org/" },
                { name: "BookFi", url: "https://bookfi.net/" },
                { name: "BookFrom.net", url: "https://www.bookfrom.net/" },
                { name: "BookSC EU", url: "https://booksc.eu/" },
                { name: "BookSC ORG", url: "https://booksc.org/" },
                { name: "BookSee", url: "https://en.booksee.org/" },
                { name: "Bookstagram", url: "https://vk.com/bookstagram_eng" },
                { name: "BookZZ", url: "https://bookzz.org/" },
                { name: "dpgroup", url: "https://www.dpgroup.org/" },
                { name: "eBook-Hunter", url: "https://ebook-hunter.org/" },
                { name: "eBook Lobby", url: "https://ebooklobby.com/" },
                { name: "eBook777", url: "https://ebook777.com/" },
                { name: "eBookBB", url: "https://ebookbb.in/" },
                { name: "eBooksInfo", url: "https://ebooksinfo.com/" },
                { name: "eBookoz", url: "https://ebookoz.net/" },
                { name: "Ebook PDF", url: "https://ebookpdf.com/" },
                { name: "ePDF", url: "https://epdf.tips/" },
                { name: "ePDF 2", url: "https://epdf.pub/" },
                { name: "Free eBooks Download", url: "https://free-ebooks-download.org/" },
                { name: "FreeBannedBooks", url: "https://freebannedbooks.org/" },
                { name: "FreePDFBook", url: "https://freepdfbook.com/" },
                { name: "GetFreePDFs", url: "https://getfreepdfs.com/" },
                { name: "iBookPile", url: "https://ibookpile.in/" },
                { name: "iDoc", url: "https://idoc.tips/" },
                { name: "IsIDore", url: "https://rentry.co/FMHYBase64#isidore" },
                { name: "KuPDF", url: "https://kupdf.net/" },
                { name: "Liber3 (Decentralizowana)", url: "https://liber3.eth.limo/" },
                { name: "LibGen .gs", url: "https://libgen.gs/" },
                { name: "LibGen .is", url: "https://libgen.is/" },
                { name: "LibGen .li (Mirror)", url: "https://libgen.li/" },
                { name: "LibGen .st (Mirror)", url: "https://libgen.st/" },
                { name: "Library Genesis (Klasyk)", url: "https://libgen.rs/" },
                { name: "Library Land", url: "https://library.land/" },
                { name: "LibraryGenesis.net (Mirror)", url: "https://librarygenesis.net/" },
                { name: "Manybooks", url: "https://manybooks.net/" },
                { name: "Mobilism", url: "https://forum.mobilism.org", tag: "⭐" },
                { name: "Mobilism 2", url: "https://forum.mobilism.me/", tag: "⭐" },
                { name: "Novel12", url: "https://novel12.com/" },
                { name: "OceanofPDF", url: "https://oceanofpdf.com/" },
                { name: "Open Library", url: "https://openlibrary.org/" },
                { name: "PDF Books Free Download", url: "https://pdf-books-free-download.com/" },
                { name: "PDF Coffee (IT section)", url: "https://pdfcoffee.com/" },
                { name: "PDFCookie", url: "https://pdfcookie.com/" },
                { name: "PDFDrive TO", url: "https://pdfdrive.to/" },
                { name: "PDFDrive.com", url: "https://www.pdfdrive.com/" },
                { name: "PDF eBook Free", url: "https://pdfebookfree.com/" },
                { name: "PDF Room", url: "https://pdfroom.com/" },
                { name: "PDFBooksDownload", url: "https://pdfbooksdownload.com/" },
                { name: "PDFBooksWorld", url: "https://pdfbooksworld.com/" },
                { name: "PDFSearches", url: "https://pdfsearches.com/" },
                { name: "ReadOnlineFreeBook", url: "https://readonlinefreebook.com/" },
                { name: "SingleLogin (Z-Library backup)", url: "https://singlelogin.re/" },
                { name: "The Library", url: "https://discord.gg/mSyFJz9" },
                { name: "WeLib", url: "https://welib.org/" },
                { name: "Z-Lib.fm", url: "https://z-lib.fm/" },
                { name: "Z-Lib.gd", url: "https://z-lib.gd/" },
                { name: "Z-Lib.io", url: "https://z-lib.io/" },
                { name: "Z-Library (Instrukcja dostępu)", url: "https://www.reddit.com/r/zlibrary/wiki/index/access/" }
            ]
        },
        {
            id: 'ksiazki-ogolne-i-beletrystyka',
            title: '📖 Książki Ogólne i Beletrystyka',
            links: [
                { name: "AlternateHistory", url: "https://www.alternatehistory.com/forum/" },
                { name: "AO3 (Archive of Our Own)", url: "https://archiveofourown.org/", tag: "⭐" },
                { name: "BAEN", url: "https://www.baen.com/catalog/category/view/s/free-library/id/2012" },
                { name: "Baen Books (sci-fi/fantasy)", url: "https://www.baen.com/" },
                { name: "Book Depository (fizyczne + darmowa wysyłka)", url: "https://www.bookdepository.com/" },
                { name: "Booksie", url: "https://www.booksie.com/" },
                { name: "By the Fireplace", url: "https://bythefireplace.com/" },
                { name: "Classic Literature", url: "https://classic-literature.co.uk/" },
                { name: "DigiLibraries", url: "https://digilibraries.com/" },
                { name: "DPLA", url: "https://dp.la/" },
                { name: "E-Book Mecca", url: "https://ebook-mecca.com/" },
                { name: "eBooks.com (legalne zakupy)", url: "https://www.ebooks.com/" },
                { name: "Everything2", url: "https://everything2.com/" },
                { name: "ExClassics", url: "https://www.exclassics.com/" },
                { name: "Faded Page (kanadyjskie klasyki)", url: "https://www.fadedpage.com/" },
                { name: "FanFiction.net", url: "https://www.fanfiction.net/" },
                { name: "FanMTL", url: "https://www.fanmtl.com/" },
                { name: "Feedbooks", url: "https://www.feedbooks.com/" },
                { name: "FictionPress", url: "https://www.fictionpress.com/" },
                { name: "fiction.live", url: "https://fiction.live/" },
                { name: "Fim Fiction", url: "https://www.fimfiction.net/" },
                { name: "Fork Read", url: "https://forkread.com/" },
                { name: "FreeEditorial", url: "https://www.freeditorial.com/en/" },
                { name: "FreeEditorial Spanish", url: "https://www.freeditorial.com" },
                { name: "Global Grey", url: "https://www.globalgreyebooks.com/index.html" },
                { name: "Hoopla", url: "https://www.hoopladigital.com/" },
                { name: "Inkitt", url: "https://www.inkitt.com/fanfiction" },
                { name: "JustFreeBooks", url: "https://www.justfreebooks.info/" },
                { name: "Kobo (legalne zakupy)", url: "https://www.kobo.com/" },
                { name: "Library of Short Stories", url: "https://www.libraryofshortstories.com/" },
                { name: "Liminal Archives", url: "http://liminal-archives.wikidot.com/" },
                { name: "Lit2Go", url: "https://etc.usf.edu/lit2go/" },
                { name: "Loyal Books", url: "https://www.loyalbooks.com/" },
                { name: "NovelBuddy", url: "https://novelbuddy.com/" },
                { name: "OpenChapter", url: "https://openchapter.io/" },
                { name: "OrionsArm", url: "https://www.orionsarm.com/" },
                { name: "Page by Page Books", url: "https://www.pagebypagebooks.com/" },
                { name: "Planet eBook", url: "https://www.planetebook.com/" },
                { name: "Planet Publish", url: "https://www.planetpublish.com/" },
                { name: "Poop Fiction", url: "https://readpoopfiction.com/" },
                { name: "Potions and Snitches", url: "https://www.potionsandsnitches.org/" },
                { name: "Project Gutenberg (domena publiczna)", url: "https://www.gutenberg.org/", tag: "⭐" },
                { name: "PublicDomainReview", url: "https://publicdomainreview.org/" },
                { name: "Quotev", url: "https://www.quotev.com/stories/c/Fanfiction" },
                { name: "Royal Road (webnovels)", url: "https://www.royalroad.com/" },
                { name: "RPC Authority", url: "http://rpc-wiki.net/" },
                { name: "SCP Foundation", url: "https://scp-wiki.wikidot.com/" },
                { name: "sherlock-holm.es", url: "https://sherlock-holm.es/" },
                { name: "Short Stories", url: "https://short-stories.co/", tag: "⭐" },
                { name: "Smashwords (niezależni autorzy)", url: "https://www.smashwords.com/" },
                { name: "SquidgeWorld", url: "https://squidgeworld.org/" },
                { name: "Standard Ebooks (wysoka jakość)", url: "https://standardebooks.org/" },
                { name: "the Wanderers' Library", url: "https://wanderers-library.wikidot.com/" },
                { name: "Unglue.it", url: "https://unglue.it/", tag: "⭐" },
                { name: "Vestal Review", url: "https://www.vestalreview.net/" },
                { name: "Vocal Media", url: "https://vocal.media/fiction/" },
                { name: "Wattpad", url: "https://wattpad.com/" },
                { name: "Wikibooks", url: "https://www.wikibooks.org/" },
                { name: "Wikisource", url: "https://en.wikisource.org" },
            ]
        },
        {
            id: 'magazyny-i-czasopisma',
            title: '📰 Magazyny i Czasopisma',
            links: [
                { name: "Amiga Magazines", url: "https://archive.org/details/amiga_magazines" },
                { name: "Apple Magazines", url: "https://archive.org/details/apple_magazines" },
                { name: "Archive Fashion for the World", url: "https://www.archivepdf.net/" },
                { name: "Archive.org Magazines", url: "https://archive.org/details/magazines" },
                { name: "Atari Magazines", url: "https://www.atarimagazines.com/" },
                { name: "Calameo", url: "https://calameo.com/" },
                { name: "CGW Museum", url: "https://www.cgwmuseum.org/" },
                { name: "Commodore Magazines", url: "https://archive.org/details/commodore_magazines" },
                { name: "Computer Magazines Archive", url: "https://archive.org/details/computermagazines" },
                { name: "DownMagaz", url: "https://downmagaz.net/", tag: "⭐" },
                { name: "EBooksYard", url: "https://ebooksyard.com/" },
                { name: "FlipHTML5", url: "https://fliphtml5.com/exploring" },
                { name: "Free Magazines", url: "https://freemagazines.top/" },
                { name: "FreeMagazines.TOP", url: "https://freemagazines.top/" },
                { name: "FreeMagazinePDF", url: "https://freemagazinespdf.com/" },
                { name: "GetFreeMagazines", url: "https://getfreemagazines.com/" },
                { name: "HomePower", url: "https://www.homepower.com/archive-browse" },
                { name: "Issuu (cyfrowe czasopisma)", url: "https://issuu.com/" },
                { name: "Lainzine", url: "https://lainzine.org/" },
                { name: "MagDownload", url: "https://magdownload.org/" },
                { name: "MagazineLib", url: "https://magazinelib.com/", tag: "⭐" },
                { name: "Magzter (legalne subskrypcje)", url: "https://magzter.com/" },
                { name: "Mobilism Magazines", url: "https://forum.mobilism.org/viewforum.php?f=123", tag: "⭐" },
                { name: "PC Zone", url: "https://pixsoriginadventures.co.uk/PCZone/" },
                { name: "PDF Dude", url: "https://pdfdude.com/" },
                { name: "PDF Magaz", url: "https://www.pdfmagaz.in/" },
                { name: "PDF Magazines Archive", url: "https://pdf-magazines-archive.com/" },
                { name: "PDF Magazines Download", url: "https://pdf-magazines-download.com/" },
                { name: "PDFMagazines Club", url: "https://pdfmagazines.club/", tag: "⭐" },
                { name: "PDFMagazines ORG", url: "https://pdfmagazines.org/" },
                { name: "PressReader (prasa światowa)", url: "https://www.pressreader.com/" },
                { name: "RadioShack Catalogs", url: "https://www.radioshackcatalogs.com/" },
                { name: "RetroMags (klasyczne magazyny)", url: "https://retromags.com/" },
                { name: "WholeEarth", url: "https://wholeearth.info/" },
                { name: "World Mags", url: "https://www.worldmags.net/" }
            ]
        },
        {
            id: 'akademickie-i-naukowe',
            title: '🎓 Akademickie i Naukowe',
            links: [
                { name: "2012books", url: "https://2012books.lardbucket.org/" },
                { name: "84000", url: "https://84000.co/" },
                { name: "Academia", url: "https://www.academia.edu/" },
                { name: "Academic Journals", url: "https://academicjournals.org/" },
                { name: "Academic Torrents", url: "https://academictorrents.com/", tag: "⭐" },
                { name: "ACM", url: "https://dl.acm.org/" },
                { name: "ACM Digital Library", url: "https://dl.acm.org/" },
                { name: "Alexandria", url: "https://www.alexandria.ucsb.edu/" },
                { name: "arXiv (fizyka, matematyka, CS)", url: "https://arxiv.org/", tag: "⭐" },
                { name: "arXiv Tools", url: "https://arxivxplorer.com/", tag: "⭐" },
                { name: "arXiv Tools 2", url: "https://searchthearxiv.com/", tag: "⭐" },
                { name: "BASE (Bielefeld Academic Search Engine)", url: "https://www.base-search.net/" },
                { name: "BhagavadGitaApp", url: "https://github.com/WirelessAlien/BhagavadGitaApp" },
                { name: "Biomed Central", url: "https://www.biomedcentral.com/" },
                { name: "bioRvix", url: "https://www.biorxiv.org/" },
                { name: "BookGoldMine", url: "https://www.bookgoldmine.com/" },
                { name: "Brill", url: "https://brill.com/" },
                { name: "Buddhism Dictionary", url: "http://www.buddhism-dict.net/ddb/" },
                { name: "BulletPapers", url: "https://www.bulletpapers.ai/" },
                { name: "Caltech Library", url: "https://authors.library.caltech.edu/" },
                { name: "CensorBib", url: "https://censorbib.nymity.ch/" },
                { name: "CIA Publications", url: "https://www.cia.gov/resources/publications/" },
                { name: "Citrus Search", url: "https://citrus-search.com/", tag: "⭐" },
                { name: "Clarivate", url: "https://mjl.clarivate.com/" },
                { name: "ck12", url: "https://www.ck12.org/" },
                { name: "Connected Papers", url: "https://www.connectedpapers.com/" },
                { name: "Consensus", url: "https://consensus.app/" },
                { name: "Constitute Project", url: "https://www.constituteproject.org/" },
                { name: "CORE (otwarty dostęp)", url: "https://core.ac.uk/" },
                { name: "CourtListerner", url: "https://www.courtlistener.com/" },
                { name: "Crossref", url: "https://search.crossref.org/" },
                { name: "Data Catalog", url: "https://datacatalog.worldbank.org/" },
                { name: "Dataone", url: "https://www.dataone.org/" },
                { name: "DBpedia", url: "https://www.dbpedia.org/" },
                { name: "De Gruyter Brill", url: "https://www.degruyterbrill.com/?submittedFilterId=by-type&access_4=open&pageSize=10&sort=datedescending&type_5=book" },
                { name: "De Gruyter Brill 2", url: "https://www.degruyterbrill.com/page/2045" },
                { name: "Dimensions", url: "https://app.dimensions.ai/discover/publication" },
                { name: "Dirzon", url: "https://www.dirzon.com/Doc/SearchAsync" },
                { name: "DOAJ", url: "https://doaj.org/" },
                { name: "DOKU.PUB", url: "https://doku.pub/" },
                { name: "Dummies Store", url: "https://t.me/dummiesbook" },
                { name: "E-Books Directory", url: "https://www.e-booksdirectory.com/" },
                { name: "E-International Relations", url: "https://www.e-ir.info/" },
                { name: "eBookRoom", url: "https://t.me/eBookRoom" },
                { name: "Einstein Papers", url: "https://einsteinpapers.press.princeton.edu/" },
                { name: "Encyclopedia Of Buddhism", url: "https://archive.org/details/EdwardA.IronsEncyclopediaOfBuddhismEncyclopediaOfWorldReligions/" },
                { name: "Encyclopedia Of Hinduism", url: "https://archive.org/details/ConstanceA.JonesJamesD.RyanEncyclopediaOfHinduism/" },
                { name: "EveryCulture", url: "https://www.everyculture.com/index.html" },
                { name: "FBI Vault", url: "https://vault.fbi.gov/" },
                { name: "Free Medical Journals", url: "http://www.freemedicaljournals.com/" },
                { name: "FreeBookCentre", url: "https://freebookcentre.net/" },
                { name: "FreeFullPDF", url: "https://freefullpdf.com/" },
                { name: "FreePLRDownloads", url: "https://freeplrdownloads.com/" },
                { name: "GBIF", url: "https://www.gbif.org/" },
                { name: "Google Scholar (legalne + linki do Sci-Hub)", url: "https://scholar.google.com/", tag: "⭐" },
                { name: "HAL", url: "https://hal.science/" },
                { name: "HathiTrust", url: "https://www.hathitrust.org/" },
                { name: "Heystacks", url: "https://heystacks.com/" },
                { name: "Higher Intellect", url: "https://preterhuman.net/" },
                { name: "IDoc", url: "https://idoc.pub/" },
                { name: "IDEAS", url: "https://ideas.repec.org/" },
                { name: "IEEE Xplore", url: "https://ieeexplore.ieee.org/" },
                { name: "InfoBooks", url: "https://www.infobooks.org/" },
                { name: "Institute of Education Sciences", url: "https://eric.ed.gov/" },
                { name: "Institutional Access", url: "https://www.facebook.com/groups/850609558335839" },
                { name: "Internet Archive Scholar", url: "https://scholar.archive.org/" },
                { name: "Japanese Wiki Corpus", url: "https://www.japanesewiki.com/" },
                { name: "JSTor", url: "https://www.jstor.org/" },
                { name: "JSTOR (archiwum naukowe)", url: "https://www.jstor.org/" },
                { name: "Kaggle", url: "https://www.kaggle.com/datasets" },
                { name: "Legal Core", url: "https://core.ac.uk/" },
                { name: "Lens", url: "https://www.lens.org/" },
                { name: "LibertyFund", url: "https://oll.libertyfund.org/" },
                { name: "LibreTexts", url: "https://one.libretexts.org/home" },
                { name: "Library Drive", url: "https://rentry.co/FMHYBase64#library-drive" },
                { name: "lol my thesis", url: "https://lolmythesis.com/" },
                { name: "longdom", url: "https://www.longdom.org/" },
                { name: "Lumina", url: "https://www.lumina.sh/" },
                { name: "MDPI", url: "https://www.mdpi.com/" },
                { name: "MedicalStudyZone", url: "https://medicalstudyzone.com/" },
                { name: "medRxiv", url: "https://www.medrxiv.org/" },
                { name: "Memory of the World", url: "https://www.memoryoftheworld.org/" },
                { name: "Mendeley", url: "https://www.mendeley.com/", tag: "⭐" },
                { name: "Monoskop", url: "https://monoskop.org/log/" },
                { name: "MyScienceWork", url: "https://www.mysciencework.com/" },
                { name: "NAP", url: "https://nap.nationalacademies.org/" },
                { name: "Nexus Search", url: "https://t.me/nexus_search/214", tag: "⭐" },
                { name: "Non-Fiction", url: "https://vk.com/non_fic" },
                { name: "NSA Archive", url: "https://nsarchive.gwu.edu/" },
                { name: "OAPEN", url: "https://oapen.org/" },
                { name: "OATD", url: "https://oatd.org/" },
                { name: "Online Books Page", url: "https://onlinebooks.library.upenn.edu/" },
                { name: "Open Access Library", url: "https://www.oalib.com/" },
                { name: "Open Payments", url: "https://openpaymentsdata.cms.gov/" },
                { name: "Open Textbook Library", url: "https://open.umn.edu/opentextbooks/" },
                { name: "OpenAire", url: "https://explore.openaire.eu/" },
                { name: "OpenDOAR", url: "https://v2.sherpa.ac.uk/opendoar/" },
                { name: "OpenED", url: "https://open.bccampus.ca/" },
                { name: "OpenEdition", url: "https://www.openedition.org/" },
                { name: "OpenKnowledge Maps", url: "https://openknowledgemaps.org/" },
                { name: "OpenMD", url: "https://openmd.com/" },
                { name: "Openstax", url: "https://openstax.org/", tag: "⭐" },
                { name: "OSF (Open Science Framework)", url: "https://osf.io/" },
                { name: "Pandora", url: "https://pandora.nla.gov.au/" },
                { name: "Paper Panda", url: "https://paperpanda.app/" },
                { name: "Paperity", url: "https://paperity.org/" },
                { name: "Parliament Archives", url: "https://archives.parliament.uk/" },
                { name: "PDFHost", url: "https://pdfhost.io/" },
                { name: "Proquest", url: "https://www.proquest.com/" },
                { name: "PsyArXiv", url: "https://psyarxiv.com/" },
                { name: "PubMed", url: "https://pubmed.ncbi.nlm.nih.gov/" },
                { name: "PubMed Central", url: "https://www.ncbi.nlm.nih.gov/pmc/" },
                { name: "qDoc", url: "https://idoc.tips/" },
                { name: "re3data", url: "https://www.re3data.org/" },
                { name: "ResearchGate", url: "https://www.researchgate.net/", tag: "⭐" },
                { name: "Retraction Watch", url: "https://retractionwatch.com/" },
                { name: "RPubs", url: "https://rpubs.com/" },
                { name: "RuTracker eBook (ogromna baza)", url: "https://rutracker.org/forum/tracker.php?nm=ebook" },
                { name: "Sci-Hub .ru (Mirror)", url: "https://sci-hub.ru/" },
                { name: "Sci-Hub .st (Mirror)", url: "https://sci-hub.st/" },
                { name: "Sci-Hub MKSA", url: "https://sci-hub.mksa.top/" },
                { name: "Sci-Hub Tools", url: "https://t.me/scihubot", tag: "⭐" },
                { name: "Sci-Hub(Artykuły naukowe)", url: "https://sci-hub.se/", tag: "⭐" },
                { name: "Sci-Hub.tf", url: "https://sci-hub.tf/" },
                { name: "Science Hub", url: "https://www.smartquantai.com/" },
                { name: "Science.gov", url: "https://www.science.gov/" },
                { name: "ScienceDirect", url: "https://www.sciencedirect.com/" },
                { name: "ScienceDirect (Elsevier)", url: "https://www.sciencedirect.com/" },
                { name: "SciLit", url: "https://www.scilit.com/", tag: "⭐" },
                { name: "Scinapse", url: "https://scinapse.io/" },
                { name: "SecretCanada", url: "https://www.secretcanada.com/" },
                { name: "Semantic Scholar", url: "https://www.semanticscholar.org/", tag: "⭐" },
                { name: "Share OSF", url: "https://share.osf.io/" },
                { name: "SkillCommons", url: "https://www.skillscommons.org/" },
                { name: "Snowden Archive", url: "https://github.com/iamcryptoki/snowden-archive" },
                { name: "SocArXiv", url: "https://osf.io/preprints/socarxiv" },
                { name: "Springer", url: "https://www.springer.com/gp" },
                { name: "SSRN", url: "https://www.ssrn.com/" },
                { name: "SuperKuh", url: "http://erewhon.superkuh.com/library/" },
                { name: "TextBookGo", url: "http://textbookgo.com/" },
                { name: "The American Presidency Project", url: "https://www.presidency.ucsb.edu/" },
                { name: "The Black Vault", url: "https://www.theblackvault.com/" },
                { name: "The Ergonomic Development of Video Game Controllers", url: "https://www.longdom.org/open-access/the-ergonomic-development-of-video-game-controllers-2165-7556-1000209.pdf" },
                { name: "TheFreeLibrary", url: "https://www.thefreelibrary.com/", tag: "⭐" },
                { name: "The Literature Network", url: "https://www.online-literature.com/" },
                { name: "The Uncensored Library", url: "https://www.uncensoredlibrary.com/en" },
                { name: "Tradepub", url: "https://knowfree.tradepub.com/" },
                { name: "Typewriter", url: "https://tetw.org/" },
                { name: "UCL Press", url: "https://www.uclpress.co.uk/" },
                { name: "Various Books", url: "https://rentry.co/FMHYBase64#various-books-manuals" },
                { name: "VDOC.PUB", url: "https://vdoc.pub/" },
                { name: "VetBooks", url: "https://vetbooks.ir/" },
                { name: "Wikiversity", url: "https://www.wikiversity.org/" },
                { name: "WorldBank", url: "https://www.worldbank.org/en/home" },
                { name: "Zenodo (CERN open science)", url: "https://zenodo.org/" },
                { name: "Zooniverse", url: "https://www.zooniverse.org/" }
            ]
        },
        {
            id: 'programowanie-i-it',
            title: '💻 Programowanie i IT',
            links: [
                { name: "All About Circuits", url: "https://www.allaboutcircuits.com/education/" },
                { name: "Apress", url: "https://www.apress.com/" },
                { name: "Best-Books.dev", url: "https://www.best-books.dev/", tag: "⭐" },
                { name: "Biology.com.pk", url: "https://biology.com.pk/" },
                { name: "ChauThanh (IT & więcej)", url: "https://chauthanh.info/" },
                { name: "Chemistry.com.pk", url: "https://chemistry.com.pk/" },
                { name: "ChessProgramming", url: "https://www.chessprogramming.org/" },
                { name: "CoderProg", url: "https://coderprog.com/" },
                { name: "CS Video Courses (również PDFy)", url: "https://github.com/Developer-Y/cs-video-courses" },
                { name: "eBooks-IT", url: "https://ebooks-it.org" },
                { name: "Essential Programming Books", url: "https://www.programming-books.io/" },
                { name: "Explanations", url: "https://magcius.github.io/xplain/article/" },
                { name: "Flavio Copes", url: "https://flaviocopes.com/" },
                { name: "ForCoder", url: "https://forcoder.net/" },
                { name: "Free eBooks", url: "https://books-pdf.blogspot.com/" },
                { name: "Free Ebooks Download List", url: "https://free-ebook-download-links.blogspot.com/" },
                { name: "Free Programming Books (GitHub)", url: "https://github.com/EbookFoundation/free-programming-books", tag: "🌐" },
                { name: "FreeComputerEbooks", url: "https://freecomputerbooks.com/" },
                { name: "FreeTechBooks", url: "https://www.freetechbooks.com/" },
                { name: "Go Books", url: "https://github.com/dariubs/GoBooks" },
                { name: "GoalKicker", url: "https://goalkicker.com/" },
                { name: "GoodTheorist", url: "https://www.goodtheorist.science/" },
                { name: "Hacker News Books", url: "https://hackernewsbooks.com/" },
                { name: "HBPMS", url: "https://hbpms.blogspot.com/" },
                { name: "Institute of Mathematics", url: "https://aimath.org/textbooks/" },
                { name: "IntechOpen", url: "https://www.intechopen.com/" },
                { name: "IT Book Drive", url: "https://rentry.co/FMHYBase64#it-books-drive" },
                { name: "IT eBooks", url: "https://it-ebooks.info/" },
                { name: "JSBooks", url: "https://jsbooks.revolunet.com/" },
                { name: "Manning Publications", url: "https://www.manning.com/" },
                { name: "Math and Physics Books", url: "https://rentry.co/FMHYBase64#math-and-physics-books" },
                { name: "Naked Scientists", url: "https://www.thenakedscientists.com/" },
                { name: "No Starch Press", url: "https://nostarch.com/" },
                { name: "O'Reilly (legalne, subskrypcja)", url: "https://www.oreilly.com/", tag: "⭐" },
                { name: "OnlineProgrammingBooks", url: "https://www.onlineprogrammingbooks.com/" },
                { name: "OSSU Computer Science (ścieżka + materiały)", url: "https://github.com/ossu/computer-science" },
                { name: "Packt Publishing", url: "https://www.packtpub.com/" },
                { name: "PDFiles", url: "https://www.pdfiles.net/" },
                { name: "Pragmatic Programmer", url: "https://www.pragmaticprogrammer.com/" },
                { name: "Python Data Science Handbook", url: "https://jakevdp.github.io/PythonDataScienceHandbook/" },
                { name: "RealNotComplex", url: "https://realnotcomplex.com/" },
                { name: "ScanLibs", url: "https://scanlibs.com/", tag: "⭐" },
                { name: "SemiWiki", url: "https://semiwiki.com/" },
                { name: "TechBooksFree", url: "https://techbooksforfree.com/" },
                { name: "Ultimate Electronics Book", url: "https://ultimateelectronicsbook.com/" },
                { name: "vhf Free Programming Books", url: "https://github.com/vhf/free-programming-books" },
                { name: "WOW! eBook", url: "https://www.wowebook.org/" },
                { name: "X-Files", url: "https://doc.lagout.org/" }
            ]
        },
        {
            id: 'kursy-i-edukacja',
            title: '🎬 Kursy i Edukacja',
            links: [
                { name: "Course Joiner", url: "https://coursejoiner.com/" },
                { name: "CourseFolder", url: "https://coursefolder.org/" },
                { name: "CourseTime", url: "https://coursetime.net/" },
                { name: "Coursera", url: "https://www.coursera.org/" },
                { name: "Courses Bag", url: "https://coursesbag.com/" },
                { name: "DownloadFreeCourse", url: "https://downloadfreecourse.com/" },
                { name: "edX", url: "https://www.edx.org/" },
                { name: "FreeCourseNet", url: "https://freecoursenet.com/" },
                { name: "FreeCourseSite", url: "https://freecoursesite.com/" },
                { name: "FreeCoursesDownload", url: "https://freecoursesdownload.net/" },
                { name: "FreeEducationWeb", url: "https://freeeducationweb.com/" },
                { name: "FutureLearn", url: "https://www.futurelearn.com/" },
                { name: "GetFreeCourses", url: "https://getfreecourses.co/" },
                { name: "Khan Academy (darmowe)", url: "https://www.khanacademy.org/" },
                { name: "LinkedIn Learning", url: "https://www.linkedin.com/learning/" },
                { name: "MIT OpenCourseWare", url: "https://ocw.mit.edu/" },
                { name: "Online Courses Club", url: "https://online-courses.club/" },
                { name: "OpenLearn (The Open University)", url: "https://www.open.edu/openlearn/" },
                { name: "Pluralsight", url: "https://www.pluralsight.com/" },
                { name: "Skillshare", url: "https://www.skillshare.com/" },
                { name: "Udemy (legalne kursy)", url: "https://www.udemy.com/" }
            ]
        },
        {
            id: 'audiobooki',
            title: '🎧 Audiobooki',
            links: [
                { name: "AppAudioBooks", url: "https://appaudiobooks.com/" },
                { name: "Audible (Amazon, legalne)", url: "https://www.audible.com/" },
                { name: "AudioAZ", url: "https://audioaz.com/" },
                { name: "Audiobook Bay (Torrenty)", url: "https://audiobookbay.lu/", tag: "⭐" },
                { name: "Audiobook Treasure", url: "https://audiobooktreasure.com/" },
                { name: "AudiobookCovers", url: "https://audiobookcovers.com/" },
                { name: "Audiobooks For Soul", url: "https://audiobooks4soul.com/" },
                { name: "AudioBookShelf (self-hosted server)", url: "https://audiobookshelf.org/" },
                { name: "AudioBooksBee", url: "https://audiobooksbee.com/" },
                { name: "Archive.org Audiobooks & Poetry", url: "https://archive.org/details/audio_bookspoetry" },
                { name: "Big AudioBooks", url: "https://bigaudiobooks.com/" },
                { name: "Book Audiobooks", url: "https://bookaudiobooks.com/" },
                { name: "Book Radio", url: "https://bookradio.vercel.app/" },
                { name: "CD Audiobook", url: "https://cdaudiobook.com/" },
                { name: "Chirp Books", url: "https://www.chirpbooks.com/" },
                { name: "Digitalbook", url: "https://www.digitalbook.io/" },
                { name: "Downpour", url: "https://www.downpour.com/" },
                { name: "Find Audiobook", url: "https://findaudiobook.app/" },
                { name: "Free Classic AudioBooks", url: "https://www.freeclassicaudiobooks.com/" },
                { name: "FullLengthAudiobooks", url: "https://fulllengthaudiobooks.net/" },
                { name: "GalaxyAudiobook", url: "https://galaxyaudiobook.com/" },
                { name: "GoldenAudiobook", url: "https://goldenaudiobook.com/" },
                { name: "HD Audio Books", url: "https://hdaudiobooks.com/" },
                { name: "Hot Audiobooks", url: "https://hotaudiobooks.com/" },
                { name: "Kobo Audiobooks", url: "https://www.kobo.com/audiobooks" },
                { name: "LearnOutLoud", url: "https://www.learnoutloud.com/Free-Audiobooks" },
                { name: "LibriVox (Darmowe, legalne)", url: "https://librivox.org/" },
                { name: "LitGu.ru", url: "https://litgu.ru/" },
                { name: "Mobilism Audiobooks", url: "https://forum.mobilism.org/viewforum.php?f=124", tag: "⭐" },
                { name: "MyAnonamouse (Prywatny tracker)", url: "https://www.myanonamouse.net/", tag: "⭐" },
                { name: "Narrator AI (AI-generated audiobooks)", url: "https://www.narrator.ai/" },
                { name: "NEPU Audiobooks", url: "https://nepu.to/ebooks", tag: "⭐" },
                { name: "Scribd Audiobooks", url: "https://www.scribd.com/audiobooks" },
                { name: "Spotify Audiobooks", url: "https://open.spotify.com/artist/1FSWXfsYsosTxjcV9WoLax" },
                { name: "Storynory (Dla dzieci)", url: "https://www.storynory.com/" },
                { name: "Storytel", url: "https://www.storytel.com/" },
                { name: "Tokybook", url: "https://tokybook.com/", tag: "⭐" },
                { name: "zAudiobooks", url: "https://zaudiobooks.com/" }
            ]
        },
        {
            id: 'ksiazki-dla-dzieci',
            title: '👶 Książki Dla Dzieci',
            links: [
                { name: "Baldwin Library", url: "https://ufdc.ufl.edu/juv" },
                { name: "BookDash", url: "https://github.com/bookdash/bookdash-android-app" },
                { name: "byGosh", url: "https://bygosh.com" },
                { name: "Children's Books Forever", url: "https://www.childrensbooksforever.com/" },
                { name: "Epic! (dla dzieci 12-)", url: "https://www.getepic.com/" },
                { name: "International Children's Digital Library", url: "https://childrenslibrary.org/" },
                { name: "Magic Keys", url: "https://www.magickeys.com/books/" },
                { name: "Oxford Owl", url: "https://www.oxfordowl.co.uk/for-home/find-a-book/library-page/" },
                { name: "Speakaboos", url: "https://www.speakaboos.com/" },
                { name: "Starfall (czytanie dla najmłodszych)", url: "https://www.starfall.com/" },
                { name: "StoryWhale", url: "https://www.storywhale.com/" },
                { name: "Storynory", url: "https://www.storynory.com/" },
                { name: "TumbleBooks", url: "https://www.tumblebooks.com/" },
                { name: "Unite for Literacy", url: "https://www.uniteforliteracy.com/" }
            ]
        },
        {
            id: 'nuty-i-partytury',
            title: '🎼 Nuty i Partytury',
            links: [
                { name: "8notes", url: "https://www.8notes.com/" },
                { name: "Cantorion", url: "https://cantorion.org/" },
                { name: "Free-Scores", url: "https://www.free-scores.com/" },
                { name: "IMSLP / Petrucci Music Library", url: "https://imslp.org/" },
                { name: "MuseScore (wspólnota + darmowe nuty)", url: "https://musescore.com/" },
                { name: "Musicnotes", url: "https://www.musicnotes.com/" },
                { name: "Musopen (Darmowe nuty)", url: "https://musopen.org/" },
                { name: "Noteflight (edytor online)", url: "https://www.noteflight.com/" },
                { name: "Sheet Music Plus (legalne zakupy)", url: "https://www.sheetmusicplus.com/" },
                { name: "Virtual Sheet Music", url: "https://www.virtualsheetmusic.com/" }
            ]
        },
        {
            id: 'regionalne-i-wielojęzyczne',
            title: '🌍 Regionalne i Wielojęzyczne',
            links: [
                { name: "Biblioteka Piosenki (teksty piosenek)", url: "https://bibliotekapiosenki.pl/" },
                { name: "EU Publications (wiele języków)", url: "https://fedra.publications.europa.eu/" },
                { name: "Flibusta", url: "https://flibusta.is/" },
                { name: "Polona (Biblioteka Narodowa)", url: "https://pbc.biaman.pl/" },
                { name: "Project Gutenberg Francuski", url: "https://www.gutenberg.org/browse/languages/fr" },
                { name: "Project Gutenberg Hiszpański", url: "https://www.gutenberg.org/browse/languages/es" },
                { name: "Project Gutenberg Japoński", url: "https://www.gutenberg.org/browse/languages/ja" },
                { name: "Project Gutenberg Niemiecki", url: "https://www.gutenberg.org/browse/languages/de" },
                { name: "Project Gutenberg Polski", url: "https://www.gutenberg.org/browse/languages/pl" },
                { name: "Project Gutenberg Rosyjski", url: "https://www.gutenberg.org/browse/languages/ru" },
                { name: "The Free Book Library", url: "https://ebooks.i2p/" },
                { name: "Wikisource Chiński", url: "https://zh.wikisource.org/" },
                { name: "Wikisource Francuski", url: "https://fr.wikisource.org/" },
                { name: "Wikisource Japoński", url: "https://ja.wikisource.org/" },
                { name: "Wolne Lektury (polskie klasyki)", url: "https://wolnelektury.pl/" }
            ]
        },
        {
            id: 'wyszukiwarki-ebookow',
            title: '🔍 Wyszukiwarki eBooków',
            links: [
                { name: "Audiobook CSE", url: "https://cse.google.com/cse?cx=006516753008110874046:cwbbza56vhd", tag: "⭐" },
                { name: "Book Search Guide", url: "https://docs.google.com/document/d/1ZwWs8JOrlkrrqiHwkQSwc4_NM85Zbzc9t9ifQ1rHZgM/mobilebasic" },
                { name: "BookFinder (porównywarka cen)", url: "https://bookfinder.com/" },
                { name: "Goodreads (recenzje + znajdź ebooka)", url: "https://www.goodreads.com/" },
                { name: "ISBNdb", url: "https://isbndb.com/" },
                { name: "LibraryThing", url: "https://www.librarything.com/" },
                { name: "Open Slum", url: "https://open-slum.org/", tag: "🌐" },
                { name: "Rave Book Search", url: "https://ravebooksearch.com/" },
                { name: "Reading CSE", url: "https://cse.google.com/cse?cx=006516753008110874046:s9ddesylrm8" },
                { name: "Recherche Ebook (Francuska)", url: "https://recherche-ebook.fr/" },
                { name: "Textbook Search Engine", url: "https://cse.google.com/cse/publicurl?cx=011394183039475424659:5bfyqg89ers" },
                { name: "WorldCat (katalog bibliotek światowych)", url: "https://www.worldcat.org/" }
            ]
        },
        {
            id: 'czytniki-i-narzedzia',
            title: '🛠️ Czytniki i Narzędzia',
            links: [
                { name: "AccelaReader", url: "https://accelareader.com/" },
                { name: "acsm-calibre-plugin", url: "https://github.com/Leseratte10/acsm-calibre-plugin" },
                { name: "Adobe Digital Editions", url: "https://www.adobe.com/solutions/ebook/digital-editions/download.html" },
                { name: "Alexandria", url: "https://github.com/btpf/Alexandria" },
                { name: "All My Books", url: "https://www.bolidesoft.com/allmybooks.html" },
                { name: "Amazon Kindle EPUB Fix", url: "https://kindle-epub-fix.netlify.app/" },
                { name: "Annas Archive Reader", url: "https://annas-archive.org/view" },
                { name: "AnyFlip", url: "https://anyflip.com/" },
                { name: "Apple Books", url: "https://www.apple.com/ios/books/" },
                { name: "Aquile Reader", url: "https://apps.microsoft.com/detail/9p08t4jltqnk" },
                { name: "AudiobookShelf", url: "https://www.audiobookshelf.org/" },
                { name: "BookViser", url: "https://www.bookviser.com/" },
                { name: "Bookworm", url: "https://github.com/babluboy/bookworm" },
                { name: "Calibre (Zarządzanie biblioteką)", url: "https://calibre-ebook.com/", tag: "⭐" },
                { name: "Calibre-Web-Automated", url: "https://github.com/crocodilestick/Calibre-Web-Automated" },
                { name: "ComparisonTabl.es", url: "https://comparisontabl.es/" },
                { name: "DeDRM_tools", url: "https://github.com/noDRM/DeDRM_tools", tag: "🌐" },
                { name: "DjVuLibr", url: "https://djvu.sourceforge.net/" },
                { name: "Doqment", url: "https://github.com/shivaprsd/doqment" },
                { name: "dotepub", url: "https://dotepub.com/" },
                { name: "EBook Reader", url: "https://epub-reader.online/" },
                { name: "Ebook-Translator", url: "https://translator.bookfere.com", tag: "⭐" },
                { name: "EinkBro", url: "https://github.com/plateaukao/einkbro", tag: "⭐" },
                { name: "ePub Reader Online", url: "https://www.ofoct.com/viewer/epub-reader-online.html" },
                { name: "Evince", url: "https://apps.gnome.org/Evince/" },
                { name: "FanFicFare", url: "https://github.com/JimmXinu/FanFicFare" },
                { name: "FBReader", url: "https://apps.apple.com/app/fbreader-epub-and-fb2-reader/id1067172178" },
                { name: "FBReader (multiplatformowy)", url: "https://www.fbreader.org/" },
                { name: "FF PDF", url: "https://github.com/sdushantha/ff-pdf/" },
                { name: "FicHub", url: "https://fichub.net/" },
                { name: "Flow OSS (Czytnik EPUB)", url: "https://www.flowoss.com/" },
                { name: "foliate-js", url: "https://github.com/johnfactotum/foliate-js" },
                { name: "Foliate (Linux)", url: "https://github.com/JohnFactotum/foliate" },
                { name: "Foxit PDF Reader", url: "https://www.foxit.com/pdf-reader/", tag: "⭐" },
                { name: "Google Play Books", url: "https://play.google.com/store/apps/details?id=com.google.android.apps.books", tag: "⭐" },
                { name: "HowLongToRead", url: "https://howlongtoread.com/" },
                { name: "Icecream Reader", url: "https://icecreamapps.com/Ebook-Reader/" },
                { name: "iLovePDF", url: "https://www.ilovepdf.com/" },
                { name: "Jane Reader", url: "https://janereader.com/" },
                { name: "Kindle Cloud Reader", url: "https://www.amazon.com/kindle-dbs/fd/kcp" },
                { name: "KoboCloud", url: "https://github.com/fsantini/KoboCloud" },
                { name: "Koodo Reader", url: "https://www.koodo-reader.org/", tag: "⭐" },
                { name: "KoReader", url: "https://koreader.rocks/" },
                { name: "Libgen for Calibre", url: "https://github.com/poochinski/libgen-calibre-store-plugin" },
                { name: "Libby", url: "https://libbyapp.com/" },
                { name: "Librum", url: "https://librumreader.com" },
                { name: "Litera Reader", url: "https://litera-reader.com/" },
                { name: "Lithium (iOS)", url: "https://www.lithium.app/" },
                { name: "md2mobi", url: "https://md2mobi.lapw.at/" },
                { name: "Microsoft Edge (czytnik PDF/EPUB)", url: "https://www.microsoft.com/en-us/p/microsoft-edge/9ncbcv6hfnpm" },
                { name: "Minimal Reader", url: "https://www.minimalreader.xyz/" },
                { name: "MuPDF", url: "https://mupdf.com/" },
                { name: "Neat Reader", url: "https://www.neat-reader.cn/en/" },
                { name: "Okular", url: "https://okular.kde.org/" },
                { name: "Online Cloud File Viewer", url: "https://www.fviewer.com/" },
                { name: "Open Media Library", url: "https://openmedialibrary.com/" },
                { name: "Papeer", url: "https://papeer.tech/", tag: "⭐" },
                { name: "PDF Candy", url: "https://pdfcandy.com/" },
                { name: "PDF Escape", url: "https://www.pdfescape.com/" },
                { name: "PDF24 Tools (konwersja, edycja)", url: "https://pdf24.org/" },
                { name: "qPDFview", url: "https://launchpad.net/qpdfview" },
                { name: "Reader Mode", url: "https://readermode.io/" },
                { name: "Reader View", url: "https://webextension.org/listing/chrome-reader-view.html", tag: "⭐" },
                { name: "Readest", url: "https://readest.com/" },
                { name: "Readwok", url: "https://readwok.com/" },
                { name: "Remove Kindle DRM", url: "https://itsfoss.com/calibre-remove-drm-kindle/" },
                { name: "Scribd DL", url: "https://github.com/rkwyu/scribd-dl" },
                { name: "Sejda PDF", url: "https://www.sejda.com/" },
                { name: "Send to Kobo/Kindle", url: "https://send.djazz.se/" },
                { name: "Sigil Ebook", url: "https://sigil-ebook.com/" },
                { name: "Sioyek", url: "https://sioyek.info/" },
                { name: "SmallPDF", url: "https://smallpdf.com/" },
                { name: "Spreeder", url: "https://www.spreeder.com/app.php?intro=1", tag: "⭐" },
                { name: "Sumatra PDF", url: "https://www.sumatrapdfreader.org/" },
                { name: "The Open Book", url: "https://github.com/joeycastillo/The-Open-Book" },
                { name: "Thorium", url: "https://thorium.edrlab.org/" },
                { name: "WinDjView", url: "https://windjview.sourceforge.io/" },
                { name: "Yomu", url: "https://www.yomu-reader.com/" }
            ]
        },
        {
            id: 'calibre-libraries',
            title: '📚 Biblioteki Calibre',
            links: [
                { name: "Calibre Libraries", url: "https://rentry.co/FMHYBase64#calibre-libraries", tag: "↪️" }
            ]
        },
        {
            id: 'esoteric-cultural',
            title: '🔮 Ezoteryka i Kultura',
            links: [
                { name: "2Muslims", url: "https://www.2muslims.com/" },
                { name: "766 Occult Books", url: "https://rentry.co/FMHYBase64#766-occult-books" },
                { name: "84000", url: "https://84000.co/" },
                { name: "Alchemy Drive", url: "https://rentry.co/FMHYBase64#alchemy-drive" },
                { name: "Astrum Argenteum", url: "https://www.astrumargenteum.org/library/" },
                { name: "Awakening-Intuition", url: "https://www.awakening-intuition.com/ebooks.html" },
                { name: "Awesome Islam", url: "https://github.com/AhmedKamal/awesome-Islam" },
                { name: "Azrk's library", url: "https://rentry.co/FMHYBase64#azrks-library" },
                { name: "BhagavadGitaApp", url: "https://github.com/WirelessAlien/BhagavadGitaApp" },
                { name: "Bible.com", url: "https://www.bible.com/" },
                { name: "BibleGateway", url: "https://www.biblegateway.com/" },
                { name: "Biblioteca Pleyades", url: "https://www.bibliotecapleyades.net/esp_tema.htm" },
                { name: "Buddhism Dictionary", url: "http://www.buddhism-dict.net/ddb/" },
                { name: "Classics Ethereal Library", url: "https://www.ccel.org/" },
                { name: "CraftStuff", url: "https://rentry.co/FMHYBase64#craftstuff" },
                { name: "Dhamma Talks", url: "https://www.dhammatalks.org/" },
                { name: "Dhushara Research", url: "https://www.dhushara.com/index.htm" },
                { name: "DigiVatLib", url: "https://digi.vatlib.it/" },
                { name: "Early Christian Writings", url: "https://www.earlychristianwritings.com/index.html" },
                { name: "EatTheFruit", url: "https://www.eatthefruit.com/media-library/pdf-library/" },
                { name: "Encyclopedia Of Buddhism", url: "https://archive.org/details/EdwardA.IronsEncyclopediaOfBuddhismEncyclopediaOfWorldReligions/" },
                { name: "Encyclopedia Of Hinduism", url: "https://archive.org/details/ConstanceA.JonesJamesD.RyanEncyclopediaOfHinduism/" },
                { name: "Esoterica Drive", url: "https://rentry.co/FMHYBase64#archive" },
                { name: "Esoteric Archive", url: "https://esotericarchives.com/" },
                { name: "eSword", url: "https://e-sword.net/" },
                { name: "Five Prayers", url: "https://github.com/Five-Prayers/five-prayers-android" },
                { name: "Germanic Mythology", url: "https://www.germanicmythology.com/index.html" },
                { name: "Gnostic Society Library", url: "http://www.gnosis.org/library.html" },
                { name: "Grimoar.cz", url: "http://english.grimoar.cz/?Loc=key&Lng=2" },
                { name: "Halakhah", url: "https://www.halakhah.com/" },
                { name: "Hermetic International", url: "https://www.hermetics.net/" },
                { name: "Hermetics", url: "https://www.hermetics.org/library.html" },
                { name: "Hidden Bible", url: "http://www.hiddenbible.com/enoch/online.html" },
                { name: "HolyBooks", url: "https://holybooks.com/" },
                { name: "Humanitys Vault", url: "https://rentry.co/FMHYBase64#humanitys-vault" },
                { name: "IAPSOP", url: "http://iapsop.com/" },
                { name: "Inuit Myths", url: "https://www.inuitmyths.com/index.htm" },
                { name: "Jainism Library of Jain Literature", url: "https://www.atmadharma.com/index.html" },
                { name: "LeftHandPath", url: "https://rentry.co/FMHYBase64#lefthandpath" },
                { name: "Libris Adepti", url: "https://librisadepti.com/", tag: "⭐" },
                { name: "Logoi Library", url: "https://logoilibrary.com/" },
                { name: "magZtore", url: "https://t.me/magZtore" },
                { name: "Masonic Library", url: "https://masonicshop.com/masonic-library/" },
                { name: "Messy Occult Library", url: "https://rentry.co/FMHYBase64#messy-occult-library" },
                { name: "Muslim Scholars", url: "https://muslimscholars.info/" },
                { name: "OpenMaktaba", url: "https://openmaktaba.com/" },
                { name: "Public Witchcraft Library", url: "https://rentry.co/FMHYBase64#public-witchcraft-library" },
                { name: "Quran.com", url: "https://quran.com/" },
                { name: "Rosicrucian Esotericism Lecture", url: "https://rsarchive.org/" },
                { name: "Sacred Text Archive", url: "https://sacred-texts.com/", tag: "⭐" },
                { name: "Sefaria", url: "https://www.sefaria.org/" },
                { name: "Shankaracharya", url: "https://www.shankaracharya.org/" },
                { name: "Soren Megathread", url: "https://rentry.co/FMHYBase64#soren-megathread", tag: "🌐" },
                { name: "Spirituality Megadrive", url: "https://rentry.co/FMHYBase64#spirituality-megadrive" },
                { name: "Sunnah.com", url: "https://sunnah.com/" },
                { name: "Sutta Central", url: "https://suttacentral.net/" },
                { name: "Targum", url: "http://targum.info/targumic-texts/" },
                { name: "The Dead Sea Scrolls", url: "https://www.deadseascrolls.org.il/" },
                { name: "The Exerdex", url: "https://rentry.co/FMHYBase64#echerdex-repository", tag: "⭐" },
                { name: "The Library of Consciousness", url: "https://www.organism.earth/library/" },
                { name: "The Theosophical Society", url: "https://www.theosociety.org/" },
                { name: "TheIslam360", url: "https://theislam360.com/" },
                { name: "Theoi", url: "https://www.theoi.com/" },
                { name: "Vedabase", url: "https://vedabase.io/en/" },
                { name: "Vedanta Shastras", url: "https://www.shastras.com/" },
                { name: "WiLd's Occult Ebooks", url: "https://rentry.co/FMHYBase64#wilds-occult-ebook-sources", tag: "🌐" },
                { name: "Witchcraft Library", url: "https://rentry.co/FMHYBase64#witchcraft-library" }
            ]
        },
        {
            id: 'special-interest',
            title: '⭐ Książki Tematyczne',
            links: [
                { name: "Anarchist FAQ", url: "https://www.anarchistfaq.org/" },
                { name: "Anarcho-Copy", url: "https://anarcho-copy.org/" },
                { name: "Archive.Leftove.rs", url: "https://archive.leftove.rs/" },
                { name: "ArtFacultas", url: "https://t.me/ArtFacultas" },
                { name: "Artbooks Archive", url: "https://t.me/archive_artbooks" },
                { name: "Auto-Brochures.com", url: "https://www.auto-brochures.com/" },
                { name: "Avalon Library", url: "https://avalonlibrary.net/" },
                { name: "Booklet Library", url: "https://bookletlibrary.org/" },
                { name: "Communism Essays / FAQs", url: "https://dessalines.github.io/essays" },
                { name: "eBookHunter.net", url: "https://www.ebookhunter.net/" },
                { name: "Film Books", url: "https://rentry.co/FMHYBase64#film-books" },
                { name: "FreeSFOnline", url: "https://www.freesfonline.net/" },
                { name: "HourWolf", url: "https://www.hourwolf.com/sfbooks/" },
                { name: "Liberation School", url: "https://liberationschool.org/" },
                { name: "Marxists Internet Archive", url: "https://www.marxists.org/" },
                { name: "Project Aon", url: "https://www.projectaon.org/en/Main/Home" },
                { name: "QSL", url: "https://rentry.co/FMHYBase64#qsl" },
                { name: "Red Texts", url: "https://redtexts.org/" },
                { name: "Survival / Prepping", url: "https://www.reddit.com/r/FREEMEDIAHECKYEAH/wiki/storage#wiki_survival", tag: "↪️" },
                { name: "The Anarchist Library", url: "https://theanarchistlibrary.org/special/index", tag: "⭐" },
                { name: "The Eldritch Dark", url: "http://www.eldritchdark.com/" },
                { name: "The Trove", url: "https://web.archive.org/web/20210614215400/https://thetrove.is/" },
                { name: "TTRPG Torrent", url: "https://rentry.co/FMHYBase64#ttrpg-books" },
                { name: "Trans Reads", url: "https://transreads.org/" },
                { name: "VGArtbooks", url: "https://vk.com/vgartbooks" }
            ]
        },
        {
            id: 'visual-media',
            title: '🎨 Media Wizualne',
            links: [
            ]
        },

        {
            id: 'newspapers',
            title: '📰 Gazety',
            links: [
                { name: "Archive.org Newspapers", url: "https://rentry.co/FMHYBase64#archiveorg-newspapers" },
                { name: "Bypass Newspaper Paywalls", url: "https://www.reddit.com/r/FREEMEDIAHECKYEAH/wiki/internet-tools#wiki_.25B7_paywall_bypass", tag: "↪️" },
                { name: "Chronicling America", url: "https://chroniclingamerica.loc.gov/newspapers/" },
                { name: "EngNewspapers", url: "https://vk.com/engnewspapers" },
                { name: "Europeana Newspapers", url: "https://www.europeana.eu/en/collections/topic/18-newspapers" },
                { name: "Front Pages", url: "https://www.frontpages.com/" },
                { name: "FultonHistory", url: "https://fultonhistory.com/Fulton.html" },
                { name: "Google Newspaper Search", url: "https://news.google.com/newspapers", tag: "⭐" },
                { name: "Kiosko", url: "https://en.kiosko.net/" },
                { name: "LA Times", url: "https://latimes.newspapers.com/" },
                { name: "Library of Congress Newspapers", url: "https://guides.loc.gov/foreign-newspapers/digital-resources" },
                { name: "Loc.gov Newspapers", url: "https://www.loc.gov/newspapers/" },
                { name: "Meta-Press", url: "https://www.meta-press.es/" },
                { name: "Mobilism Newspapers", url: "https://forum.mobilism.org/viewforum.php?f=123", tag: "⭐" },
                { name: "Newspaper Map", url: "https://newspapermap.com/" },
                { name: "Newspapers", url: "https://newspapers.com/" },
                { name: "SoftArchive", url: "https://softarchive.download/newspapers" },
                { name: "ThoughtCo", url: "https://www.thoughtco.com/us-historical-newspapers-online-by-state-1422215" },
                { name: "Veridian", url: "https://veridiansoftware.com/collections/", tag: "🌐" },
                { name: "World-Newspapers", url: "https://world-newspapers.com/" },
                { name: "Worldwide News Sites", url: "https://www.reddit.com/r/FREEMEDIAHECKYEAH/wiki/misc#wiki_.25BA_news", tag: "↪️" }
            ]
        },
        {
            id: 'history-books',
            title: '📜 Książki Historyczne',
            links: [
                { name: "Archives.gov", url: "https://archives.gov/" },
                { name: "ByzantineMilitary", url: "https://byzantinemilitary.blogspot.com/" },
                { name: "CELT", url: "https://celt.ucc.ie/" },
                { name: "Classical Libraries", url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vRkUFBfVVqv5Tr2aZS4apFNpTJ-ys6VqeQxgsAI1v7cH5putIgchYWJAVGHuu0lWGmdD2DU7Vb1o7XH/pubhtml" },
                { name: "De Re Militari", url: "https://deremilitari.org/articles/" },
                { name: "Digital Archive", url: "https://digitalarchive.wilsoncenter.org/collections" },
                { name: "DigitalTransgenderArchive", url: "https://www.digitaltransgenderarchive.net/" },
                { name: "Duke University Library", url: "https://repository.duke.edu/catalog?utf8=%E2%9C%93&search_scope=https%3A%2F%2Frepository.duke.edu%2Fcatalog&q=&search_field=all_fields" },
                { name: "Early English Books", url: "https://quod.lib.umich.edu/e/eebogroup/" },
                { name: "EarlyModernTexts", url: "https://www.earlymoderntexts.com", tag: "⭐" },
                { name: "Encyclopaedia Iranica", url: "https://www.iranicaonline.org/" },
                { name: "Europeana", url: "https://www.europeana.eu/" },
                { name: "History Newsboys of 1899", url: "https://rentry.co/FMHYBase64#history-newsboys-of-1899" },
                { name: "HornTip", url: "https://www.horntip.com/" },
                { name: "In Parenthesis", url: "https://www.yorku.ca/inpar/" },
                { name: "Jewish Virtual Library", url: "https://www.jewishvirtuallibrary.org/" },
                { name: "Making of America", url: "https://quod.lib.umich.edu/m/moa/" },
                { name: "Media History", url: "https://mediahistoryproject.org/", tag: "⭐" },
                { name: "Perseus Digital Library", url: "https://www.perseus.tufts.edu/hopper/" },
                { name: "r/AskHistorians Recommended", url: "https://www.reddit.com/r/AskHistorians/wiki/books", tag: "🌐" },
                { name: "Radical Scatters", url: "http://radicalscatters.unl.edu/indices.html" },
                { name: "Smithsonian Institution Archives", url: "https://siarchives.si.edu/" },
                { name: "textfiles.com", url: "http://textfiles.com/" },
                { name: "The History of Maritime Piracy", url: "http://www.cindyvallar.com/pirates.html" },
                { name: "The Morgan Library Museum", url: "https://www.themorgan.org/music" },
                { name: "The National Archives", url: "https://nationalarchives.gov.uk/" },
                { name: "ToposText", url: "https://topostext.org/" },
                { name: "Van Gogh Letters", url: "https://vangoghletters.org/vg/" },
                { name: "WarshipsResearch", url: "https://warshipsresearch.blogspot.com/" },
                { name: "Wiktenauer", url: "https://wiktenauer.com/" },
                { name: "World History", url: "https://www.worldhistory.org/", tag: "⭐" },
                { name: "WorldRadioHistory", url: "https://worldradiohistory.com/" }
            ]
        },
        {
            id: 'quotes-poetry',
            title: '✒️ Cytaty i Poezja',
            links: [
                { name: "AZQuotes", url: "https://www.azquotes.com/" },
                { name: "BrainyQuote", url: "https://www.brainyquote.com/" },
                { name: "DiscoverPoetry", url: "https://discoverpoetry.com/" },
                { name: "PoemHunter", url: "https://www.poemhunter.com/" },
                { name: "Poetry In Translation", url: "https://www.poetryintranslation.com/" },
                { name: "Poetry.com", url: "https://www.poetry.com/" },
                { name: "PoetryArchive", url: "https://poetryarchive.org/" },
                { name: "Poetry Foundation", url: "https://www.poetryfoundation.org/", tag: "⭐" },
                { name: "Poets.org", url: "https://poets.org/" },
                { name: "Quote Collections", url: "https://rentry.co/zeoemsh9" },
                { name: "QuoteGarden", url: "https://www.quotegarden.com/" },
                { name: "QuoteMaster", url: "https://www.quotemaster.org/" },
                { name: "RUVerses", url: "https://ruverses.com/" },
                { name: "ScottishPoetryLibrary", url: "https://www.scottishpoetrylibrary.org.uk/" },
                { name: "TheOtherPages", url: "https://theotherpages.org/quote.html" },
                { name: "Wikiquote", url: "https://en.wikiquote.org", tag: "⭐" }
            ]
        },
        {
            id: 'manuals',
            title: '🔧 Instrukcje i Poradniki',
            links: [
                { name: "CarPDFManual", url: "https://www.carpdfmanual.com/" },
                { name: "Charm", url: "https://charm.li/" },
                { name: "David Kleinfeld Laboratory", url: "https://neurophysics.ucsd.edu/Manuals/" },
                { name: "Exploitee.rs", url: "https://www.exploitee.rs/" },
                { name: "iFixIt", url: "https://www.ifixit.com/" },
                { name: "JDMFSM", url: "https://jdmfsm.info/Auto/" },
                { name: "Manned.org", url: "https://manned.org/" },
                { name: "ManualLib", url: "https://www.manuallib.com/" },
                { name: "Manuals & Schematics", url: "https://redd.it/nlw3er", tag: "🌐" },
                { name: "Ownersman.com", url: "https://ownersman.com/" },
                { name: "PremierProduct", url: "https://www.premierproducts-uk.co.uk/" },
                { name: "RepairWiki", url: "https://repair.wiki/", tag: "⭐" },
                { name: "Restarters", url: "https://wiki.restarters.net/" },
                { name: "WonderHowTo", url: "https://www.wonderhowto.com/" }
            ]
        },
        {
            id: 'tracking-database',
            title: '📋 Śledzenie i Bazy Danych',
            links: [
                { name: "Anobii", url: "https://www.anobii.com/" },
                { name: "BookWyrm", url: "https://joinbookwyrm.com/" },
                { name: "Books Search", url: "https://books-search.typesense.org/" },
                { name: "CandlApp", url: "https://www.candlapp.com/" },
                { name: "GoodReads", url: "https://www.goodreads.com/", tag: "⭐" },
                { name: "Hardcover", url: "https://hardcover.app/" },
                { name: "ISFDB", url: "https://isfdb.org/" },
                { name: "libib", url: "https://www.libib.com/" },
                { name: "LibraryThing", url: "https://www.librarything.com/" },
                { name: "Listal", url: "https://www.listal.com/" },
                { name: "Literal", url: "https://literal.club/" },
                { name: "nooSFere", url: "https://www.noosfere.org/" },
                { name: "Oku", url: "https://oku.club/" },
                { name: "rate.house", url: "https://rate.house/" },
                { name: "Romance.io", url: "https://www.romance.io/" },
                { name: "StoryGraph", url: "https://www.thestorygraph.com/", tag: "⭐" }
            ]
        },
        {
            id: 'curated-recommendations',
            title: '👍 Rekomendacje i Polecane',
            links: [
                { name: "5000 Best", url: "http://5000best.com/books/" },
                { name: "BookHype", url: "https://bookhype.com/" },
                { name: "Bookmarks Review", url: "https://bookmarks.reviews/" },
                { name: "BookStash", url: "https://bookstash.io/" },
                { name: "Break the Bubble!", url: "https://abooklike.foo/escape" },
                { name: "Charts and Culture", url: "https://pastebin.com/uRDJVGkL" },
                { name: "En", url: "https://en.app/" },
                { name: "Five Books", url: "https://fivebooks.com/", tag: "⭐" },
                { name: "Gnooks", url: "https://www.gnooks.com/" },
                { name: "GoodBooks", url: "https://www.goodbooks.io/" },
                { name: "Hacker Recommended Books", url: "https://hacker-recommended-books.vercel.app/" },
                { name: "Litsy", url: "https://www.litsy.com/" },
                { name: "Literature-Map", url: "https://www.literature-map.com/" },
                { name: "Mind Expanding Books", url: "https://mindexpandingbooks.com" },
                { name: "Most Recommended Books", url: "https://www.mostrecommendedbooks.com/" },
                { name: "Nevix", url: "https://nevix.com/" },
                { name: "Newvella", url: "https://newvella.com/" },
                { name: "PagePundit", url: "https://pagepundit.com/" },
                { name: "r/ifyoulikeblank", url: "https://www.reddit.com/r/ifyoulikeblank/" },
                { name: "r/TrueLit Top 100 Lists", url: "https://www.reddit.com/r/TrueLit/wiki/top100lists" },
                { name: "Read This Twice", url: "https://readthistwice.com/" },
                { name: "Readow", url: "https://readow.ai/" },
                { name: "Reddit Reads", url: "https://www.redditreads.com/" },
                { name: "RecommendMeABook", url: "https://recommendmeabook.com/" },
                { name: "Shepherd", url: "https://shepherd.com/" },
                { name: "TasteDive", url: "https://tastedive.com/books", tag: "⭐" },
                { name: "The Greatest Books", url: "https://www.thegreatestbooks.org/", tag: "⭐" },
                { name: "WhichBook", url: "https://www.whichbook.net/" }
            ]
        }
    ]
};