const pageData = {
    "sections": [
        {
            "id": "filmy-dokumentalne",
            "title": "🎥 Filmy Dokumentalne",
            "links": [
                { "name": "⭐ 1337x Documentaries", "url": "https://1337x.to/top-100-documentaries", "tag": "Torrent" },
                { "name": "ARTE", "url": "https://www.arte.tv/" },
                { "name": "⭐ Documentary+", "url": "https://www.docplus.com/" },
                { "name": "⭐ DocumentaryArea", "url": "https://www.documentaryarea.com/" },
                { "name": "DocumentaryHeaven", "url": "https://documentaryheaven.com/" },
                { "name": "Documentary Network", "url": "https://documentary.net/" },
                { "name": "Documentary Storm", "url": "https://www.documentarystorm.com/" },
                { "name": "Documentary Tube", "url": "https://www.documentarytube.com/" },
                { "name": "Films For Action", "url": "https://www.filmsforaction.org/" },
                { "name": "Folkstreams", "url": "https://www.folkstreams.net/" },
                { "name": "⭐ IHaveNoTV", "url": "https://ihavenotv.com" },
                { "name": "LearnOutLoud", "url": "https://www.learnoutloud.com/" },
                { "name": "Media Burn Archive", "url": "https://mediaburn.org/" },
                { "name": "MVGroup", "url": "https://forums.mvgroup.org/" },
                { "name": "Nat Geo", "url": "https://www.natgeotv.com/" },
                { "name": "PBS", "url": "https://www.pbs.org/video/" },
                { "name": "r/Documentaries", "url": "https://reddit.com/r/Documentaries" },
                { "name": "Rocumentaries", "url": "https://rocumentaries.com/" },
                { "name": "Thought Maybe", "url": "https://thoughtmaybe.com/" },
                { "name": "Top Documentary Films", "url": "https://topdocumentaryfilms.com/" },
                { "name": "Videoneat", "url": "https://www.videoneat.com/" },
                { "name": "WatchDocumentaries", "url": "https://watchdocumentaries.com/" }
            ]
        },
        {
            "id": "kursy-streaming",
            "title": "🎓 Kursy (Streaming)",
            "links": [
                { "name": "Alison", "url": "https://alison.com/" },
                { "name": "🌐 Awesome Courses", "url": "https://github.com/prakhar1989/awesome-courses", "tag": "Kursy" },
                { "name": "⭐ Class Central", "url": "https://www.classcentral.com/", "tag": "Wyszukiwarka kursów" },
                { "name": "CourseBuffet", "url": "https://www.coursebuffet.com/", "tag": "Wyszukiwarka kursów" },
                { "name": "Course CSE", "url": "https://cse.google.com/cse?cx=67ed14bf7b99643e3", "tag": "Wyszukiwarka kursów" },
                { "name": "⭐ Coursera", "url": "https://www.coursera.org/", "tag": "Kursy" },
                { "name": "Crash Course", "url": "https://thecrashcourse.com/" },
                { "name": "DigitalGarage", "url": "https://grow.google/intl/uk/courses-and-tools/", "tag": "Kursy Google" },
                { "name": "EbookFoundation Courses", "url": "https://github.com/EbookFoundation/free-programming-books#free-online-courses", "tag": "Kursy" },
                { "name": "⭐ edX", "url": "https://www.edx.org/", "tag": "Kursy" },
                { "name": "Git.ir", "url": "https://en.git.ir/", "tag": "Kursy" },
                { "name": "Gresham College", "url": "https://www.gresham.ac.uk/", "tag": "Wykłady" },
                { "name": "⭐ Khan Academy", "url": "https://www.khanacademy.org/", "tag": "Kursy" },
                { "name": "LearnOutLoud", "url": "https://www.learnoutloud.com/" },
                { "name": "🌐 Limnology", "url": "https://limnology.co/", "tag": "Edukacyjne kanały YouTube" },
                { "name": "⭐ MitOpenCourseWare", "url": "https://ocw.mit.edu/", "tag": "Kursy" },
                { "name": "OLI", "url": "https://oli.cmu.edu/independent-learner-courses/", "tag": "Kursy" },
                { "name": "OpenCulture", "url": "https://www.openculture.com/freeonlinecourses", "tag": "Kursy" },
                { "name": "OpenHPI", "url": "https://open.hpi.de/", "tag": "Kursy" },
                { "name": "OpenLearn", "url": "https://www.open.edu/openlearn/", "tag": "Kursy" },
                { "name": "Saylor Academy", "url": "https://learn.saylor.org/", "tag": "Kursy" },
                { "name": "Video Lectures", "url": "https://videolectures.net/", "tag": "Wykłady" }
            ]
        },
        {
            "id": "pobieranie-kursow",
            "title": "💾 Pobieranie Kursów",
            "links": [
                { "name": "AfraTafreeh", "url": "https://afratafreeh.com/" },
                { "name": "CertCommunity", "url": "https://www.certcommunity.org/forum/", "tag": "Kursy certyfikacyjne IT" },
                { "name": "⭐ Course Busters", "url": "https://t.me/coursebusters", "tag": "Dostęp do Course Busters" },
                { "name": "firerip", "url": "https://rentry.co/FMHYBase64#firerip", "tag": "Pobieranie kursów Fireship.io" },
                { "name": "FreeCourseSite", "url": "https://freecoursesite.com/", "tag": "Strony z torrentami" },
                { "name": "🌐 Free-Courses-For-Everyone", "url": "https://github.com/MasterBrian99/Free-Courses-For-Everyone", "tag": "Indeks stron z kursami" },
                { "name": "FreeEducationWeb", "url": "https://freeeducationweb.com/" },
                { "name": "⭐ HackNation", "url": "https://hacksnation.com/" },
                { "name": "learningDL", "url": "https://learningdl.net/", "tag": "Wymagany leech" },
                { "name": "LinkedIn_Learning", "url": "https://t.me/linkedin_learning", "tag": "Kursy LinkedIn" },
                { "name": "OneHack", "url": "https://onehack.us/" },
                { "name": "Revival", "url": "https://rentry.co/FMHYBase64#revival", "tag": "Kursy" },
                { "name": "technet24", "url": "https://technet24.ir/category/videos" },
                { "name": "⭐ TutFlix", "url": "https://tutflix.org/", "tag": "Rejestracja w piątki" },
                { "name": "⭐ tut4dl", "url": "https://tut4it.com/" }
            ]
        },
        {
            "id": "strony-edukacyjne",
            "title": "🧠 Strony Edukacyjne",
            "links": [
                { "name": "AFAIK", "url": "https://afaik.io/", "tag": "Mapa nauki" },
                { "name": "AirVectors", "url": "https://www.airvectors.net/", "tag": "Indeksy samolotów" },
                { "name": "Alchemy Forums", "url": "https://alchemyforums.com/index.php" },
                { "name": "AnimaGraffs", "url": "https://animagraffs.com/", "tag": "Animowane infografiki" },
                { "name": "Appropedia", "url": "https://www.appropedia.org/", "tag": "Wiki o zrównoważonym rozwoju" },
                { "name": "⁠Basic Knowledge 101", "url": "https://www.basicknowledge101.com/", "tag": "Baza wiedzy" },
                { "name": "British & Exotic Mineralogy", "url": "https://www.c82.net/mineralogy/", "tag": "Baza danych mineralogii" },
                { "name": "Common Misconceptions", "url": "https://en.wikipedia.org/wiki/List_of_common_misconceptions", "tag": "Indeks powszechnych błędnych przekonań" },
                { "name": "coolguid.es", "url": "https://coolguid.es/", "tag": "Poradniki i samouczki" },
                { "name": "HerbologyY", "url": "https://t.me/HerbologyY", "tag": "Zielarstwo / Telegram" },
                { "name": "HowStuffWorks", "url": "https://www.howstuffworks.com/" },
                { "name": "Information Is Beautiful", "url": "https://informationisbeautiful.net/", "tag": "Dane / Infografiki" },
                { "name": "ISODN", "url": "https://discord.gg/k3zkD2y", "tag": "Społeczność Międzynarodowych Olimpiad Naukowych" },
                { "name": "Learn About", "url": "https://learning.google.com/experiments/learn-about", "tag": "Edukacyjne AI od Google" },
                { "name": "🌐 Learn Anything", "url": "https://learn-anything.xyz/", "tag": "Wyszukiwarka zasobów do nauki" },
                { "name": "LitCharts", "url": "https://www.litcharts.com/", "tag": "Przewodniki po literaturze" },
                { "name": "masterWiki", "url": "https://masterwiki.how/", "tag": "Klasy MasterClass jako artykuły wikiHow" },
                { "name": "media.ccc.de", "url": "https://media.ccc.de/", "tag": "Prezentacje edukacyjne" },
                { "name": "Memory Toys", "url": "https://memory.toys/", "tag": "Testy / Trening pamięci" },
                { "name": "🌐 OpenCulture", "url": "https://www.openculture.com/", "tag": "Zasoby do nauki" },
                { "name": "🌐 OSSU", "url": "https://github.com/ossu/", "tag": "Zasoby do nauki" },
                { "name": "P2PU", "url": "https://www.p2pu.org/", "tag": "Dołącz do grup uczących się" },
                { "name": "Quetre", "url": "https://quetre.iket.me", "tag": "Społeczności Q&A" },
                { "name": "⭐ r/coolguides", "url": "https://reddit.com/r/coolguides/", "tag": "Poradniki i samouczki" },
                { "name": "⭐ r/educationalgifs", "url": "https://reddit.com/r/educationalgifs", "tag": "Ucz się z GIF-ów" },
                { "name": "⭐ r/explainlikeimfive", "url": "https://www.reddit.com/r/explainlikeimfive/", "tag": "Proste wyjaśnienia" },
                { "name": "ShipSpotting", "url": "https://www.shipspotting.com/", "tag": "Indeks statków / Obrazy" },
                { "name": "Stack Exchange", "url": "https://stackexchange.com/", "tag": "Społeczności Q&A" },
                { "name": "Ted Talks", "url": "https://www.ted.com/", "tag": "Inspirujące i edukacyjne wykłady" },
                { "name": "🌐 The Free Learning List", "url": "https://freelearninglist.org/", "tag": "Zasoby do nauki" },
                { "name": "⭐ The Punctuation Guide", "url": "https://www.thepunctuationguide.com/", "tag": "Przewodnik po interpunkcji" },
                { "name": "🌐 Wakelet", "url": "https://wakelet.com/explore", "tag": "Zasoby do nauki" },
                { "name": "🌐 WISC", "url": "https://www.wisc-online.com/", "tag": "Zasoby do nauki" }
            ]
        },
        {
            "id": "umiejetnosci-i-hobby",
            "title": "🎨 Umiejętności i Hobby",
            "links": [
                { "name": "ActivistHandbook", "url": "https://activisthandbook.org/", "tag": "Poradniki aktywistyczne" },
                { "name": "Animated Knots", "url": "https://www.animatedknots.com/", "tag": "Naucz się wiązać węzły" },
                { "name": "BeatBlackjack", "url": "https://www.beatblackjack.org/", "tag": "Naucz się liczyć karty w blackjacku" },
                { "name": "Bridge Command", "url": "https://www.bridgecommand.co.uk/", "tag": "Symulator mostka kapitańskiego" },
                { "name": "diyhpluswiki", "url": "https://diyhpl.us/wiki/", "tag": "DIY Biohacking" },
                { "name": "Erowid", "url": "https://www.erowid.org/", "tag": "Informacje o substancjach psychoaktywnych" },
                { "name": "Excel Practice Online", "url": "https://excel-practice-online.com/", "tag": "Ćwiczenia z Excela" },
                { "name": "HypnosisChatBooks", "url": "https://t.me/HypnosisChatBooks", "tag": "Hipnoza / Telegram" },
                { "name": "Ian's Shoelace Site", "url": "https://www.fieggen.com/shoelace/", "tag": "Naucz się wiązać sznurówki" },
                { "name": "LibraryOfJuggling", "url": "https://libraryofjuggling.com/", "tag": "Baza technik żonglerskich" },
                { "name": "Lock Picking 101", "url": "https://www.lockpicking101.com/", "tag": "Forum o otwieraniu zamków" },
                { "name": "Make it Yourself", "url": "https://makeityourself.org/", "tag": "1000 projektów DIY" },
                { "name": "Perry Morse", "url": "https://www.perry.qa/morse", "tag": "Naucz się alfabetu Morse'a" },
                { "name": "Polymaker", "url": "https://wiki.polymaker.com/", "tag": "Przewodnik po druku 3D" },
                { "name": "PsychonautWiki", "url": "https://psychonautwiki.org/wiki/Main_Page", "tag": "Wiki o psychonautyce" },
                { "name": "Rookie Road", "url": "https://www.rookieroad.com/", "tag": "Przewodniki sportowe" },
                { "name": "Shroomery", "url": "https://www.shroomery.org/", "tag": "Forum o magicznych grzybach" }
            ]
        },
        {
            "id": "nauka-interaktywna",
            "title": "🎮 Nauka Interaktywna",
            "links": [
                { "name": "EduMedia", "url": "https://www.edumedia.com/", "tag": "Interaktywne symulacje naukowe" },
                { "name": "Explorabl.es", "url": "https://explorabl.es/", "tag": "Quizy / Poradniki / Gry" },
                { "name": "JavaLab", "url": "https://javalab.org/en/", "tag": "Interaktywne symulacje naukowe" },
                { "name": "LabXchange", "url": "https://www.labxchange.org/", "tag": "Interaktywne symulacje naukowe" },
                { "name": "Matthen", "url": "https://blog.matthen.com/", "tag": "Animacje matematyczne i naukowe" },
                { "name": "MinuteLabs", "url": "https://minutelabs.io/", "tag": "Quizy / Poradniki / Gry" },
                { "name": "⭐ PhET", "url": "https://phet.colorado.edu/", "tag": "Interaktywne lekcje" },
                { "name": "Wikiversity", "url": "https://www.wikiversity.org/", "tag": "Quizy / Poradniki / Gry" }
            ]
        },
        {
            "id": "historia",
            "title": "📜 Historia",
            "links": [
                { "name": "911 Realtime", "url": "https://911realtime.org/", "tag": "9/11 w czasie rzeczywistym" },
                { "name": "Arachne", "url": "https://arachne.dainst.org/", "tag": "Archiwum obrazów antycznych rzeźb" },
                { "name": "Athena", "url": "https://athena.unige.ch/athena/", "tag": "Encyklopedia historii Grecji" },
                { "name": "BlackPast", "url": "https://www.blackpast.org/", "tag": "Encyklopedia historii Afryki" },
                { "name": "CARI", "url": "https://cari.institute/", "tag": "Historia estetyki designu" },
                { "name": "ChinesePosters", "url": "https://chineseposters.net/", "tag": "Historia chińskich plakatów propagandowych" },
                { "name": "ETHW", "url": "https://ethw.org/", "tag": "Wiki historii inżynierii i technologii" },
                { "name": "EyewitnesstoHistory", "url": "http://www.eyewitnesstohistory.com/index.html", "tag": "Historyczne relacje naocznych świadków" },
                { "name": "Historical Fashion", "url": "https://docs.google.com/document/d/1R8eulTsb9Zlc7h2H917dNJZS9s0rIq9OAu7LpSS9F2k/", "tag": "Zasoby o modzie historycznej" },
                { "name": "Historical Recipes", "url": "https://l-lists.com/en/lists/55cbww.html", "tag": "Indeks stron z przepisami historycznymi" },
                { "name": "⁠Historical Tech Tree", "url": "https://www.historicaltechtree.com/", "tag": "Historyczne osie czasu odkryć" },
                { "name": "⭐ Historic Films", "url": "https://www.historicfilms.com/", "tag": "Historyczne nagrania / filmy" },
                { "name": "⭐ Histography", "url": "https://histography.io/", "tag": "Oś czasu historii" },
                { "name": "Imperial War Museums", "url": "https://www.iwm.org.uk/", "tag": "Historyczne nagrania wojenne" },
                { "name": "ManuscriptMiniatures", "url": "https://manuscriptminiatures.com/", "tag": "Obrazy ze średniowiecznych manuskryptów" },
                { "name": "Mission US", "url": "https://www.mission-us.org/", "tag": "Gry edukacyjne o historii Ameryki" },
                { "name": "⭐ MorbidKuriosity", "url": "https://morbidkuriosity.com/", "tag": "Mroczna historia, zbrodnie, mity itp." },
                { "name": "Museo", "url": "https://museo.app/", "tag": "Wyszukiwarka muzeów" },
                { "name": "NuclearWeaponArchive", "url": "https://nuclearweaponarchive.org/", "tag": "Historia broni jądrowej" },
                { "name": "OnThisDay", "url": "https://www.onthisday.com/", "tag": "Co wydarzyło się danego dnia" },
                { "name": "PessimistsArchive", "url": "https://pessimistsarchive.org/", "tag": "Archiwum historycznego pesymizmu technologicznego" },
                { "name": "Royal Armouries Collections", "url": "https://royalarmouries.org/collection/", "tag": "Muzeum starożytnego uzbrojenia" },
                { "name": "Royal Constellations", "url": "https://royalconstellations.visualcinnamon.com/", "tag": "Wizualizacja przodków rodziny królewskiej" },
                { "name": "Shorpy", "url": "https://shorpy.com/", "tag": "Zdjęcia historyczne" },
                { "name": "SmartHistory", "url": "https://smarthistory.org/", "tag": "Historia sztuki / obiektów kulturowych" },
                { "name": "Smithsonian Institution Archives", "url": "https://siarchives.si.edu/", "tag": "Zdjęcia historyczne / dokumenty" },
                { "name": "The Food Timeline", "url": "https://www.foodtimeline.org/", "tag": "Oś czasu historii jedzenia" },
                { "name": "Time Portal", "url": "https://www.eggnog.ai/entertimeportal", "tag": "Gra w zgadywanie klipów historycznych" },
                { "name": "Wonderous", "url": "https://play.google.com/store/apps/details?id=com.gskinner.flutter.wonders", "tag": "Dowiedz się o starożytnych budowlach" }
            ]
        },
        {
            "id": "mitologia-i-folklor",
            "title": "🏺 Mitologia i Folklor",
            "links": [
                { "name": "ABookOfCreatures", "url": "https://abookofcreatures.com/", "tag": "Encyklopedie mitologiczne" },
                { "name": "Encyclopedia Mythica", "url": "https://pantheon.org/", "tag": "Mitologia / Folklor / Religia" },
                { "name": "GodChecker", "url": "https://www.godchecker.com/", "tag": "Historia religii / mitologii" },
                { "name": "Japanese Mythology", "url": "https://japanesemythology.wordpress.com/", "tag": "Japońska mitologia / folklor" },
                { "name": "Mythology.net", "url": "https://mythology.net/", "tag": "Mitologia / Religia" },
                { "name": "ObscUrban Legend Wiki", "url": "https://obscurban-legend.fandom.com/", "tag": "Mitologia / Miejskie legendy" }
            ]
        },
        {
            "id": "filozofia",
            "title": "🤔 Filozofia",
            "links": [
                { "name": "Art of Manliness", "url": "https://www.artofmanliness.com/", "tag": "Rozwijaj umiejętności życiowe" },
                { "name": "Brainkit", "url": "https://www.braink.it/", "tag": "Naucz się pomocnych zasad" },
                { "name": "IEoP", "url": "https://iep.utm.edu/fallacy/", "tag": "Dowiedz się o błędach logicznych" },
                { "name": "Kialo", "url": "https://www.kialo.com/", "tag": "Debaty / Dyskusje" },
                { "name": "Philosophy Bro", "url": "https://www.philosophybro.com/", "tag": "Zasoby filozoficzne / nauka" },
                { "name": "Sketchplanations", "url": "https://www.sketchplanations.com/", "tag": "Szkice wyjaśniające" },
                { "name": "Social Engineers", "url": "https://web.archive.org/web/20221208021915/https://www.socialengineers.net", "tag": "Poradniki inżynierii społecznej" },
                { "name": "⭐ Stanford Encyclopedia of Philosophy", "url": "https://plato.stanford.edu/index.html", "tag": "Encyklopedie filozofii" },
                { "name": "The Trolley Problem Game", "url": "https://newfastuff.com/the-trolley-problem-game/", "tag": "Problem wagonika" },
                { "name": "Untools", "url": "https://untools.co/", "tag": "Narzędzia do lepszego myślenia" },
                { "name": "VisualizeValue", "url": "https://archivve.visualizevalue.com/", "tag": "Wizualizacje lekcji życiowych" },
                { "name": "WikEnigma", "url": "https://wikenigma.org.uk/", "tag": "Wiki 'znanych niewiadomych'" },
                { "name": "Wireless Philosophy", "url": "https://www.wi-phi.com/", "tag": "Filmy filozoficzne" },
                { "name": "YourBias.is", "url": "https://yourbias.is/", "tag": "Dowiedz się o uprzedzeniach" }
            ]
        },
        {
            "id": "nauka-muzyki",
            "title": "🎵 Nauka Muzyki",
            "links": [
                { "name": "911tabs", "url": "https://www.911tabs.com/", "tag": "Tabulatury" },
                { "name": "A-Complete-UTAU-Tutorial-For-Beginners", "url": "https://www.quotev.com/story/9299060/A-Complete-UTAU-Tutorial-For-Beginners", "tag": "Poradnik UTAU" },
                { "name": "Arpeggiator", "url": "https://codepen.io/jakealbaugh/full/qNrZyw", "tag": "Generatory progresji akordów" },
                { "name": "AudioZ", "url": "https://audioz.download/tutorials/", "tag": "Kursy audio" },
                { "name": "🌐 Awesome Music Theory", "url": "https://github.com/vpavlenko/study-music", "tag": "Zasoby teorii muzyki" },
                { "name": "ChiffAndFipple", "url": "https://forums.chiffandfipple.com/index.php", "tag": "Forum tradycyjnej muzyki irlandzkiej" },
                { "name": "Chorder", "url": "https://www.chorder.com/guitar-chords/", "tag": "Wyszukiwarka akordów gitarowych" },
                { "name": "Circle of Fifths", "url": "https://muted.io/circle-of-fifths/", "tag": "Wizualizuj nuty, akordy i tonacje" },
                { "name": "coop3rdrumm3r", "url": "https://www.drumeo.com/coop3rdrumm3r/", "tag": "Lekcje gry na perkusji" },
                { "name": "FretFlip", "url": "https://fretflip.com/guitar-scales", "tag": "Nauka gam gitarowych / akordów" },
                { "name": "#fretflip", "url": "https://fretflip.com/", "tag": "Twórz / Drukuj gamy i akordy gitarowe" },
                { "name": "Guitar Fretboard", "url": "https://muted.io/guitar-fretboard/", "tag": "Wirtualne gryfy / Lekcje gry na gitarze" },
                { "name": "Helio", "url": "https://helio.fm/", "tag": "Narzędzia do kompozycji muzyki" },
                { "name": "HookTheory", "url": "https://www.hooktheory.com/trends", "tag": "Biblioteka progresji akordów" },
                { "name": "JamStart", "url": "https://jamstart.app/", "tag": "Wykresy akordów Spotify" },
                { "name": "Jazz Improvisor", "url": "https://www.cs.hmc.edu/~keller/jazz/improvisor/", "tag": "Improwizowany jazz" },
                { "name": "JustinGuitar", "url": "https://www.justinguitar.com/", "tag": "Lekcje gry na gitarze" },
                { "name": "Keyboard Connect", "url": "https://keyboardconnect.com/", "tag": "Aplikacja do nauki gry na keyboardzie" },
                { "name": "Learning Music", "url": "https://learningmusic.ableton.com/", "tag": "Lekcje tworzenia muzyki" },
                { "name": "LearningSynths", "url": "https://learningsynths.ableton.com/", "tag": "Syntezatory" },
                { "name": "LilyPond", "url": "https://lilypond.org/", "tag": "Program do grawerowania nut" },
                { "name": "Midiano", "url": "https://midiano.com/", "tag": "Ćwiczenia / nauka gry na pianinie" },
                { "name": "MIMO", "url": "https://mimo-international.com/MIMO/", "tag": "Baza danych instrumentów muzycznych" },
                { "name": "MusicKit", "url": "https://musickit.jull.dev/", "tag": "Metronom, tuner i generatory tonów" },
                { "name": "MusicStaff", "url": "https://musicstaff.com/", "tag": "Wyszukiwarka nauczycieli muzyki" },
                { "name": "⭐ Muted", "url": "https://muted.io/", "tag": "Teoria muzyki" },
                { "name": "⭐ Open Music Theory", "url": "https://viva.pressbooks.pub/openmusictheory/", "tag": "Teoria muzyki" },
                { "name": "PerfectPitch", "url": "https://artistaiden.com/perfectpitch", "tag": "Ćwiczenie rozpoznawania wysokości dźwięku" },
                { "name": "Piano Scribe", "url": "https://laqieer.github.io/piano-scribe/", "tag": "Transkrypcja pianina" },
                { "name": "ScoreCloud", "url": "https://scorecloud.com/", "tag": "Wykrywanie akordów / Transkrypcja" },
                { "name": "Sight Singing Factory", "url": "https://www.sightreadingfactory.com/", "tag": "Ćwiczenie śpiewu a vista" },
                { "name": "Tuner Ninja", "url": "https://tuner.ninja/", "tag": "Stroik do instrumentów" },
                { "name": "Ultimate Guitar", "url": "https://www.ultimate-guitar.com/", "tag": "Tabulatury gitarowe" },
                { "name": "VGM Sound Sources", "url": "https://docs.google.com/spreadsheets/d/1JJBlHHDc65fhZmKUGLrDTLCm6rfUU83-kbuD8Y0zU0o/", "tag": "Źródła dźwięku VGM" }
            ]
        },
        {
            "id": "sztuka-i-edycja",
            "title": "🖌️ Sztuka i Edycja",
            "links": [
                { "name": "Agora", "url": "https://agora.community/", "tag": "Społeczność ucząca animacji / Poradniki" },
                { "name": "AMV101", "url": "https://www.amv101.com/", "tag": "Poradniki tworzenia AMV" },
                { "name": "AnimeOutline", "url": "https://www.animeoutline.com/", "tag": "Poradniki rysowania anime / mangi" },
                { "name": "Anime Study General", "url": "https://discord.gg/3bwdfRk", "tag": "Społeczność produkcji anime" },
                { "name": "🌐 AwesomeAnimeResearch", "url": "https://github.com/SerialLain3170/AwesomeAnimeResearch", "tag": "Uczenie maszynowe w anime" },
                { "name": "Artist Reference", "url": "https://artist-reference.com", "tag": "Referencje zdjęć dla artystów" },
                { "name": "⭐ Art Study Guide", "url": "https://drive.google.com/file/d/1cK9q7oeFRE58MVaSgUql662iGqCXC8Ah/", "tag": "Poradniki i wskazówki do nauki sztuki" },
                { "name": "ArtWithFlo", "url": "https://artwithflo.com/", "tag": "Poradniki Procreate" },
                { "name": "cg_tuts", "url": "https://t.me/cg_tuts", "tag": "Poradniki CG" },
                { "name": "Character Design References", "url": "https://characterdesignreferences.com/visual-library", "tag": "Biblioteka wizualna do projektowania postaci" },
                { "name": "🌐 Creator Resources", "url": "https://www.newgrounds.com/wiki/creator-resources/", "tag": "Indeks zasobów artystycznych i animacyjnych" },
                { "name": "Curriculum for the Solo Artists", "url": "https://alexhuneycutt.gumroad.com/l/free_curriculum", "tag": "Program nauczania dla samouków" },
                { "name": "Design Tuts", "url": "https://t.me/designfreetuts", "tag": "Poradniki projektowania" },
                { "name": "DevinKorwin Color Guide", "url": "https://x.com/devinkorwin/status/1278049901709012995", "tag": "Przewodnik po kolorach w malarstwie" },
                { "name": "Dimensions", "url": "https://www.dimensions.com/", "tag": "Referencje wymiarów obiektów" },
                { "name": "DoArtDaily", "url": "https://dad.gallery", "tag": "Codzienne wyzwania artystyczne" },
                { "name": "DomDesigns", "url": "https://www.youtube.com/c/DomDesigns/", "tag": "Poradniki Illustratora" },
                { "name": "⭐ Drawabox", "url": "https://drawabox.com/", "tag": "Lekcje rysunku" },
                { "name": "DrawingNow", "url": "https://www.drawingnow.com/", "tag": "Nauka rysowania" },
                { "name": "Drawingbooks.org", "url": "https://www.drawingbooks.org/", "tag": "Stare książki o rysunku" },
                { "name": "Draw Mix Paint", "url": "https://www.drawmixpaint.com/", "tag": "Nauka malarstwa olejnego" },
                { "name": "FloobyNooby", "url": "http://www.floobynooby.com/comp1.html", "tag": "Poradniki do storyboardów" },
                { "name": "GraphicsCodex", "url": "https://graphicscodex.com/", "tag": "Poradniki grafiki komputerowej 3D" },
                { "name": "Line of Action", "url": "https://line-of-action.com/", "tag": "Narzędzia do szkicowania postaci / Lekcje" },
                { "name": "MangaMaterials", "url": "https://www.youtube.com/channel/UCnx8zKsQ2QzMqLA/", "tag": "Poradniki wideo o mandze" },
                { "name": "McLelun", "url": "http://www.mclelun.com/p/tutorial.html", "tag": "Poradnik tła w stylu anime" },
                { "name": "MetPublications", "url": "https://www.metmuseum.org/met-publications/all", "tag": "Książki do nauki sztuki" },
                { "name": "online-courses", "url": "https://online-courses.club/", "tag": "Kursy artystyczne / projektowe" },
                { "name": "Paintable", "url": "https://paintable.cc/", "tag": "Poradniki sztuki cyfrowej" },
                { "name": "Painting Demos", "url": "https://paintingdemos.com/", "tag": "Pokazy malarskie" },
                { "name": "⭐ PaintingTube", "url": "https://painting.tube", "tag": "Poradniki wideo o sztuce" },
                { "name": "Pedro's Pixel Art Tutorials", "url": "https://saint11.art/blog/pixel-art-tutorials/", "tag": "Poradniki pixel artu" },
                { "name": "PhotoshopTraining", "url": "https://www.youtube.com/@PhotoshopTrainingChannel", "tag": "Poradniki YouTube o Photoshopie" },
                { "name": "PhotoshopTutorials.ws", "url": "https://www.photoshoptutorials.ws/", "tag": "Poradniki Photoshopa" },
                { "name": "⭐ Proko", "url": "https://www.youtube.com/user/ProkoTV/videos", "tag": "Lekcje rysowania postaci" },
                { "name": "Reference Angle", "url": "http://referenceangle.com/", "tag": "Wyszukiwarka referencji zdjęć ludzi" },
                { "name": "Settei Dreams", "url": "https://setteidreams.net/", "tag": "Materiały produkcyjne anime" },
                { "name": "The Bézier Game", "url": "https://bezier.method.ac/", "tag": "Ćwiczenie narzędzia pióro" },
                { "name": "Thomas Romain Perspective", "url": "https://ibb.co/album/chGtPJ?sort=name_asc", "tag": "Przewodnik po perspektywie" },
                { "name": "TutsPlus", "url": "https://tutsplus.com/", "tag": "Kursy kreatywne" },
                { "name": "Ubu", "url": "https://ubuweb.com/", "tag": "Artefakty awangardowe" },
                { "name": "x6ud", "url": "https://x6ud.github.io/#/", "tag": "Wyszukiwarka referencji zdjęć zwierząt" }
            ]
        },
        {
            "id": "geografia-i-socjologia",
            "title": "🗺️ Geografia i Socjologia",
            "links": [
                { "name": "AntipodesMap", "url": "https://www.antipodesmap.com/", "tag": "Znajdź antypody" },
                { "name": "🌐 Awesome Datasets", "url": "https://github.com/awesomedata/awesome-public-datasets", "tag": "Publiczne zbiory danych" },
                { "name": "City Data", "url": "https://www.city-data.com/", "tag": "Dane o miastach w USA" },
                { "name": "Climate Data", "url": "https://climate-data.org/", "tag": "Dane o zmianach klimatu" },
                { "name": "🌐 Country Infographics", "url": "https://rentry.org/o4gq6cq5", "tag": "Infografiki o krajach" },
                { "name": "Data Commons", "url": "https://datacommons.org/", "tag": "Wizualizacje danych" },
                { "name": "DataUNODC", "url": "https://dataunodc.un.org/", "tag": "Statystyki przestępczości" },
                { "name": "Dollar Street", "url": "https://www.gapminder.org/dollar-street", "tag": "Porównaj domy według kraju / dochodu" },
                { "name": "En-ROADS", "url": "https://en-roads.climateinteractive.org/scenario.html", "tag": "Symulator rozwiązań klimatycznych" },
                { "name": "EverySecond", "url": "https://everysecond.io/", "tag": "Wizualizuj dane na sekundę" },
                { "name": "Expatistan", "url": "https://www.expatistan.com/", "tag": "Kalkulator kosztów życia" },
                { "name": "ExtremeWeatherWatch", "url": "https://www.extremeweatherwatch.com/", "tag": "Dane o ekstremalnej pogodzie" },
                { "name": "Flag Guesser", "url": "https://flagguesser.com/", "tag": "Quizy o flagach" },
                { "name": "FlagLog", "url": "https://www.flaglog.com/", "tag": "Bazy danych flag" },
                { "name": "Flag Stories", "url": "https://flagstories.co/", "tag": "Analiza projektów flag" },
                { "name": "Global Consciousness Project", "url": "https://gcpdot.com/", "tag": "Dane o globalnej świadomości w czasie rzeczywistym" },
                { "name": "Global Volcanism Program", "url": "https://volcano.si.edu/", "tag": "Baza informacji o wulkanach" },
                { "name": "Gun Violence Archive", "url": "https://www.gunviolencearchive.org/", "tag": "Statystyki przemocy z użyciem broni" },
                { "name": "Hate on Display", "url": "https://www.adl.org/hate-symbols", "tag": "Baza danych symboli nienawiści" },
                { "name": "iCivics", "url": "https://www.icivics.org/games", "tag": "Gry do nauki prawa USA" },
                { "name": "If It Were My Home", "url": "https://www.ifitweremyhome.com/", "tag": "Porównania danych o krajach" },
                { "name": "Incarceration in Real Numbers", "url": "https://mkorostoff.github.io/incarceration-in-real-numbers/", "tag": "Wizualizacja danych o więziennictwie" },
                { "name": "LizardPoint", "url": "https://lizardpoint.com/", "tag": "Zgadywanki geograficzne / Quizy" },
                { "name": "Maps.com", "url": "https://www.maps.com/", "tag": "Ciekawe / edukacyjne mapy" },
                { "name": "NationsEncyclopedia", "url": "https://www.nationsencyclopedia.com/", "tag": "Dane o lokalizacji / populacji" },
                { "name": "Netblocks", "url": "https://netblocks.org/cost/", "tag": "Wpływ wyłączeń internetu na gospodarkę" },
                { "name": "OEC", "url": "https://oec.world/en", "tag": "Dane o handlu światowym" },
                { "name": "⭐ Our World in Data", "url": "https://ourworldindata.org/", "tag": "Baza danych o problemach świata" },
                { "name": "Rulers.org", "url": "https://rulers.org/", "tag": "Baza danych głów państw i rządów" },
                { "name": "⭐ Soar", "url": "https://soar.earth/", "tag": "Cyfrowy atlas" },
                { "name": "Statista", "url": "https://www.statista.com/", "tag": "Statystyki rynkowe" },
                { "name": "Symbols", "url": "https://www.symbols.com/", "tag": "Baza danych symboli" },
                { "name": "⭐ The Atlas of Economic Complexity", "url": "https://atlas.cid.harvard.edu/", "tag": "Dane o globalnym wzroście gospodarczym" },
                { "name": "The True Size", "url": "https://thetruesize.com/", "tag": "Porównaj rozmiar krajów" },
                { "name": "Unequal Scenes", "url": "https://unequalscenes.com/", "tag": "Sceny nierówności na świecie" },
                { "name": "World Births and Deaths", "url": "https://worldbirthsanddeaths.com/", "tag": "Wizualizacja wskaźników urodzeń / zgonów" },
                { "name": "WorldLicensePlates", "url": "http://www.worldlicenseplates.com/", "tag": "Indeks tablic rejestracyjnych świata" },
                { "name": "⭐ Worldometer", "url": "https://www.worldometers.info/", "tag": "Dane i statystyki światowe" },
                { "name": "WorldPoverty", "url": "https://worldpoverty.io/", "tag": "Dane o ubóstwie na świecie" }
            ]
        },
        {
            "id": "wirtualne-wycieczki",
            "title": "🏛️ Wirtualne Wycieczki",
            "links": [
                { "name": "360Cities", "url": "https://www.360cities.net/", "tag": "Obrazy / Wideo 360" },
                { "name": "Basilica Viewer", "url": "https://virtual.basilicasanpietro.va/en/basilica-viewer/", "tag": "Wycieczka po Bazylice św. Piotra" },
                { "name": "BelowTheSurface", "url": "https://belowthesurface.amsterdam/en", "tag": "Baza obiektów archeologicznych z Amsterdamu" },
                { "name": "⭐ CityHop", "url": "https://www.cityhop.cafe/", "tag": "Symulatory podróży" },
                { "name": "Digital Giza", "url": "https://mused.com/giza/", "tag": "Wirtualne wycieczki po Wielkiej Piramidzie" },
                { "name": "Gez.la", "url": "https://gez.la/", "tag": "Mapa wirtualnych wycieczek" },
                { "name": "Matterport", "url": "https://matterport.com/discover", "tag": "Odkrywaj prawdziwe miejsca cyfrowo" },
                { "name": "NaturalHistory", "url": "https://naturalhistory.si.edu/visit/virtual-tour", "tag": "Wirtualna wycieczka po Muzeum Historii Naturalnej" },
                { "name": "Persepolis Reimagined", "url": "https://persepolis.getty.edu/", "tag": "Odkryj rekonstrukcję Persepolis" },
                { "name": "Smithsonian 3D", "url": "https://3d.si.edu/", "tag": "Muzeum cyfryzacji 3D Smithsonian" },
                { "name": "Spitfire Panorama", "url": "https://www.haraldjoergens.com/panoramas/spitfire-td314/files/", "tag": "Interaktywna panorama kokpitu Spitfire" },
                { "name": "The Bayeux Tapestry", "url": "https://www.bayeuxmuseum.com/en/the-bayeux-tapestry/discover-the-bayeux-tapestry/explore-online/", "tag": "Cyfryzacja 3D Tapiserii z Bayeux" },
                { "name": "🌐 Virtual Museum Resources", "url": "https://mcn.edu/a-guide-to-virtual-museum-resources/", "tag": "Muzea online" },
                { "name": "Virtual Vist Tours", "url": "https://www.virtualvisittours.com/", "tag": "Wirtualne wycieczki po Irlandii" },
                { "name": "WW2 in 100 Objects", "url": "https://www.tweedewereldoorlog.nl/100voorwerpen/en/virtual-tour/", "tag": "Wirtualna wycieczka po muzeum II WŚ" },
                { "name": "Wiki Spaces", "url": "https://wiki-spaces.org/", "tag": "Wirtualne wycieczki" }
            ]
        }
    ]
};