const pageData = {
    sections: [
        {
            id: 'pl-sites',
            title: '🇵🇱 Polskie Strony',
            subsections: [
                {
                    title: 'Wymagane Logowanie',
                    links: [
                        { name: 'filman.cc', url: 'https://filman.cc/' },
                        { name: 'vizjer.eu', url: 'https://vizjer.eu/' },
                        { name: 'zalukaj-tv.pl', url: 'https://zalukaj-tv.pl/' }
                    ]
                },
                {
                    title: 'Bez Logowania',
                    links: [
                        { name: 'cda-hd.cc', url: 'https://cda-hd.cc/' },
                        { name: 'cda.pl', url: 'https://www.cda.pl/' },
                        { name: 'ekino-tv.pl', url: 'https://ekino-tv.pl/' },
                        { name: 'ekino.sx', url: 'https://ekino.sx/' },
                        { name: 'ekino.ws', url: 'https://ekino.ws/' },
                        { name: 'filser.cc', url: 'https://filser.cc/' },
                        { name: 'iiTV', url: 'https://iitv.info/' },
                        { name: 'obejrzyj.to', url: 'https://www.obejrzyj.to/' },
                        { name: 'vider.info', url: 'https://vider.info/' },
                        { name: 'virpe.cc', url: 'https://virpe.cc/' },
                        { name: 'zaluknij.cc', url: 'https://zaluknij.cc/' },
                        { name: 'zerion.cc', url: 'https://zerion.cc/' }
                    ]
                }
            ]
        },
        {
            id: 'intl-streaming',
            title: '🎬 Międzynarodowe Strony Streamingowe (Online)',
            subsections: [
                {
                    title: 'Zewnętrzne API (Movie-Web Frontends)',
                    links: [
                        { name: '1Flex (Mirror)', url: 'https://www.1flex.ru/' },
                        { name: '1Shows', url: 'https://www.1shows.ru/', tag: 'Filmy/Seriale/Anime' },
                        { name: '345movie (Mirror)', url: 'https://345movie.net/' },
                        { name: '456movie (Mirror)', url: 'https://456movie.net/' },
                        { name: 'BFLIX', url: 'https://bflix.sh/', tag: 'Filmy/Seriale' },
                        { name: 'BitCine (Mirror Cineby)', url: 'https://www.bitcine.app/' },
                        { name: 'CineMora (Mirror)', url: 'https://cinemora.ru/' },
                        { name: '⭐ Cineby', url: 'https://www.cineby.app/', tag: 'Filmy/Seriale/Anime/4K' },
                        { name: 'Cinegram', url: 'https://cinegram.net/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'CorsFlix', url: 'https://watch.corsflix.net' },
                        { name: 'CorsFlix DPN', url: 'https://watch.corsflix.dpdns.org/' },
                        { name: 'CorsFlix NET', url: 'https://corsflix.net' },
                        { name: 'Downloads-Anymovies', url: 'https://www.downloads-anymovies.co/', tag: 'Filmy' },
                        { name: 'FilmCave', url: 'https://filmcave.net/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'FlickyStream', url: 'https://flickystream.net', tag: 'Filmy/Seriale/Anime' },
                        { name: '⭐ Flixer', url: 'https://flixer.su/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'Fmovies+ (Premium)', url: 'https://www.fmovies.gd/' },
                        { name: 'Hexa (Mirror)', url: 'https://hexa.watch/' },
                        { name: 'MovieHD', url: 'https://moviehd.us', tag: 'Filmy' },
                        { name: '⭐ P-Stream', url: 'https://pstream.mov/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'PrimeWire', url: 'https://www.primewire.mov/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'PrimeWire TF (Mirror)', url: 'https://www.primewire.tf/' },
                        { name: 'ProjectFreeTV', url: 'https://projectfreetv.sx/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'RgShows (Mirror)', url: 'https://www.rgshows.me/' },
                        { name: 'Rive', url: 'https://rivestream.org/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'RiveStream App', url: 'https://www.rivestream.app/' },
                        { name: 'RiveStream NET', url: 'https://rivestream.net/' },
                        { name: 'Smashystream', url: 'https://smashystream.xyz/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'Smashystream Flix', url: 'https://flix.smashystream.xyz/' },
                        { name: 'SoaPy', url: 'https://soapy.to/', tag: 'Filmy/Seriale/Anime' },
                        { name: '⭐ SpenFlix', url: 'https://watch.spencerdevs.xyz/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'SpenFlix RU (Mirror)', url: 'https://spenflix.ru/' },
                        { name: 'StreamDB', url: 'https://streamdb.online/', tag: 'Filmy/Seriale' },
                        { name: 'StreamM4u', url: 'https://streamm4u.com.co/', tag: 'Filmy/Seriale/Anime' },
                        { name: '⭐ VeloraTV', url: 'https://veloratv.ru/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'Vidora (Mirror)', url: 'https://watch.vidora.su/' },
                        { name: '⭐ XPrime', url: 'https://xprime.tv/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'XPrime Today (Mirror)', url: 'https://xprime.today/' }
                    ]
                },
                {
                    title: 'API Frontends',
                    links: [
                        { name: '1PrimeShows', url: 'https://1primeshow.online/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'AlienFlix', url: 'https://alienflix.net/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'Altair', url: 'https://altair.mollusk.top/', tag: 'Filmy/Seriale' },
                        { name: 'Ask4Movies', url: 'https://ask4movie.app/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'Autoembed', url: 'https://watch.autoembed.cc/', tag: 'Filmy/Seriale/Anime/Drama' },
                        { name: '⭐ BEECH', url: 'https://beech.watch/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'CineBolt', url: 'https://cinebolt.net/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'CineGo', url: 'https://cinego.co/', tag: 'Filmy/Seriale' },
                        { name: 'Cinema Deck', url: 'https://cinemadeck.com/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'Cinema Deck ST (Mirror)', url: 'https://cinemadeck.st/' },
                        { name: '⭐ CinemaOS', url: 'https://cinemaos.live/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'CinemaOS Me (Mirror)', url: 'https://cinemaos.me/' },
                        { name: 'CinemaOS Tech (Mirror)', url: 'https://cinemaos.tech/' },
                        { name: 'Cinepeace', url: 'https://cinepeace.in/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'Cinezo', url: 'https://www.cinezo.net/', tag: 'Filmy/Seriale/Anime' },
                        { name: '⭐ Filmex', url: 'https://filmex.to/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'Flicker Addon (Mirror)', url: 'https://flickeraddon.pages.dev/' },
                        { name: 'Flicker Mini', url: 'https://flickermini.pages.dev/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'Flicker Mini Proxy (Mirror)', url: 'https://flickerminiproxy.pages.dev/' },
                        { name: 'Fmovies4u (Mirror)', url: 'https://fmovies4u.com/' },
                        { name: 'HexaWatch (Mirror)', url: 'https://hexawatch.cc/' },
                        { name: 'Hopfly', url: 'https://watch.hopfly.site/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'HydraHD', url: 'https://hydrahd.io/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'KaitoVault', url: 'https://www.kaitovault.com/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'M-Zone', url: 'https://www.m-zone.org/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'Mapple.tv', url: 'https://mapple.tv/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'Maxflix', url: 'https://maxflix.top/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'Mocine (Mirror)', url: 'https://mocine.cam/' },
                        { name: 'MoviePluto', url: 'https://moviepluto.fun/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'Netplay', url: 'https://netplayz.live/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'Nova (Mirror)', url: 'https://novastream.top/' },
                        { name: 'Novafork', url: 'https://novafork.cc/', tag: 'Filmy/Seriale' },
                        { name: 'Nunflix', url: 'https://nunflix.org/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'Nunflix Pages (Mirror)', url: 'https://nunflix-ey9.pages.dev/' },
                        { name: 'PopcornMovies', url: 'https://popcornmovies.org/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'Primeshows', url: 'https://www.primeshows.live/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'Purplix (Mirror)', url: 'https://purplix.transdev.pw/' },
                        { name: 'Purplix Neoxa', url: 'https://neoxa.transdev.pw/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'Purplix Starnode (Mirror)', url: 'https://tv.starnode.host/' },
                        { name: 'Redflix', url: 'https://redflix.co/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'Redflix Club (Mirror)', url: 'https://redflix.club/' },
                        { name: 'Salix (Mirror)', url: 'https://salix.pages.dev/' },
                        { name: 'TMovie', url: 'https://tmovie.tv/', tag: 'Filmy/Seriale/Anime' },
                        { name: '⭐ Vidbox', url: 'https://vidbox.to/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'Vidjoy', url: 'https://vidjoy.pro/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'ViewVault', url: 'https://viewvault.org/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'VLOP', url: 'https://www.vlop.fun/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'Willow', url: 'https://willow.arlen.icu/', tag: 'Filmy/Seriale/Anime/4K' },
                        { name: 'Wooflix', url: 'https://www.wooflixtv.co/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'Yampi', url: 'https://yampi.live/', tag: 'Filmy/Seriale/Anime' }
                    ]
                },
                {
                    title: 'Single Server Sites',
                    links: [
                        { name: '1Movies (Mirror)', url: 'https://1movies.bz/' },
                        { name: '24Drama', url: 'https://24drama.to/', tag: 'Filmy/Seriale/Anime/720p' },
                        { name: 'AZMovies', url: 'https://azmovies.ag/', tag: 'Filmy' },
                        { name: '⭐ EE3', url: 'https://ee3.me/', tag: 'Filmy/Zaproszenia' },
                        { name: 'FlixHQ (Mirror)', url: 'https://flixhq.to/' },
                        { name: 'FshareTV', url: 'https://fsharetv.co/', tag: 'Filmy' },
                        { name: 'Gir Society (Plex Required)', url: 'https://discord.gg/WHxeZ3aTtb' },
                        { name: 'Goojara (Mirror)', url: 'https://ww1.goojara.to/' },
                        { name: 'HollyMovieHD', url: 'https://hollymoviehd.cc/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'Levidia', url: 'https://www.levidia.ch/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'LookMovie', url: 'https://lookmovie2.to/', tag: 'Filmy/Seriale/480p' },
                        { name: 'Movies4F', url: 'https://movies4f.com/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'Movies7', url: 'https://movies7.im/', tag: 'Filmy/Seriale' },
                        { name: 'Mp4Hydra', url: 'https://mp4hydra.org/', tag: 'Filmy' },
                        { name: 'Mp4Hydra Top (Mirror)', url: 'https://mp4hydra.top/' },
                        { name: '⭐ NEPU', url: 'https://nepu.to/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'NMovies (Mirror)', url: 'https://nmovies.cc/' },
                        { name: 'NovaMovie (Mirror)', url: 'https://novamovie.net/' },
                        { name: 'OnionPlay', url: 'https://onionplay.mx/', tag: 'Filmy/Seriale' },
                        { name: 'Player4U', url: 'https://rentry.co/FMHYBase64#player4u', tag: 'Filmy/Seriale/Anime' },
                        { name: 'PlayIMDb', url: 'https://www.playimdb.com/', tag: 'Wyszukiwanie IMDb' },
                        { name: 'PoorFlix', url: 'https://poorflix.net/', tag: 'Filmy/Seriale/Anime' },
                        { name: '⭐ Qstream', url: 'https://qstream.pages.dev/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'RidoMovies', url: 'https://ridomovies.tv/', tag: 'Filmy/Seriale' },
                        { name: 'RIPS (Mirror)', url: 'https://rips.cc/' },
                        { name: 'SFlix', url: 'https://sflix2.to/', tag: 'Filmy/Seriale' },
                        { name: 'SFlix (Mirror)', url: 'https://sflix.to/' },
                        { name: 'SFlixto (Mirror)', url: 'https://sflixto.tube/' },
                        { name: 'ShowBox', url: 'https://www.showbox.media/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'Soaker', url: 'https://soaker.tv/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'Soaper (Mirror)', url: 'https://soaper.live/' },
                        { name: 'Supernova (Mirror)', url: 'https://supernova.to/' },
                        { name: 'UniqueStream', url: 'https://uniquestream.net/', tag: 'Filmy/Seriale/Anime/720p' },
                        { name: 'Vidsrc.cx', url: 'https://vidsrc.cx/', tag: 'Filmy/Seriale' },
                        { name: 'YesHD (Mirror)', url: 'https://yeshd.net/' },
                        { name: 'YesMovie', url: 'https://yesmovies.ag/', tag: 'Filmy/Seriale/720p' },
                        { name: '⭐ yFlix', url: 'https://yflix.to/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'Zoechip', url: 'https://zoechip.org/', tag: 'Filmy/Seriale' }
                    ]
                },
                {
                    title: 'Darmowe z Reklamami (Legalne)',
                    links: [
                        { name: '7+', url: 'https://7plus.com.au/', tag: 'Tylko US/AU' },
                        { name: 'ARTE', url: 'https://www.arte.tv/en', tag: 'Filmy/Seriale' },
                        { name: 'BBC iPlayer', url: 'https://www.bbc.co.uk/iplayer', tag: 'Wymagane UK VPN' },
                        { name: 'DarkRoom', url: 'https://www.darkroom.film/', tag: 'Tylko US' },
                        { name: 'Fandango at Home', url: 'https://athome.fandango.com/content/browse/free', tag: 'Tylko US' },
                        { name: 'Fawesome', url: 'https://fawesome.tv/', tag: 'Filmy/Seriale' },
                        { name: 'Filmzie', url: 'https://filmzie.com/', tag: 'Filmy/Seriale' },
                        { name: 'FlixHouse', url: 'https://flixhouse.com/', tag: 'Filmy niezależne' },
                        { name: 'Found TV', url: 'https://watch.foundtv.com/', tag: 'Wymagana rejestracja' },
                        { name: 'FreeGreatMovies', url: 'https://www.freegreatmovies.com/', tag: 'Kolekcja YT' },
                        { name: 'Freevee', url: 'https://www.amazon.com/gp/video/storefront/?ie=UTF8&contentId=freetv', tag: 'Tylko US' },
                        { name: 'hoopla', url: 'https://www.hoopladigital.com/', tag: 'Wymagana karta biblioteczna' },
                        { name: 'Kanopy', url: 'https://kanopy.com/', tag: 'Wymagana karta biblioteczna' },
                        { name: 'Mometu', url: 'https://watch.mometu.com/', tag: 'Tylko US' },
                        { name: 'MoviesFoundOnline', url: 'https://moviesfoundonline.com/', tag: 'Kolekcja YT' },
                        { name: 'Official YT Movies', url: 'https://www.youtube.com/feed/storefront?bp=ogUCKAY%3D', tag: 'Tylko US' },
                        { name: 'OpenCulture', url: 'https://www.openculture.com/freemoviesonline', tag: 'Kolekcja YT' },
                        { name: 'Playary', url: 'https://www.playary.com/', tag: 'Filmy/Seriale' },
                        { name: '⭐ Plex', url: 'https://watch.plex.tv/', tag: 'Filmy/Seriale/720p' },
                        { name: '⭐ Pluto', url: 'https://pluto.tv/', tag: 'Filmy/Seriale/720p' },
                        { name: 'Roku Channel', url: 'https://therokuchannel.roku.com/', tag: 'Tylko US' },
                        { name: 'Shout! TV', url: 'https://shout-tv.com/', tag: 'Tylko US/CA' },
                        { name: 'Sling (Limited Free)', url: 'https://watch.sling.com/', tag: 'Tylko US' },
                        { name: '⭐ Tubi', url: 'https://tubitv.com', tag: 'Filmy/Seriale/720p' },
                        { name: 'Video Dictionary', url: 'https://videodictionary.kwebpia.net/?m=Full_Movies', tag: 'Kolekcja YT' },
                        { name: 'Voleflix', url: 'https://vole.wtf/voleflix/', tag: 'Kolekcja YT' },
                        { name: 'Vudu Free', url: 'https://www.vudu.com/content/movies/uxpage/View-All-Free-Movies-TV/207', tag: 'Tylko US' }
                    ]
                },
                {
                    title: 'General Video Platforms',
                    links: [
                        { name: 'BiliBili TV (Mirror)', url: 'https://www.bilibili.tv/' },
                        { name: '⭐ BiliBili', url: 'https://www.bilibili.com/', tag: 'Platforma wideo' },
                        { name: 'BitChute', url: 'https://www.bitchute.com/', tag: 'Platforma wideo' },
                        { name: 'BitView', url: 'https://www.bitview.net/', tag: 'Platforma wideo' },
                        { name: '⭐ Dailymotion', url: 'https://www.dailymotion.com/', tag: 'Platforma wideo' },
                        { name: 'Naver', url: 'https://tv.naver.com/', tag: 'Platforma wideo' },
                        { name: '⭐ Niconico', url: 'https://www.nicovideo.jp/', tag: 'Platforma wideo' },
                        { name: 'odysee', url: 'https://odysee.com/', tag: 'Platforma wideo' },
                        { name: '⭐ OK.ru', url: 'https://ok.ru/video', tag: 'Platforma wideo' },
                        { name: 'PeerTube', url: 'https://joinpeertube.org/', tag: 'Zdecentralizowane wideo' },
                        { name: 'Playeur', url: 'https://playeur.com/', tag: 'Platforma wideo' },
                        { name: 'Rumble', url: 'https://rumble.com/', tag: 'Platforma wideo' },
                        { name: 'rutube', url: 'https://rutube.ru', tag: 'Platforma wideo' },
                        { name: 'Tape', url: 'https://tape.xyz/', tag: 'Platforma wideo' },
                        { name: 'ultimedia', url: 'https://www.ultimedia.com/', tag: 'Platforma wideo' },
                        { name: 'Videa', url: 'https://videa.hu/', tag: 'Platforma wideo' },
                        { name: 'Vimeo', url: 'https://vimeo.com/watch', tag: 'Platforma wideo' },
                        { name: '⭐ VK', url: 'https://vkvideo.ru/', tag: 'Platforma wideo' },
                        { name: '⭐ YouTube', url: 'https://www.youtube.com/', tag: 'Platforma wideo' }
                    ]
                }
            ]
        },
        {
            id: 'specialty-streaming',
            title: '🎭 Specjalistyczne Filmy i Seriale',
            subsections: [
                {
                    title: 'Rare / Obscure Films',
                    links: [
                        { name: '"Slime Tutorials"', url: 'https://youtube.com/playlist?list=PLsIt5G4GJ27lxWP9Qi5N70zRSkJAT0ntc', tag: 'Playlisty Broadway' },
                        { name: '0xDB', url: 'https://0xdb.org/', tag: 'Rzadkie Filmy' },
                        { name: 'Argo', url: 'https://web.watchargo.com/', tag: 'Filmy Krótkometrażowe' },
                        { name: 'Audpop', url: 'https://audpop.com/', tag: 'Filmy Krótkometrażowe' },
                        { name: 'Audiovault', url: 'https://audiovault.net/', tag: 'Audiodeskrypcja' },
                        { name: 'Bandersnatch Interactive Player', url: 'https://mehotkhan.github.io/BandersnatchInteractive/' },
                        { name: 'Clownsec', url: 'https://rentry.co/FMHYBase64#clownsec', tag: 'Filmy 3D na 3DS' },
                        { name: 'Daily Commercials (Mirror)', url: 'https://dailycommercials.com/' },
                        { name: 'Domain Expansion', url: 'https://rentry.co/FMHYBase64#domain-expansion', tag: 'Treści z reakcjami' },
                        { name: 'GlobalShakespeares', url: 'https://globalshakespeares.mit.edu/', tag: 'Szekspir' },
                        { name: '⭐ GizmoPlex', url: 'https://www.gizmoplex.com/mst3k', tag: 'MST3K' },
                        { name: 'HomeMovies101', url: 'https://www.homemovies100.it/en/', tag: 'Filmy domowe' },
                        { name: '⭐ JP-Films', url: 'https://jp-films.com/', tag: 'Japońskie Filmy/Seriale' },
                        { name: 'Le Cinéma Club', url: 'https://www.lecinemaclub.com/', tag: 'Filmy niezależne' },
                        { name: 'Le Cinéma Club Archive', url: 'https://www.lecinemaclub.com/archives/index/' },
                        { name: 'LightCone', url: 'https://lightcone.org/en', tag: 'Krótkie/Eksperymentalne' },
                        { name: 'LIMA', url: 'https://www.li-ma.nl/', tag: 'Krótkie/Eksperymentalne' },
                        { name: 'Lumo TV', url: 'https://lumotv.co.uk/', tag: 'Rozrywka dla niesłyszących' },
                        { name: 'Prelinger Archives', url: 'https://www.panix.com/~footage/', tag: 'Filmy efemeryczne' },
                        { name: 'Prelinger Archives (Mirror)', url: 'https://archive.org/details/prelinger' },
                        { name: 'r/MusicalBootlegs', url: 'https://www.reddit.com/r/MusicalBootlegs', tag: 'Przedstawienia z Broadwayu' },
                        { name: '⭐ RareFilmm', url: 'https://rarefilmm.com/', tag: 'Rzadkie Filmy' },
                        { name: 'RiffTrax Pluto (Mirror)', url: 'https://pluto.tv/live-tv/rifftrax' },
                        { name: '⭐ RiffTrax Twitch', url: 'https://www.twitch.tv/rifftrax', tag: 'Transmisje na żywo' },
                        { name: 'Rohesia Hamilton Metcalfe', url: 'https://www.panix.com/~hamiltro/links/', tag: 'Eksperymentalne' },
                        { name: 'Short of the Week', url: 'https://www.shortoftheweek.com/', tag: 'Filmy Krótkometrażowe' },
                        { name: 'Shortly', url: 'https://watch.shortly.film/', tag: 'Filmy Krótkometrażowe' },
                        { name: 'Shortverse', url: 'https://www.shortverse.com/explore', tag: 'Filmy Krótkometrażowe' },
                        { name: 'SidePlusLeaks', url: 'https://sideplusleaks.online/', tag: 'Treści Sidemen' },
                        { name: '⭐ Tokuzilla', url: 'https://tokuzilla.net/', tag: 'Tokusatsu' },
                        { name: 'TVARK', url: 'https://tvark.org/', tag: 'Reklamy/Promocje TV' },
                        { name: '⭐ Ubu', url: 'https://ubu.com/film/', tag: 'Krótkie/Awangardowe' },
                        { name: 'Unus Annus Archive', url: 'https://archive.org/details/unus-annus' },
                        { name: 'Viddsee', url: 'https://viddsee.com/', tag: 'Filmy Krótkometrażowe' },
                        { name: 'Yuzu4K Japanese Commercials', url: 'https://archive.org/details/jpcm_yuzu4k' },
                        { name: 'Zero1Cine', url: 'https://zero1cine.com/', tag: 'Filmy generowane przez AI' }
                    ]
                },
                {
                    title: 'TV Series Specific Streaming',
                    links: [
                        { name: 'Adult Swim', url: 'https://www.adultswim.com/videos/', tag: 'Pełne odcinki' },
                        { name: 'AZ Series', url: 'https://azseries.org/', tag: 'Seriale' },
                        { name: '⭐ Best Series', url: 'https://bstsrs.in/', tag: 'Seriale/Anime' },
                        { name: 'BrokenSilenze', url: 'https://www.brokensilenze.net/', tag: 'Reality TV' },
                        { name: '⭐ CouchTuner', url: 'https://www.couchtuner.show/', tag: 'Seriale/Anime/720p' },
                        { name: 'HDclump', url: 'https://hdclump.com/', tag: 'Dokumenty/Gotowanie' },
                        { name: 'HISTORY', url: 'https://play.history.com/', tag: 'Pełne odcinki' },
                        { name: 'MyRM', url: 'https://myrunningman.com/', tag: 'Odcinki Running Man' },
                        { name: 'No-Laughing Batsu Game List', url: 'https://redd.it/2fgm9p' },
                        { name: '⭐ NOXX', url: 'https://noxx.to/', tag: 'Seriale' },
                        { name: 'Owen Davies', url: 'https://www.youtube.com/@ODavies/playlists', tag: 'Seriale 4K' },
                        { name: 'r/Panelshow', url: 'https://www.reddit.com/r/panelshow/', tag: 'Panel Shows' },
                        { name: 'Series Top (Mirror)', url: 'https://srstop.link/' },
                        { name: 'SFBTV', url: 'https://diva.sfsu.edu/collections/sfbatv', tag: 'Archiwum TV San Francisco' },
                        { name: 'Taskmaster', url: 'https://rentry.co/bbbr4cfr', tag: 'Pełne odcinki' },
                        { name: 'The Silent Library', url: 'https://thesilentlibrary.com/', tag: 'Japońskie teleturnieje' },
                        { name: 'Top Series (Mirror)', url: 'https://topsrs.day/' },
                        { name: 'TWC Classics', url: 'https://twcclassics.com/', tag: 'Powtórki Weather Channel' }
                    ]
                },
                {
                    title: 'Cartoon Streaming',
                    links: [
                        { name: 'FunnierMoments', url: 'https://www.funniermoments.net/', tag: 'Seriale' },
                        { name: 'HiCartoons', url: 'https://hicartoon.to/', tag: 'Seriale/Filmy' },
                        { name: '⭐ KimCartoon', url: 'https://kimcartoon.si/', tag: 'Seriale' },
                        { name: 'KissCartoon', url: 'https://kisscartoon.nz/', tag: 'Seriale' },
                        { name: 'SuperCartoons', url: 'https://www.supercartoons.net/', tag: 'Klasyczne/Seriale' },
                        { name: 'TamilToon', url: 'https://tamiltoon.net/', tag: 'Seriale/Filmy/Anime' },
                        { name: 'ToonamiAftermath', url: 'https://www.toonamiaftermath.com/schedule', tag: 'Transmisje Toonami' },
                        { name: 'ToonTales', url: 'https://www.toontales.net/', tag: 'Klasyczne/Seriale' },
                        { name: 'Watch Cartoon Online', url: 'https://www.watchcartoononline.com/', tag: 'Seriale/Filmy/Anime' },
                        { name: '⭐ WCO', url: 'https://www.wco.tv/', tag: 'Seriale/Filmy/Anime' },
                        { name: 'WCOStream (Mirror)', url: 'https://www.wcostream.tv/' }
                    ]
                },
                {
                    title: 'Drama Streaming (Asian)',
                    links: [
                        { name: 'Asiaflix', url: 'https://asiaflix.net/', tag: 'Seriale/Filmy' },
                        { name: 'AsianCrush', url: 'https://www.asiancrush.com/', tag: 'Seriale/Filmy' },
                        { name: 'AsianSubs', url: 'https://asiansubs.com/', tag: 'Seriale/Filmy' },
                        { name: 'Dramacool (Mirror)', url: 'https://dramacool.com.ly/' },
                        { name: '⭐ Dramacool', url: 'https://dramacool.com.tr/', tag: 'Seriale/Filmy' },
                        { name: 'Dramacool.sr (Mirror)', url: 'https://www12.dramacool.sr/' },
                        { name: 'Dramacool9 (Mirror)', url: 'https://dramacools9.cam/' },
                        { name: 'Dramacoold (Mirror)', url: 'https://dramacoold.pl/' },
                        { name: 'Dramacoolk.one (Mirror)', url: 'https://dramacoolk.one/' },
                        { name: 'DramaFire', url: 'https://dramafire.com.pl/', tag: 'Seriale/Filmy' },
                        { name: '⭐ DramaGo', url: 'https://dramago.me/', tag: 'Seriale/Filmy' },
                        { name: 'Dramahood', url: 'https://dramahood.top/', tag: 'Seriale/Filmy' },
                        { name: 'Einthusan', url: 'https://einthusan.tv/intro/', tag: 'Filmy' },
                        { name: '⭐ EverythingMoe', url: 'https://everythingmoe.com/#section-drama', tag: 'Indeks' },
                        { name: 'EverythingMoe (Mirror)', url: 'https://everythingmoe.org/#section-drama' },
                        { name: '⭐ GoPlay', url: 'https://goplay.su/', tag: 'Seriale/Filmy' },
                        { name: 'KissAsian', url: 'https://kissasian.video/', tag: 'Seriale/Filmy' },
                        { name: 'KissAsian (Mirror)', url: 'https://kissasian.com.lv/' },
                        { name: 'kisskh', url: 'https://kisskh.ovh/', tag: 'Seriale/Filmy' },
                        { name: 'kisskh (Mirror)', url: 'https://kisskh.run/' },
                        { name: 'OnDemandChina', url: 'https://www.ondemandchina.com/', tag: 'Seriale/Filmy' },
                        { name: 'Rive Live (Korean Drama)', url: 'https://rivestream.org/kdrama' },
                        { name: 'Vidbox (Asian Drama)', url: 'https://vidbox.to/asian-drama' }
                    ]
                },
                {
                    title: 'Klasyczne i Public Domain',
                    links: [
                        { name: 'Classic Cinema Online', url: 'https://classiccinemaonline.com/', tag: 'Filmy klasyczne' },
                        { name: 'Cinetimes', url: 'https://cinetimes.org/en/', tag: 'Domena publiczna' },
                        { name: 'commons.wikimedia', url: 'https://commons.wikimedia.org/wiki/Category:Videos', tag: 'Pliki wideo Wiki' },
                        { name: 'Danish Silent Film', url: 'https://www.stumfilm.dk/en/stumfilm', tag: 'Archiwum' },
                        { name: 'FilmsByTheYear', url: 'https://www.youtube.com/@FilmsbytheYear/playlists', tag: 'Playlisty YT' },
                        { name: 'FootageFarm', url: 'https://footagefarm.com/', tag: 'Domena publiczna' },
                        { name: 'Historic Films', url: 'https://www.historicfilms.com/', tag: 'Nagrania historyczne' },
                        { name: '⭐ Internet Archive', url: 'https://archive.org/details/moviesandfilms', tag: 'Klasyczne/Nieme' },
                        { name: 'moonflix', url: 'https://moonflix.com/', tag: 'Odnawiane/Koloryzowane' },
                        { name: 'National Film Preservation Foundation', url: 'https://www.filmpreservation.org/' },
                        { name: 'RetroFlix', url: 'https://retroflix.org/', tag: 'Filmy klasyczne' },
                        { name: 'RetroStrange', url: 'https://live.retrostrange.com/', tag: 'Transmisje retro na żywo' },
                        { name: 'Silent Hall of Fame', url: 'https://silent-hall-of-fame.org/', tag: 'Filmy nieme' },
                        { name: 'The Classic Movies', url: 'https://www.the-classic-movies.com/', tag: 'Filmy klasyczne' },
                        { name: 'WikiFlix', url: 'https://wikiflix.toolforge.org/', tag: 'Filmy klasyczne' },
                        { name: 'Wu Tang Collection', url: 'https://www.thewutangcollection.com/', tag: 'Sztuki walki' }
                    ]
                },
                {
                    title: 'Archiwa Filmowe',
                    links: [
                        { name: '35mm', url: 'https://35mm.online/en', tag: 'Polskie Archiwum' },
                        { name: 'Austrian Film Museum', url: 'https://www.filmmuseum.at/jart/prj3/filmmuseum/main.jart?rel=en', tag: 'Archiwum' },
                        { name: 'BFI National Archive', url: 'https://www.bfi.org.uk/bfi-national-archive' },
                        { name: 'BFIPlayer', url: 'https://player.bfi.org.uk/free', tag: 'British Film Institute' },
                        { name: 'British Pathé', url: 'https://www.britishpathe.com/', tag: 'Brytyjskie archiwum wideo' },
                        { name: 'Chicago Film Archives', url: 'https://www.chicagofilmarchives.org/', tag: 'Archiwum' },
                        { name: 'Cinemata', url: 'https://cinemata.org/', tag: 'Filmy z Azji i Pacyfiku' },
                        { name: 'Cinematheque', url: 'https://www.cinematheque.fr/henri/english/', tag: 'Francuskie Archiwum' },
                        { name: 'ColonialFilm', url: 'http://www.colonialfilm.org.uk/', tag: 'Brytyjskie archiwum wideo' },
                        { name: 'Digitaler Lesesaal', url: 'https://digitaler-lesesaal.bundesarchiv.de/en', tag: 'Niemieckie Archiwum' },
                        { name: 'Eastern European Movies', url: 'https://easterneuropeanmovies.com/', tag: 'Archiwum' },
                        { name: 'European Film Gateway', url: 'https://www.europeanfilmgateway.eu/', tag: 'Europejskie Archiwum' },
                        { name: 'Film Polski Database', url: 'https://filmpolski.pl/fp/index.php' },
                        { name: 'Film Portal', url: 'https://www.filmportal.de/en/videos', tag: 'Niemieckie Archiwum' },
                        { name: 'HuntleyArchives', url: 'https://huntleyarchives.com/', tag: 'Rzadkie/Zapomniane' },
                        { name: 'IFI Archive (Mirror)', url: 'https://ifiarchiveplayer.ie/' },
                        { name: 'Imperial War Museums', url: 'https://www.iwm.org.uk/', tag: 'Nagrania wojenne' },
                        { name: 'IndianCine', url: 'https://indiancine.ma/', tag: 'Indyjskie Archiwum' },
                        { name: 'Japanese Animated Film Classics', url: 'https://animation.filmarchives.jp/index.html' },
                        { name: 'National Film Archive of Japan', url: 'https://meiji.filmarchives.jp/' },
                        { name: 'nfb.ca', url: 'https://www.nfb.ca/', tag: 'Kanadyjskie Archiwum' },
                        { name: 'NFSA', url: 'https://www.nfsa.gov.au/', tag: 'Australijskie Archiwum' },
                        { name: 'NGA Taonga', url: 'https://www.ngataonga.org.nz/search-use-collection/search/', tag: 'Archiwum NZ' },
                        { name: 'NLS', url: 'https://www.nls.uk/', tag: 'Szkockie Archiwum' },
                        { name: 'NLS Moving Image (Mirror)', url: 'https://movingimage.nls.uk/' },
                        { name: 'Northern Ireland Screen (Archive)', url: 'https://digitalfilmarchive.net/' },
                        { name: 'NZOnScreen (Mirror)', url: 'https://www.nzonscreen.com/' },
                        { name: 'RussianFilmHub', url: 'https://russianfilmhub.com/', tag: 'Rosyjskie filmy' },
                        { name: 'Stiftung imai', url: 'https://stiftung-imai.de/', tag: 'Niemieckie Archiwum' },
                        { name: 'TexasArchive', url: 'https://texasarchive.org/', tag: 'Archiwum filmowe z Teksasu' },
                        { name: 'The Travel Film Archive', url: 'https://travelfilmarchive.com/', tag: 'Nagrania archiwalne' },
                        { name: '⭐ The Library of Congress', url: 'https://www.loc.gov/film-and-videos/', tag: 'Filmy/Krótkometrażowe' },
                        { name: '⭐ USNationalArchives', url: 'https://www.youtube.com/@USNationalArchives', tag: 'Filmy/Krótkometrażowe' },
                        { name: 'yfanefa', url: 'https://www.yfanefa.com/', tag: 'Archiwum Yorkshire' }
                    ]
                },
                {
                    title: 'TV Streaming (Nie Live)',
                    links: [
                        { name: 'Adult Swim', url: 'https://www.adultswim.com/videos/', tag: 'Pełne odcinki' },
                        { name: 'AZ Series', url: 'https://azseries.org/', tag: 'Seriale' },
                        { name: 'BrokenSilenze', url: 'https://www.brokensilenze.net/', tag: 'Reality TV' },
                        { name: '⭐ CouchTuner', url: 'https://www.couchtuner.show/', tag: 'Seriale/Anime' },
                        { name: 'HDclump', url: 'https://hdclump.com/', tag: 'Dokumenty/Gotowanie' },
                        { name: 'HISTORY', url: 'https://play.history.com/', tag: 'Pełne odcinki' },
                        { name: 'MyRM', url: 'https://myrunningman.com/', tag: 'Odcinki Running Man' },
                        { name: 'No-Laughing Batsu Game List', url: 'https://redd.it/2fgm9p' },
                        { name: '⭐ NOXX', url: 'https://noxx.to/', tag: 'Seriale' },
                        { name: 'Owen Davies', url: 'https://www.youtube.com/@ODavies/playlists', tag: 'Seriale 4K' },
                        { name: 'r/Panelshow', url: 'https://www.reddit.com/r/panelshow/', tag: 'Panel Shows' },
                        { name: 'SFBTV', url: 'https://diva.sfsu.edu/collections/sfbatv', tag: 'Archiwum TV San Francisco' },
                        { name: 'Taskmaster', url: 'https://rentry.co/bbbr4cfr', tag: 'Pełne odcinki' },
                        { name: 'The Silent Library', url: 'https://thesilentlibrary.com/', tag: 'Japońskie teleturnieje' },
                        { name: 'TWC Classics', url: 'https://twcclassics.com/', tag: 'Powtórki Weather Channel' }
                    ]
                }
            ]
        },
        {
            id: 'download-sites',
            title: '💾 Pobieranie Filmów i Seriali (DDL)',
            subsections: [
                {
                    title: 'Strony z Bezpośrednim Pobieraniem',
                    links: [
                        { name: '4KHDHub', url: 'https://4khdhub.fans/', tag: 'Filmy/Seriale/4K' },
                        { name: '9xFlix', url: 'https://www.9xflix.me/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'BEECH (Downloads)', url: 'https://beech.watch/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'Best-MovieZ', url: 'https://www.best-moviez.ws/', tag: 'Filmy/Seriale' },
                        { name: 'BitCine (Downloads)', url: 'https://www.bitcine.app/' },
                        { name: 'Bollywood.eu', url: 'https://bollywood.eu.org/', tag: 'Filmy/Telegram' },
                        { name: 'CinemaOS (Downloads)', url: 'https://cinemaos.live/download', tag: 'Filmy/Seriale/Anime' },
                        { name: 'CinemaOS Me (Downloads)', url: 'https://cinemaos.me/download' },
                        { name: 'CinemaOS Tech (Downloads)', url: 'https://cinemaos.tech/download' },
                        { name: 'Cinemalux', url: 'https://cinemalux.autos/', tag: 'Filmy/Seriale' },
                        { name: 'CineMora (Downloads)', url: 'https://cinemora.ru/' },
                        { name: 'Cineby (Downloads)', url: 'https://www.cineby.app/', tag: 'Filmy/Seriale/Anime/4K' },
                        { name: 'CondensedAudioCatalog', url: 'https://condensedaudiocatalog.com/', tag: 'Dramy Azjatyckie' },
                        { name: 'DDLBase', url: 'https://ddlbase.com/', tag: 'Filmy/4K' },
                        { name: 'Download.ir', url: 'https://download.ir/topics/film/', tag: 'Filmy/Seriale' },
                        { name: 'Downloads-Anymovies (Downloads)', url: 'https://www.downloads-anymovies.co/', tag: 'Filmy' },
                        { name: '⭐ Drama Day', url: 'https://dramaday.me/', tag: 'Dramy Azjatyckie' },
                        { name: 'Fanedit.org', url: 'https://fanedit.org/', tag: 'Społeczność Fanedit' },
                        { name: 'FilmGo', url: 'https://www.filmgo.live/', tag: 'Filmy/Seriale/720p' },
                        { name: 'FlickyStream (Downloads)', url: 'https://flickystream.net', tag: 'Filmy/Seriale/Anime' },
                        { name: 'Free Movies', url: 'https://free-movies.to/', tag: 'Filmy/Seriale' },
                        { name: 'FZMovies', url: 'https://fzmovies.host/', tag: 'Filmy/720p' },
                        { name: 'GoDrivePlayer', url: 'https://godriveplayer.com/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'Goojara (Downloads)', url: 'https://ww1.goojara.to/' },
                        { name: 'HDRush', url: 'https://hdrush.cc/', tag: 'Filmy/Seriale' },
                        { name: 'HollyMovieHD (Downloads)', url: 'https://hollymoviehd.cc/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'IMDb-Scout-Mod', url: 'https://greasyfork.org/en/scripts/407284', tag: 'Dodaj strony pobierania do IMDb' },
                        { name: 'Jackass Vault', url: 'https://discord.gg/ZH5MjcKmJJ', tag: 'Discord' },
                        { name: 'KatMovie4k', url: 'https://katworld.net/?type=Katmovie4k', tag: 'Filmy/Seriale/4K' },
                        { name: 'KatMovieHD', url: 'https://katworld.net/?type=KatmovieHD', tag: 'Filmy/Seriale/Anime' },
                        { name: 'Levidia (Downloads)', url: 'https://www.levidia.ch/', tag: 'Filmy/Seriale/Anime' },
                        { name: '⭐ MKVDrama', url: 'https://mkvdrama.org/', tag: 'Dramy Azjatyckie' },
                        { name: 'Mocine (Downloads)', url: 'https://mocine.cam/' },
                        { name: '⭐ MovieParadise', url: 'https://movieparadise.org/', tag: 'Filmy/Seriale' },
                        { name: 'Movies Ni Pipay', url: 'https://moviesnipipay.me/', tag: 'Filmy/Seriale' },
                        { name: 'MoviesFlix (Mirror)', url: 'https://moviesflix.ad/' },
                        { name: 'Naijavault', url: 'https://www.naijavault.com/', tag: 'Filmy/Seriale/480p' },
                        { name: 'nKiri', url: 'https://nkiri.com/', tag: 'Dramy Azjatyckie/720p' },
                        { name: 'NovaMovie (Downloads)', url: 'https://novamovie.net/' },
                        { name: 'OlaMovies', url: 'https://olamovies.top/', tag: 'Filmy/Seriale/4K' },
                        { name: 'P-Stream (Downloads)', url: 'https://pstream.mov/', tag: 'Filmy/Seriale/Anime' },
                        { name: '⭐ Pahe', url: 'https://pahe.ink/', tag: 'Filmy/Seriale/Anime/4K' },
                        { name: 'PrivateMovieZ', url: 'https://privatemoviez.help/', tag: 'Filmy/Seriale' },
                        { name: 'ProjectFreeTV (Downloads)', url: 'https://projectfreetv.sx/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'ProtonMovies', url: 'https://m2.protonmovies.top/', tag: 'Filmy/Seriale' },
                        { name: 'PSArips', url: 'https://psa.wf/', tag: 'Filmy/Seriale/4K' },
                        { name: 'r/DownUnderTV', url: 'https://www.reddit.com/r/DownUnderTV/', tag: 'AU/NZ TV' },
                        { name: 'RareDoramas', url: 'https://www.raredoramas.com/', tag: 'Rzadkie JDrama/480p' },
                        { name: 'RgShows (Downloads)', url: 'https://www.rgshows.me/' },
                        { name: '⭐ Rive (Downloads)', url: 'https://rivestream.org/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'Rive NET (Downloads)', url: 'https://rivestream.net/' },
                        { name: 'RLSXTVT', url: 'https://rlsxtvt.icu/', tag: 'Filmy/Seriale' },
                        { name: 'Salix (Downloads)', url: 'https://salix.pages.dev/' },
                        { name: 'SD Toons', url: 'https://sdtoons.in/category/cartoon/', tag: 'Filmy/Seriale/Anime/NSFW' },
                        { name: 'SeriesVault', url: 'https://seriesvault.win/', tag: 'Seriale/Anime' },
                        { name: 'SeriesVault Org (Mirror)', url: 'https://seriesvault.org/' },
                        { name: 'SeriezLoaded NG', url: 'https://www.seriezloaded.com.ng/', tag: 'Filmy/Seriale' },
                        { name: 'ShareBB', url: 'https://sharebb.me/', tag: 'Filmy/Seriale' },
                        { name: 'ShareMania', url: 'https://sharemania.us/', tag: 'Filmy/Seriale/4K' },
                        { name: 'ShareSpark', url: 'https://ww1.sharespark.cfd/', tag: 'Filmy/Seriale' },
                        { name: 'Sinflix', url: 'https://rentry.co/FMHYBase64#sinflix', tag: 'Dramy Azjatyckie' },
                        { name: 'SSR Movies', url: 'https://ssrmovies.com/', tag: 'Filmy/Seriale' },
                        { name: 'StagaTV', url: 'https://www.stagatv.com/', tag: 'Filmy/Seriale' },
                        { name: 'Supernova (Downloads)', url: 'https://supernova.to/' },
                        { name: 'TFPDL', url: 'https://tfpdl.se/category/movies/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'TFPDL (Mirror)', url: 'https://tfpdl.to/category/movies/' },
                        { name: 'TodayTVSeries', url: 'https://www.todaytvseries6.com/', tag: 'Seriale/1080p' },
                        { name: 'Toku.fun', url: 'https://toku.fun/', tag: 'Japoński Superhero' },
                        { name: 'TV Shows', url: 'https://tvshows.ac/', tag: 'Seriale/720p' },
                        { name: 'TV Shows (Mirror)', url: 'https://tvshows.in/' },
                        { name: 'TVSeries', url: 'https://www.tvseries.in/', tag: 'Seriale/Anime' },
                        { name: 'TVSBoy', url: 'https://tvsboy.com/', tag: 'Seriale/720p' },
                        { name: 'TvShows4Mobile', url: 'https://tvshows4mobile.org/', tag: 'Seriale/Anime/480p' },
                        { name: 'UHDMovies', url: 'https://modlist.in/?type=uhdmovies', tag: 'Filmy/4K' },
                        { name: '⭐ VegaMovies', url: 'https://vegamovies.gmbh/', tag: 'Filmy/Seriale/Anime/4K' },
                        { name: '⭐ VidBox (Downloads)', url: 'https://vidbox.to/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'Waploaded', url: 'https://films.waploaded.com/movie', tag: 'Filmy/Seriale/480p' },
                        { name: 'Willow (Downloads)', url: 'https://willow.arlen.icu/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'WorldFree4u', url: 'https://worldfree4u.moe/', tag: 'Filmy' },
                        { name: 'YesHD (Downloads)', url: 'https://yeshd.net/' }
                    ]
                },
                {
                    title: 'Drives / Directories',
                    links: [
                        { name: '⭐ 111477', url: 'https://rentry.co/FMHYBase64#directory-111477', tag: 'Filmy/Seriale/Anime' },
                        { name: '⭐ Acer Movies', url: 'https://rentry.co/FMHYBase64#acermovies', tag: 'Filmy/Seriale/Anime' },
                        { name: '⭐ DramaSuki', url: 'https://rentry.co/fmhybase64#dramasuki', tag: 'Dramy Azjatyckie' },
                        { name: 'LightDLMovies', url: 'https://rentry.co/fmhybase64#lightdl', tag: 'Filmy/Seriale' },
                        { name: 'Medeberiya', url: 'https://rentry.co/fmhybase64#medeberiya', tag: 'Filmy/Seriale' },
                        { name: 'ProSearch4Bot', url: 'https://t.me/ProSearch4Bot', tag: 'Filmy z Telegrama' },
                        { name: '⭐ Scloud', url: 'https://rentry.co/FMHYBase64#scloud', tag: 'Filmy/Seriale/4K' },
                        { name: 'SolidarityCinema', url: 'https://www.solidaritycinema.com/', tag: 'Filmy' },
                        { name: 'T4TSA', url: 'https://t4tsa.cc/', tag: 'Filmy/Seriale/Telegram' },
                        { name: 'Vadapav', url: 'https://rentry.co/FMHYBase64#vadapav', tag: 'Filmy/Seriale' }
                    ]
                }
            ]
        },
        {
            id: 'torrent-apps',
            title: '🌊 Aplikacje Torrent (Filmy/Seriale)',
            subsections: [
                {
                    title: '',
                    links: [
                        { name: 'Ace Stream', url: 'https://acestream.org/', tag: 'Aplikacja do streamingu torrentów' },
                        { name: 'Arr Installer', url: 'https://github.com/LordZeuss/arr-installer', tag: 'Instalator' },
                        { name: 'Arr Scripts', url: 'https://github.com/RandomNinjaAtk/arr-scripts/', tag: 'Skrypty automatyzacji' },
                        { name: 'Autobrr', url: 'https://github.com/autobrr/autobrr', tag: 'Automatyczne pobieranie' },
                        { name: 'Autosearch Extension', url: 'https://github.com/trossr32/sonarr-radarr-lidarr-autosearch-browser-extension' },
                        { name: 'Awesome *Arr', url: 'https://ravencentric.cc/awesome-arr/', tag: 'Narzędzia automatyzacji' },
                        { name: 'Bobarr', url: 'https://github.com/iam4x/bobarr', tag: 'Automatyczne pobieranie' },
                        { name: 'Doplarr (Mirror)', url: 'https://github.com/kiranshila/Doplarr' },
                        { name: 'FlexGet', url: 'https://flexget.com/', tag: 'Automatyczne pobieranie' },
                        { name: 'GMDB', url: 'https://github.com/Dentrax/GMDB', tag: 'CLI do streamingu torrentów' },
                        { name: 'Iceetime', url: 'https://github.com/diericx/bevy', tag: 'Self-Hosted Streaming' },
                        { name: '⭐ Jackett', url: 'https://github.com/Jackett/Jackett', tag: 'Automatyczne pobieranie' },
                        { name: 'Magnet Player', url: 'https://ferrolho.github.io/magnet-player/', tag: 'Stream w przeglądarce' },
                        { name: 'nefarious', url: 'https://lardbit.github.io/nefarious/', tag: 'Automatyczne pobieranie' },
                        { name: 'NotFlix', url: 'https://github.com/Bugswriter/notflix', tag: 'Skrypt do streamingu' },
                        { name: 'PeerFlix', url: 'https://github.com/mafintosh/peerflix', tag: 'CLI do streamingu torrentów' },
                        { name: 'Popcorn Time', url: 'https://popcorn-time.site/', tag: 'Aplikacja do streamingu torrentów' },
                        { name: 'Powder', url: 'https://powder.media/', tag: 'Aplikacja do streamingu torrentów' },
                        { name: '⭐ Prowlarr', url: 'https://github.com/Prowlarr/Prowlarr', tag: 'Automatyczne pobieranie' },
                        { name: 'r/softwarr', url: 'https://reddit.com/r/softwarr', tag: 'Automatyczne pobieranie' },
                        { name: '⭐ Radarr', url: 'https://radarr.video/', tag: 'Automatyczne pobieranie filmów' },
                        { name: 'RapidBay (Mirror)', url: 'https://github.com/hauxir/rapidbay' },
                        { name: '⭐ Requestrr', url: 'https://github.com/thomst08/requestrr', tag: 'Bot na Discord' },
                        { name: 'SickChill', url: 'https://sickchill.github.io/', tag: 'Auto Torrent/NZB' },
                        { name: '⭐ Sonarr', url: 'https://sonarr.tv/', tag: 'Automatyczne pobieranie seriali' },
                        { name: '⭐ Stremio', url: 'https://www.stremio.com/', tag: 'Aplikacja do streamingu torrentów' },
                        { name: 'StreamTim (Mirror)', url: 'https://streamtim.com/' },
                        { name: 'Traktarr', url: 'https://github.com/l3uddz/traktarr', tag: 'Automatyczne pobieranie' },
                        { name: 'Unpackerr', url: 'https://unpackerr.zip/', tag: 'Ekstrakcja archiwów' },
                        { name: 'VLC-Bittorrent', url: 'https://github.com/johang/vlc-bittorrent', tag: 'Stream w VLC' },
                        { name: 'Watcher', url: 'https://nosmokingbandit.github.io/', tag: 'Automatyczne pobieranie' },
                        { name: 'WebTorrent', url: 'https://webtorrent.io/', tag: 'Aplikacja do streamingu torrentów' },
                        { name: 'webtorrent-mpv-hook', url: 'https://github.com/mrxdst/webtorrent-mpv-hook', tag: 'Stream w MPV' }
                    ]
                },
                {
                    title: 'Stremio Tools / Addons',
                    links: [
                        { name: 'Anime Catalogs', url: 'https://1fe84bc728af-stremio-anime-catalogs.baby-beamup.club/configure' },
                        { name: '⭐ Bye Sudo', url: 'https://bye.undi.rest/', tag: 'Prosty przewodnik' },
                        { name: 'Midnight\'s Addons (Mirror)', url: 'https://addonsfortheweebs.midnightignite.me/addons' },
                        { name: 'Simkl Stremio', url: 'https://simkl.com/apps/stremio/' },
                        { name: 'Stremio Account Bootstrapper', url: 'https://stremio-account-bootstrapper.vercel.app/' },
                        { name: 'Stremio Addon Manager', url: 'https://addon-manager.viren070.me/' },
                        { name: '⭐ Stremio Addons', url: 'https://stremio-addons.net/', tag: 'Indeks dodatków' },
                        { name: 'Trakt Stremio', url: 'https://2ecbbd610840-trakt.baby-beamup.club/' },
                        { name: 'Up Next', url: 'https://up-next.dontwanttos.top/', tag: 'Katalogi Stremio' },
                        { name: '⭐ Viren070\'s Guides', url: 'https://guides.viren070.me/stremio', tag: 'Zaawansowany przewodnik' }
                    ]
                },
                {
                    title: 'Strony Torrentowe (Filmy/Seriale)',
                    links: [
                        { name: '⭐ 1337x Movies', url: 'https://1337x.to/movie-library/1/', tag: 'Filmy/Seriale/Anime' },
                        { name: '⭐ EZTV', url: 'https://eztvx.to/', tag: 'Seriale/Anime' },
                        { name: '⭐ Heartive (Torrents)', url: 'https://heartive.pages.dev/', tag: 'Filmy/Seriale/Anime' },
                        { name: 'IMDb Link em All', url: 'https://greasyfork.org/en/scripts/17154-imdb-link-em-all', tag: 'Wyniki torrentów na IMDb' },
                        { name: 'IMDb-Scout-Mod (Mirror)', url: 'https://github.com/Purfview/IMDb-Scout-Mod' },
                        { name: 'JapaneseTorrents', url: 'https://japanesetorrents.wordpress.com/', tag: 'Dramy Azjatyckie' },
                        { name: '⭐ Kinozal', url: 'https://kinozal.tv/', tag: 'Filmy/Seriale/4K' },
                        { name: 'LimeTorrents', url: 'https://www.limetorrents.lol/', tag: 'Filmy/Seriale' },
                        { name: 'MSearch', url: 'https://msearch.vercel.app/', tag: 'Filmy/Seriale' },
                        { name: 'Public Domain Movie Torrents', url: 'https://www.publicdomaintorrents.info/' },
                        { name: 'RARBGLite', url: 'https://rarbglite.github.io/', tag: 'Archiwum RARBG' },
                        { name: 'RGShows (Torrents)', url: 'https://www.rgshows.me/torrent/' },
                        { name: '⭐ Rive (Torrents)', url: 'https://rivestream.org/', tag: 'Filmy/Seriale/Anime' },
                        { name: '⭐ RuTracker Movies', url: 'https://rutracker.org/forum/index.php?c=2', tag: 'Filmy/Seriale/Anime/4K' },
                        { name: 'srrextra', url: 'https://github.com/srrDB/srrextra', tag: 'Śledzenie wydań scenowych' },
                        { name: 'TPB Movies', url: 'https://thepiratebay.org/search.php?q=top100:200', tag: 'Filmy/Seriale/4K' },
                        { name: 'Video Torrent CSE', url: 'https://cse.google.com/cse?cx=006516753008110874046:gaoebxgop7j', tag: 'Wyszukiwarka wielu stron' },
                        { name: 'YTS', url: 'https://yts.mx/', tag: 'Filmy' },
                        { name: 'YifyMovies (Mirror)', url: 'https://yifymovies.xyz/' },
                        { name: 'Youplex Torrents', url: 'https://torrents.youplex.site/', tag: 'Filmy/Seriale/Anime/4K' }
                    ]
                }
            ]
        },
        {
            id: 'tracking-databases',
            title: '📊 Śledzenie i Bazy Danych (Filmy/Seriale)',
            links: [
                { name: 'AllMovie', url: 'https://www.allmovie.com/', tag: 'Filmy/Seriale/Anime' },
                { name: 'Blu-ray.com', url: 'https://www.blu-ray.com/', tag: 'DVD/Blu-ray' },
                { name: 'Box Office Mojo', url: 'https://www.boxofficemojo.com/', tag: 'Zarobki' },
                { name: 'CageMatch', url: 'https://www.cagematch.net/', tag: 'Baza danych wrestlingu' },
                { name: 'Class Real', url: 'https://www.classreal.com/', tag: 'Dziwne/psychodeliczne filmy' },
                { name: 'FFCritic', url: 'https://foundfootagecritic.com/', tag: 'Found Footage' },
                { name: 'FlixWatch (Netflix)', url: 'https://www.flixwatch.co/' },
                { name: 'GCDb', url: 'https://www.grindhousedatabase.com/', tag: 'Kino Grindhouse' },
                { name: 'High Def Digest (Mirror)', url: 'https://www.highdefdigest.com/' },
                { name: 'HKMDB', url: 'https://hkmdb.com/db/index.php', tag: 'Filmy z Hongkongu' },
                { name: '⭐ ICheckMovies', url: 'https://www.icheckmovies.com/', tag: 'Listy filmów' },
                { name: 'IGMDB', url: 'https://igmdb.com/', tag: 'Filmy LGBT' },
                { name: 'IMDb', url: 'https://www.imdb.com/', tag: 'Filmy/Seriale/Anime' },
                { name: '⭐ Letterboxd', url: 'https://letterboxd.com/', tag: 'Filmy' },
                { name: 'Libremdb (Frontend)', url: 'https://libremdb.iket.me' },
                { name: 'MediaTracker', url: 'https://github.com/bonukai/MediaTracker', tag: 'Self-Hosted' },
                { name: 'Movieo', url: 'https://movieo.me/', tag: 'Filmy/Seriale/Anime' },
                { name: 'MyDramaList', url: 'https://mydramalist.com/', tag: 'Dramy Azjatyckie' },
                { name: 'namuwiki', url: 'https://en.namu.wiki/', tag: 'Koreańskie media' },
                { name: 'Netflix Top 10', url: 'https://www.netflix.com/tudum/top10', tag: 'Najczęściej oglądane' },
                { name: '⭐ RatS', url: 'https://github.com/StegSchreck/RatS', tag: 'Transfer ocen' },
                { name: 'Rotten Tomatoes', url: 'https://www.rottentomatoes.com/', tag: 'Filmy/Seriale' },
                { name: '⭐ serializd', url: 'https://www.serializd.com/', tag: 'Seriale/Anime' },
                { name: '⭐ Simkl', url: 'https://simkl.com/', tag: 'Seriale/Anime/Filmy' },
                { name: 'Spaghetti Western Database', url: 'https://www.spaghetti-western.net/index.php/Main_Page' },
                { name: 'TMDb', url: 'https://www.themoviedb.org/', tag: 'Filmy/Seriale/Anime' },
                { name: '⭐ Trakt', url: 'https://trakt.tv/', tag: 'Seriale/Anime/Filmy' },
                { name: 'uNoGS (Netflix)', url: 'https://unogs.com/' },
                { name: 'What\'s on Netflix', url: 'https://www.whats-on-netflix.com/library/', tag: 'Przeglądaj bibliotekę' },
                { name: 'What\'s on Netflix (Mirror)', url: 'https://www.whats-on-netflix.com/' }
            ]
        },
        {
            id: 'curated-recommendations',
            title: '💖 Kuratorowane Rekomendacje',
            subsections: [
                {
                    title: '',
                    links: [
                        { name: 'Age Rating JuJu', url: 'https://www.ageratingjuju.com/', tag: 'Oceny wiekowe mediów' },
                        { name: 'agoodmovietowatch (Mirror)', url: 'https://agoodmovietowatch.com/' },
                        { name: 'Charts and Culture', url: 'https://pastebin.com/uRDJVGkL', tag: 'Katalog rekomendacji' },
                        { name: 'CommonSenseMedia', url: 'https://www.commonsensemedia.org/', tag: 'Recenzje wg wieku' },
                        { name: 'cringeMDb', url: 'https://cringemdb.com/', tag: 'Filmy bezpieczne dla rodziny' },
                        { name: 'DigitalDreamDoor', url: 'https://digitaldreamdoor.com/', tag: 'Listy 100 najlepszych' },
                        { name: 'Episode Hive (Mirror)', url: 'https://episodehive.com/' },
                        { name: '⭐ FlickMetrix', url: 'https://flickmetrix.com/', tag: 'Połączone oceny' },
                        { name: 'IMDb Table', url: 'https://docyx.github.io/imdb-table', tag: 'Wykresy ocen odcinków seriali' },
                        { name: 'Kids in Mind (Mirror)', url: 'https://kids-in-mind.com/' },
                        { name: 'kudos.wiki', url: 'https://kudos.wiki/', tag: 'Wikipedia Top 1000' },
                        { name: 'listal', url: 'https://www.listal.com/', tag: 'Filmy/Seriale' },
                        { name: 'MRQE', url: 'https://www.mrqe.com/', tag: 'Wyszukiwarka recenzji filmów' },
                        { name: '⭐ RatingsGraph', url: 'https://www.ratingraph.com/', tag: 'Wykresy ocen' },
                        { name: 'ReelScary', url: 'https://www.reelscary.com/', tag: 'Oceny strasznych filmów' },
                        { name: 'RYM Ultimate Film Lists', url: 'https://rateyourmusic.com/list/TheScientist/rym-ultimate-film-genres-and-lists/', tag: 'Gatunki filmowe' },
                        { name: 'SeriesGraph (Mirror)', url: 'https://seriesgraph.com' },
                        { name: 'Sight and Sound', url: 'https://www.bfi.org.uk/sight-and-sound/greatest-films-all-time/', tag: 'Top 250 filmów' },
                        { name: '⭐ TasteDive', url: 'https://tastedive.com/', tag: 'Rekomendacje' },
                        { name: 'TheShowGrid (Mirror)', url: 'https://theshowgrid.com/' },
                        { name: '⭐ They Shoot Pictures', url: 'https://www.theyshootpictures.com/', tag: 'Top 1000 filmów' },
                        { name: 'They Shoot Zombies', url: 'https://theyshootzombies.com/', tag: 'Top 1000 horrorów' },
                        { name: 'TreasureTV', url: 'https://www.treasuretv.org/', tag: 'Kuratorowana lista seriali' },
                        { name: 'TV Chart (Mirror)', url: 'https://tvchart.benmiz.com/' },
                        { name: 'TV Charts (Mirror)', url: 'https://tvcharts.co/' },
                        { name: 'WhatToWatchOn.tv (Mirror)', url: 'https://whattowatchon.tv/' }
                    ]
                },
                {
                    title: 'Narzędzia do Rekomendacji',
                    links: [
                        { name: 'BestSimilar', url: 'https://bestsimilar.com/', tag: 'Rekomendacje filmów' },
                        { name: 'Cinetrii', url: 'https://cinetrii.com/', tag: 'Podobne motywy' },
                        { name: 'Match-a-Movie', url: 'https://match-a-movie.com/', tag: 'Z przyjaciółmi' },
                        { name: 'Movie-Map', url: 'https://www.movie-map.com/' },
                        { name: 'MovieLens', url: 'https://movielens.org/', tag: 'Rekomendacje filmów' },
                        { name: 'MovieSync', url: 'https://movie-sync-app.web.app/', tag: 'Z przyjaciółmi' },
                        { name: 'NextFlick', url: 'https://nextflick.tv/', tag: 'Losowe zwiastuny' },
                        { name: '⭐ Nothing To Watch', url: 'https://nothing-to-watch.port80.ch/', tag: 'Wizualizacja odkryć' },
                        { name: 'r/MovieSuggestions', url: 'https://www.reddit.com/r/MovieSuggestions/' },
                        { name: 'Simkl', url: 'https://simkl.com/', tag: 'Na podstawie ocen' },
                        { name: 'SuggestStream', url: 'https://suggestream.com/', tag: 'Filmy/Seriale' },
                        { name: 'Taste.io', url: 'https://www.taste.io/', tag: 'Rekomendacje filmów' }
                    ]
                }
            ]
        },
        {
            id: 'calendar-upcoming',
            title: '📅 Kalendarz i Nadchodzące Premiery',
            links: [
                { name: 'Drama Countdown (Mirror)', url: 'https://dramacountdown.com/' },
                { name: 'DVDs Release Dates (Mirror)', url: 'https://www.dvdsreleasedates.com/' },
                { name: 'Episode Calendar', url: 'https://episodecalendar.com/', tag: 'Harmonogramy TV' },
                { name: '⭐ Movie Countdown', url: 'https://moviescountdown.com/', tag: 'Nadchodzące filmy' },
                { name: 'My Episodes', url: 'https://www.myepisodes.com/', tag: 'Seriale' },
                { name: 'Next Episode (Mirror)', url: 'https://next-episode.net/' },
                { name: 'Releases.com', url: 'https://www.releases.com/', tag: 'Daty premier' },
                { name: 'showRSS', url: 'https://showrss.info/', tag: 'RSS seriali' },
                { name: 'TV Countdown (Mirror)', url: 'https://countdown.tv/' },
                { name: 'TVMaze', url: 'https://www.tvmaze.com/', tag: 'Seriale' },
                { name: 'TrailerPunk', url: 'https://trailerpunk.com/', tag: 'Najnowsze zwiastuny' },
                { name: 'WhenToStream', url: 'https://www.whentostream.com/', tag: 'Wiadomości o premierach' },
                { name: '⭐ Your Countdown To', url: 'https://yourcountdown.to/', tag: 'Filmy/Seriale/Gry' }
            ]
        },
        {
            id: 'subtitle-tools',
            title: '🗣️ Narzędzia do Napisów',
            subsections: [
                {
                    title: 'Edytory i Konwertery Napisów',
                    links: [
                        { name: 'Adjust Subs Like a Pro', url: 'https://graph.org/Adjust-subtitles-in-seconds-like-a-pro-07-17', tag: 'Przewodnik ffsubsync' },
                        { name: 'Aegisub', url: 'https://github.com/arch1t3cht/Aegisub/releases', tag: 'Edytor napisów' },
                        { name: 'asbplayer', url: 'https://killergerbah.github.io/asbplayer/', tag: 'Wydobywanie zdań' },
                        { name: 'asstosrt-wasm', url: 'https://sorz.github.io/asstosrt-wasm/', tag: 'ASS/SSA do SRT' },
                        { name: 'Auto Synced & Translated Dubs', url: 'https://github.com/ThioJoe/Auto-Synced-Translated-Dubs' },
                        { name: 'Auto-Subtitle (Mirror)', url: 'https://www.veed.io/tools/auto-subtitle-generator-online' },
                        { name: 'autosubsync (Mirror)', url: 'https://github.com/oseiskar/autosubsync' },
                        { name: 'autosubsync-mpv (Mirror)', url: 'https://github.com/joaquintorres/autosubsync-mpv' },
                        { name: 'DST (Mirror)', url: 'https://www.syedgakbar.com/projects/dst' },
                        { name: 'elSubtitle', url: 'https://www.elsubtitle.com/', tag: 'Narzędzia do napisów' },
                        { name: 'Fansub Guide (Mirror)', url: 'https://unanimated.github.io/guides.htm' },
                        { name: 'ffsubsync (Mirror)', url: 'https://github.com/smacke/ffsubsync' },
                        { name: 'FreeSubtitlesAI (Mirror)', url: 'https://freesubtitles.ai/' },
                        { name: 'gmkvextractgui (Mirror)', url: 'https://sourceforge.net/projects/gmkvextractgui/' },
                        { name: 'GPTSubtitler (Mirror)', url: 'https://gptsubtitler.com/' },
                        { name: 'I am Scum (Mirror)', url: 'https://iamscum.wordpress.com/guides/' },
                        { name: 'Jubler', url: 'https://www.jubler.org/', tag: 'Edytor napisów' },
                        { name: 'mkv-extract', url: 'https://qgustavor.github.io/mkv-extract/', tag: 'Wyodrębnij napisy' },
                        { name: 'MKVcleaver (Mirror)', url: 'https://www.videohelp.com/software/MKVcleaver' },
                        { name: 'Movie-Subtitles (Mirror)', url: 'https://github.com/gignupg/Movie-Subtitles' },
                        { name: 'Penguin', url: 'https://github.com/carsonip/Penguin-Subtitle-Player', tag: 'Odtwarzacz zew. napisów' },
                        { name: 'pyTranscriber (Mirror)', url: 'https://pytranscriber.github.io/' },
                        { name: 'Revoldiv (Mirror)', url: 'https://revoldiv.com/' },
                        { name: 'SoniTranslate', url: 'https://github.com/R3gm/SoniTranslate', tag: 'Tłumacz wideo' },
                        { name: 'SRT AI Translator (Mirror)', url: 'https://github.com/passthesh3ll/srt-ai-translator' },
                        { name: 'SubConverter', url: 'https://subconverter.com/', tag: 'Narzędzia do napisów' },
                        { name: 'Subshifter', url: 'https://subshifter.bitsnbites.eu/', tag: 'Synchronizuj napisy' },
                        { name: 'Subtitle Edit', url: 'https://nikse.dk/subtitleedit' },
                        { name: 'Subtitle One', url: 'https://subtitleone.cc/', tag: 'Narzędzia do napisów' },
                        { name: 'Subtitle Tools (Mirror)', url: 'https://subtitletools.com/' },
                        { name: 'Subtitle Workshop Classic', url: 'https://sourceforge.net/projects/subtitle-workshop-classic/' },
                        { name: 'Subtitld', url: 'https://subtitld.org/', tag: 'Edytor napisów' },
                        { name: 'Subtitling Guide', url: 'https://baechusquad.download/guide/' },
                        { name: '⭐ Substital', url: 'https://substital.com/', tag: 'Rozszerzenie do zew. napisów' },
                        { name: 'Sushi.net', url: 'https://github.com/maxpiva/Sushi.Net', tag: 'Auto synchronizacja napisów' },
                        { name: 'Tero Subtitler', url: 'https://www.uruworks.net/', tag: 'Edytor napisów' },
                        { name: 'TranslatesSubtitles', url: 'https://translatesubtitles.com/', tag: 'Tłumacz napisy' },
                        { name: 'TranslatesSubtitles (Mirror)', url: 'https://translatesubtitles.co/' },
                        { name: 'Turboscribe (Mirror)', url: 'https://turboscribe.ai/' },
                        { name: 'Vibe (Mirror)', url: 'https://thewh1teagle.github.io/vibe/' },
                        { name: 'VideoSubFinder', url: 'https://sourceforge.net/projects/videosubfinder/', tag: 'Wyodr. wbudowanych napisów' },
                        { name: 'Whisper', url: 'https://huggingface.co/spaces/BatuhanYilmaz/Whisper-Auto-Subtitled-Video-Generator', tag: 'Auto-napisy wideo' },
                        { name: 'WithSubtitles', url: 'https://withsubtitles.com/', tag: 'Transkrypcja wideo' },
                        { name: 'YukiSubs Guides', url: 'https://yukisubs.wordpress.com/guides/' }
                    ]
                },
                {
                    title: 'Pobieranie Napisów',
                    links: [
                        { name: '⭐ Addic7ed', url: 'https://www.addic7ed.com/', tag: 'Napisy' },
                        { name: '⭐ Auto-Subtitles', url: 'https://www.bazarr.media/', tag: 'Automatyczne wyszukiwanie/pobieranie' },
                        { name: 'DownSub', url: 'https://downsub.com/', tag: 'Pobieranie z witryn wideo' },
                        { name: 'Gestdown (Frontend)', url: 'https://www.gestdown.info/' },
                        { name: 'IndexSubtitle', url: 'https://indexsubtitle.cc/', tag: 'Napisy' },
                        { name: 'JustSubtitles', url: 'https://justsubtitles.com/', tag: 'Napisy' },
                        { name: 'JustSubtitles (Mirror)', url: 'https://subss.vercel.app/' },
                        { name: 'kitsuneko', url: 'https://kitsunekko.net/', tag: 'Napisy do anime' },
                        { name: '⭐ Open Subtitles', url: 'https://opensubtitles.org/', tag: 'Napisy' },
                        { name: 'Open Subtitles (Beta)', url: 'https://www.opensubtitles.com/' },
                        { name: 'Podnapisi', url: 'https://www.podnapisi.net/', tag: 'Napisy' },
                        { name: 'SaveSubs', url: 'https://www.savesubs.com/', tag: 'Wyodrębnianie z wideo online' },
                        { name: '⭐ SubDL', url: 'https://subdl.com/', tag: 'Napisy' },
                        { name: 'Subliminal (Mirror)', url: 'https://subliminal.readthedocs.io/' },
                        { name: '⭐ Subscene', url: 'https://sub-scene.com/', tag: 'Napisy' },
                        { name: 'Subsearch', url: 'https://github.com/vagabondHustler/subsearch', tag: 'Skrypt Python' },
                        { name: 'SubSource', url: 'https://subsource.net/', tag: 'Napisy' },
                        { name: 'Subtitle Cat', url: 'https://www.subtitlecat.com/', tag: 'Napisy' },
                        { name: 'Subtitlist', url: 'https://subtitlist.com/', tag: 'Napisy' },
                        { name: 'TVSubtitles', url: 'https://www.tvsubtitles.net/', tag: 'Napisy do seriali' },
                        { name: 'YTS Subs (Mirror)', url: 'https://yts-subs.com/' },
                        { name: 'YifySubtitles', url: 'https://yifysubtitles.ch/', tag: 'Napisy' }
                    ]
                }
            ]
        },
        {
            id: 'helpful-tools',
            title: '🛠️ Przydatne Narzędzia i Strony (Filmy/Seriale)',
            subsections: [
                {
                    title: '',
                    links: [
                        { name: 'AtlasOfWonders (Mirror)', url: 'https://www.atlasofwonders.com/' },
                        { name: 'Bechdel Test', url: 'https://bechdeltest.com/', tag: 'Sprawdzanie filmów' },
                        { name: 'Behind the Voice Actors', url: 'https://www.behindthevoiceactors.com/', tag: 'Baza danych' },
                        { name: '⭐ BingeClock', url: 'https://www.bingeclock.com/', tag: 'Kalkulator długości seriali' },
                        { name: 'Can I Binge? (Mirror)', url: 'https://canibinge.com/' },
                        { name: 'Caps-A-Holic', url: 'https://caps-a-holic.com/', tag: 'Porównaj jakość wydań' },
                        { name: 'DailyScript (Mirror)', url: 'https://www.dailyscript.com/' },
                        { name: 'DMT', url: 'https://dmtalkies.com/', tag: 'Wyjaśnienia zakończeń' },
                        { name: 'DoesTheDogDie', url: 'https://www.doesthedogdie.com/', tag: 'Spoilery filmowe' },
                        { name: 'DramaWiki', url: 'https://wiki.d-addicts.com/', tag: 'Wiki o dramatach azjatyckich' },
                        { name: '⭐ FastStream', url: 'https://faststream.online/', tag: 'Rozszerzenie do streamingu' },
                        { name: 'Find Movie', url: 'https://find-movie.info/', tag: 'Baza cytatów filmowych' },
                        { name: 'FlickChart', url: 'https://www.flickchart.com/', tag: 'Ranking Twoich filmów' },
                        { name: 'Forever Dreaming', url: 'https://transcripts.foreverdreaming.org/', tag: 'Transkrypcje mediów' },
                        { name: 'HanCinema (Mirror)', url: 'https://www.hancinema.net/' },
                        { name: 'HowDoesTheMovieEnd', url: 'http://www.howdoesthemovieend.com/', tag: 'Spoilery filmowe' },
                        { name: 'IMissedTheStart', url: 'https://imissedthestart.com/', tag: 'Podsumuj części' },
                        { name: 'IMFDB', url: 'https://www.imfdb.org/', tag: 'Baza broni palnej w filmach' },
                        { name: 'IMSDB (Mirror)', url: 'https://imsdb.com/' },
                        { name: 'Internet Movie Cars Database', url: 'https://www.imcdb.org/' },
                        { name: 'KoreanDrama (Mirror)', url: 'https://www.koreandrama.org/' },
                        { name: 'Media Stack DIY', url: 'http://tennojim.xyz/article/media_stack_diy', tag: 'Przewodnik po wysokiej jakości' },
                        { name: 'mov-cli', url: 'https://mov-cli.github.io/', tag: 'CLI do streamingu/pobierania' },
                        { name: 'Movie-Censorship', url: 'https://www.movie-censorship.com/', tag: 'Porównaj wersje' },
                        { name: 'Movie-Locations', url: 'https://www.movie-locations.com/', tag: 'Mapy lokalizacji filmowych' },
                        { name: 'MovieLoci (Mirror)', url: 'https://www.movieloci.com/' },
                        { name: 'MoviePooper (Mirror)', url: 'https://moviepooper.com/' },
                        { name: '⭐ OpenVideo', url: 'https://openvideofs.github.io', tag: 'Odtwarzacz bez reklam' },
                        { name: '⭐ Quality / Release Type Guide', url: 'https://redd.it/1ktgh4h' },
                        { name: 'QuoDB (Mirror)', url: 'https://www.quodb.com/' },
                        { name: 'r/movieleaks (Mirror)', url: 'https://reddit.com/r/movieleaks' },
                        { name: '⭐ Release Group Qualities', url: 'https://docs.google.com/spreadsheets/u/0/d/1xz5zqrBumfMtLGA4VMt1VtOyh-47HDTv_swIYktX6AQ/htmlview', tag: 'Indeks jakości' },
                        { name: 'RunPee', url: 'https://runpee.com/', tag: 'Czasy przerw w filmach' },
                        { name: 'Scripts.com (Mirror)', url: 'https://www.scripts.com/' },
                        { name: 'ScriptSlug (Mirror)', url: 'https://www.scriptslug.com/' },
                        { name: 'Scripts Onscreen (Mirror)', url: 'https://scripts-onscreen.com/' },
                        { name: 'ShotOnWhat?', url: 'https://shotonwhat.com/', tag: 'Informacje techniczne o filmie' },
                        { name: 'SimplyScripts (Mirror)', url: 'https://www.simplyscripts.com/' },
                        { name: 'Sprocket School', url: 'https://www.sprocketschool.org/', tag: 'Wiki o wystawianiu filmów' },
                        { name: 'Starring the Computer', url: 'https://www.starringthecomputer.com/', tag: 'Baza komputerów w filmach' },
                        { name: 'Stream-Bypass (Mirror)', url: 'https://github.com/ByteDream/stream-bypass' },
                        { name: 'Streaming Site Guide', url: 'https://redd.it/yykvnv' },
                        { name: 'SubsLikeScript', url: 'https://subslikescript.com/', tag: 'Scenariusze mediów' },
                        { name: 'TG-FileStreamBot', url: 'https://github.com/EverythingSuckz/TG-FileStreamBot', tag: 'Streaming z Telegrama' },
                        { name: 'themoviespoiler (Mirror)', url: 'https://themoviespoiler.com/' },
                        { name: 'tiii.me (Mirror)', url: 'https://tiii.me/' },
                        { name: 'unconsenting media', url: 'https://www.unconsentingmedia.org', tag: 'Baza danych przemocy seksualnej' },
                        { name: 'Video Quality Guide (Mirror)', url: 'https://www.reddit.com/r/Piracy/wiki/guides/video_quality_and_types_of_releases' },
                        { name: 'What is My Movie? (Mirror)', url: 'https://www.whatismymovie.com/' },
                        { name: 'WhatsatMovie', url: 'https://whatsatmovie.com/', tag: 'Znajdź po opisie' },
                        { name: 'WhereDidTheyFilmThat (Mirror)', url: 'https://www.wheredidtheyfilmthat.co.uk/' },
                        { name: '⭐ WhereYouWatch', url: 'https://whereyouwatch.com/latest-reports/', tag: 'Powiadomienia o wyciekach filmów' },
                        { name: 'WheresTheJump?', url: 'https://wheresthejump.com/', tag: 'Wyszukiwarka jump scare\'ów' },
                        { name: 'WheresTheScares? (Mirror)', url: 'https://wheresthescares.com/' }
                    ]
                },
                {
                    title: 'Wyszukiwarki Multi-Site',
                    links: [
                        { name: 'Streaming CSE', url: 'https://cse.google.com/cse?cx=006516753008110874046:cfdhwy9o57g##gsc.tab=0', tag: 'Wyszukiwarka wielu stron' },
                        { name: 'Streaming CSE 2 (Mirror)', url: 'https://cse.google.com/cse?cx=006516753008110874046:o0mf6t-ugea##gsc.tab=0' },
                        { name: 'Streaming CSE 3 (Mirror)', url: 'https://cse.google.com/cse?cx=98916addbaef8b4b6' },
                        { name: 'Streaming CSE 4 (Mirror)', url: 'https://cse.google.com/cse?cx=0199ade0b25835f2e' },
                        { name: 'Video Download CSE', url: 'https://cse.google.com/cse?cx=006516753008110874046:wevn3lkn9rr', tag: 'Wyszukiwarka wielu stron' },
                        { name: 'Video Download CSE 2 (Mirror)', url: 'https://cse.google.com/cse?cx=89f2dfcea452fc451' },
                        { name: 'Video Download CSE 3 (Mirror)', url: 'https://cse.google.com/cse?cx=aab218d0aa53e3578' },
                        { name: 'Video Search CSE', url: 'https://cse.google.com/cse?cx=006516753008110874046:6v9mqdaai6q#gsc.tab=0', tag: 'Wyszukiwarka wielu stron' }
                    ]
                }
            ]
        }
    ]
};