const pageData = {
  featured: [
    {
      name: "Soulseek",
      url: "https://slsknet.org/",
      badge: "P2P KLASYK",
      description: "Najlepsza sieć P2P do muzyki, miliony utworów w FLAC/320kbps"
    },
    {
      name: "Cobalt",
      url: "https://cobalt.tools/",
      badge: "UNIWERSALNY DOWNLOADER",
      description: "YouTube, SoundCloud, TikTok i więcej - najlepszy multi-downloader"
    },
    {
      name: "DoubleDouble",
      url: "https://doubledouble.top/",
      badge: "320KBPS DOWNLOAD",
      description: "Szybkie pobieranie MP3/FLAC w 320kbps z wielu źródeł"
    },
    {
      name: "Lucida",
      url: "https://lucida.to/",
      badge: "RIPPER ONLINE",
      description: "Spotify, Deezer, YouTube, SoundCloud - ripowanie w jednym miejscu"
    },
    {
      name: "Firehawk52 Collection",
      url: "https://rentry.co/firehawk52",
      badge: "MEGA KOLEKCJA",
      description: "Ogromna kolekcja linków i narzędzi do pobierania muzyki Hi-Res"
    }
  ],
  sections: [
    {
      id: "streaming-muzyki",
      title: "🎵 Streaming Muzyki (Online & Apps)",
      subsections: [
        {
          title: "Streamingowe Aplikacje Desktopowe",
          links: [
            { name: "Beatsync", url: "https://www.beatsync.gg/", tag: "Słuchaj Razem" },
            { name: "BetterSoundcloud", url: "https://alirezakj.com/bsc/", tag: "Bez Reklam" },
            { name: "Custom YTM GitHub", url: "https://github.com/th-ch/youtube-music" },
            { name: "Custom YouTube Music", url: "https://th-ch.github.io/youtube-music/", tag: "Klient YT Music" },
            { name: "Deezer", url: "https://www.deezer.com/", tag: "Aplikacja Streamingowa" },
            { name: "FunkWhale", url: "https://funkwhale.audio/", tag: "Federated" },
            { name: "Moosync", url: "https://moosync.app/", tag: "YT/Spotify" },
            { name: "MP3Jam", url: "https://www.mp3jam.org/" },
            { name: "Muffon", url: "https://muffon.netlify.app/" },
            { name: "MusicBucket", url: "https://musicbucket.net/", tag: "Integracja z Telegramem" },
            { name: "Nuclear", url: "https://nuclearplayer.com/", tag: "Klient Multi-Source" },
            { name: "pulse (Mirror)", url: "https://473999.net/pulse" },
            { name: "yewtube", url: "https://github.com/mps-youtube/yewtube", tag: "Klient YT Music" }
          ]
        },
        {
          title: "Strony Streamingowe (WebUIs)",
          links: [
            { name: "Archeophone (Mirror)", url: "https://www.archeophone.org/html/languages/en/index.en.html" },
            { name: "Audiomack", url: "https://audiomack.com/" },
            { name: "AudionautiX", url: "https://audionautix.com/", tag: "Wg Nastroju" },
            { name: "Audius", url: "https://audius.co/", tag: "Blockchain" },
            { name: "Bandcamp Free", url: "https://bandcamp.com/discover/free-music", tag: "Darmowe Wydania" },
            { name: "BitMidi", url: "https://bitmidi.com/", tag: "Pliki MIDI" },
            { name: "CitizenFreak", url: "https://citizenfreak.com/", tag: "Muzyka Kanadyjska" },
            { name: "Classical Music Only", url: "https://classicalmusiconly.com/" },
            { name: "CLPGS (Mirror)", url: "https://www.clpgs.org.uk/" },
            { name: "DAB Music Player", url: "https://dab.yeet.su/", tag: "Qobuz/Lossless" },
            { name: "DAB Music XYZ (Mirror)", url: "https://dabmusic.xyz/" },
            { name: "DatPiff", url: "https://datpiff.com/", tag: "Mixtape'y Hip-Hop" },
            { name: "DigLib", url: "https://diglib.library.vanderbilt.edu/ama-browse.pl", tag: "Nagrania Afrykańskie" },
            { name: "DMO", url: "https://dance-music.org/", tag: "Elektroniczna" },
            { name: "Dream of the 90s", url: "https://www.youtube.com/@Dreamofthe90s/playlists", tag: "Niszowe z lat 90." },
            { name: "FirstSounds", url: "https://www.firstsounds.org/", tag: "Najstarsze Nagrania" },
            { name: "FreeListenOnline", url: "https://freelistenonline.com/" },
            { name: "Hype Machine", url: "https://hypem.com/popular", tag: "Wschodzący Artyści" },
            { name: "i78s", url: "https://i78s.org/", tag: "Gramofon" },
            { name: "Irama Nusantara", url: "https://www.iramanusantara.org/en", tag: "Muzyka Indonezyjska" },
            { name: "Jamendo", url: "https://www.jamendo.com/", tag: "Muzyka CC" },
            { name: "Jango", url: "https://jango.com/" },
            { name: "Keygen Music", url: "https://keygenmusic.tk/" },
            { name: "LostMyspace", url: "http://lostmyspace.com/", tag: "Archiwum" },
            { name: "Measuring Polyphony", url: "https://measuringpolyphony.org/", tag: "Średniowieczna" },
            { name: "Mirlo", url: "https://mirlo.space/", tag: "Darmowe Wydania" },
            { name: "Mixupload", url: "https://mixupload.com/" },
            { name: "MixtapeMonkey", url: "https://mixtapemonkey.com/", tag: "Mixtape'y Hip-Hop" },
            { name: "musopen", url: "https://musopen.org/music/", tag: "Darmowa Klasyka" },
            { name: "Musico", url: "https://www.musi-co.com/listen/", tag: "Generowane przez AI" },
            { name: "New Age Music", url: "https://newage.one/" },
            { name: "Newgrounds Audio", url: "https://www.newgrounds.com/audio", tag: "Twórczość Użytkowników" },
            { name: "Nonoki", url: "https://nonoki.com/music/", tag: "YT Music WebUI" },
            { name: "Openwhyd", url: "https://openwhyd.org/", tag: "Udostępnianie Muzyki" },
            { name: "OperaOnVideo", url: "https://www.operaonvideo.com/", tag: "Nagrania Operowe" },
            { name: "Pandora", url: "https://www.pandora.com/" },
            { name: "Reddit Music Player", url: "https://reddit.musicplayer.io/" },
            { name: "Russian Records", url: "https://www.russian-records.com/", tag: "Rosyjskie Nagrania" },
            { name: "Saavn Web", url: "https://saavn-web-ui.vercel.app/", tag: "Muzyka Indyjska" },
            { name: "SoundClick", url: "https://www.soundclick.com/default.cfm" },
            { name: "SoundCloud", url: "https://soundcloud.com/", tag: "Piosenki od Użytkowników" },
            { name: "Spotify Web Player", url: "https://open.spotify.com/", tag: "Z reklamami" },
            { name: "Tancpol", url: "https://tancpol.net/", tag: "Polski/Rosyjski" },
            { name: "Tasso Music", url: "https://www.tassomusic.org/", tag: "Wczesna Nowożytność" },
            { name: "The Urban Emporium", url: "https://www.youtube.com/@theurbanemporium204/playlists", tag: "Hip-Hop YT" },
            { name: "Tinfoil (Mirror)", url: "https://www.tinfoil.com/" },
            { name: "UCSB Cylinders (Mirror)", url: "https://cylinders.library.ucsb.edu/index.php" },
            { name: "Vapor Archive", url: "https://vaporarchive.neocities.org/", tag: "Vaporwave" },
            { name: "YouTube Music", url: "https://music.youtube.com/", tag: "Oficjalny" },
            { name: "Youtaite", url: "https://www.youtaite.com/", tag: "UTAU/Vocaloid" },
            { name: "zvu4no", url: "https://zvu4no.org/", tag: "Rosyjski" }
          ]
        }
      ]
    },
    {
      id: "ripping-and-downloading",
      title: "💾 Ripperowanie & Pobieranie Muzyki",
      subsections: [
        {
          title: "Strony do Ripperowania Audio",
          links: [
            { name: "AMP3", url: "https://amp3.cc/", tag: "YouTube/320kb" },
            { name: "cobalt", url: "https://cobalt.tools/", tag: "SC/320kb/MP3" },
            { name: "DAB Music Player", url: "https://dab.yeet.su/", tag: "Qobuz/FLAC" },
            { name: "DAB Music XYZ (Mirror)", url: "https://dabmusic.xyz/" },
            { name: "DoubleDouble", url: "https://doubledouble.top/", tag: "Multi-Site/320kb/FLAC" },
            { name: "EzConv", url: "https://ezconv.com/", tag: "YouTube/320kb" },
            { name: "Jumo-DL", url: "https://jumo-dl.pages.dev/", tag: "Qobuz" },
            { name: "lucida", url: "https://lucida.to/", tag: "Multi-Site/320kb/FLAC" },
            { name: "QQDL", url: "https://qqdl.site/", tag: "Qobuz" },
            { name: "squid.wtf", url: "https://squid.wtf/", tag: "Qobuz/Khinsider/FLAC" },
            { name: "YTiz", url: "https://ytiz.xyz/", tag: "YT/SC/Bandcamp/AAC" }
          ]
        },
        {
          title: "Narzędzia do Ripperowania Audio",
          links: [
            { name: "AccurateRip", url: "https://www.accuraterip.com/", tag: "Weryfikacja Ripów" },
            { name: "BandCamp-DL", url: "https://github.com/iheanyi/bandcamp-dl", tag: "Bandcamp" },
            { name: "Deemix Revival (Mirror)", url: "https://github.com/bambanah/deemix" },
            { name: "DeemixFix", url: "https://gitlab.com/deeplydrumming/DeemixFix", tag: "Deezer/FLAC" },
            { name: "Exact Audio Copy", url: "https://www.exactaudiocopy.de/", tag: "Ripper CD/DVD" },
            { name: "Firehawk52", url: "https://rentry.co/firehawk52", tag: "Qobuz/Tidal" },
            { name: "GamDL", url: "https://github.com/glomatico/gamdl", tag: "Apple/FLAC" },
            { name: "Murglar", url: "https://murglar.app/", tag: "Deezer/SC/VK" },
            { name: "Nicotine+", url: "https://nicotine-plus.org/", tag: "Klient Soulseek" },
            { name: "OnTheSpot", url: "https://github.com/justin025/onthespot", tag: "Ripper Wielu Stron" },
            { name: "OrpheusDL", url: "https://github.com/OrfiTeam/OrpheusDL", tag: "Deezer/Qobuz" },
            { name: "qobuz-dl (Mirror)", url: "https://github.com/vitiko98/qobuz-dl" },
            { name: "QobuzDownloaderX-MOD", url: "https://github.com/DJDoubleD/QobuzDownloaderX-MOD", tag: "Qobuz/FLAC" },
            { name: "Shira", url: "https://github.com/KraXen72/shira", tag: "YT/SC/Bandcamp" },
            { name: "Soggfy", url: "https://github.com/Rafiuth/Soggfy", tag: "Ripper Spotify" },
            { name: "Soulseek", url: "https://slsknet.org/", tag: "Udostępnianie Audio P2P" },
            { name: "streamrip", url: "https://github.com/nathom/streamrip", tag: "Deezer/Tidal/Qobuz/SC" },
            { name: "tidal-dl-ng", url: "https://github.com/exislow/tidal-dl-ng", tag: "Tidal" },
            { name: "Votify", url: "https://github.com/glomatico/votify", tag: "Ripper Spotify" },
            { name: "Whipper", url: "https://github.com/whipper-team/whipper", tag: "Ripper CD/DVD" },
            { name: "you-get", url: "https://you-get.org/", tag: "SC/Bilibili" }
          ]
        },
        {
          title: "Telegram Boty do Muzyki",
          links: [
            { name: "@BeatSpotBot", url: "https://t.me/BeatSpotBot", tag: "Spotify/Deezer/Tidal" },
            { name: "@deezload2bot (Mirror)", url: "https://t.me/deezload2bot" },
            { name: "@DeezerMusicBot", url: "https://t.me/DeezerMusicBot", tag: "Deezer/FLAC" },
            { name: "@GlomaticoBlueMusicBot", url: "https://t.me/GlomaticoBlueMusicBot", tag: "Amazon Music" },
            { name: "@GlomaticoPinkMusicBot", url: "https://t.me/GlomaticoPinkMusicBot", tag: "Apple Music" },
            { name: "@JioDLBot", url: "https://t.me/JioDLBot", tag: "JioSaavn/Gaana/FLAC" },
            { name: "@mephbot (Mirror)", url: "https://t.me/mephbot" },
            { name: "@motreb_downloader_bot", url: "https://t.me/motreb_downloader_bot", tag: "Spotify" },
            { name: "@MusicsHuntersbot (Mirror)", url: "https://t.me/MusicsHuntersbot" },
            { name: "@scdlbot", url: "https://t.me/scdlbot", tag: "SC/Bandcamp" },
            { name: "Song_downloaderbot", url: "https://t.me/Song_downloaderbot", tag: "JioSaavn" },
            { name: "@soundcloudaudiodownloader", url: "https://t.me/soundcloudaudiodownloader", tag: "YT/SC" },
            { name: "@spotifydownloadrobot", url: "https://t.me/spotifydownloadrobot", tag: "Spotify" },
            { name: "@vkmsaverbot", url: "https://t.me/vkmsaverbot", tag: "VK" },
            { name: "@vkmusbot (Mirror)", url: "https://t.me/vkmusbot" }
          ]
        },
        {
          title: "Generalne Strony do Pobierania Muzyki",
          links: [
            { name: "AlterPortal", url: "https://alterportal.net/", tag: "MP3/FLAC" },
            { name: "ArtistGrid", url: "https://artistgrid.cx/", tag: "Niewydana Muzyka" },
            { name: "ArtScene (Mirror)", url: "http://artscene.textfiles.com/music/midi/" },
            { name: "Audio Download CSE", url: "https://cse.google.com/cse?cx=006516753008110874046:ibmyuhh72io", tag: "Wyszukiwarka Wielu Stron" },
            { name: "Audio Download CSE 2 (Mirror)", url: "https://cse.google.com/cse?cx=006516753008110874046:ohobg3wvr_w" },
            { name: "Audio Download CSE 3 (Mirror)", url: "https://cse.google.com/cse?cx=32d85b41e2feacd3f" },
            { name: "BitMidi", url: "https://bitmidi.com/", tag: "Pliki MIDI" },
            { name: "CannaPower", url: "https://canna-power.to", tag: "MP3" },
            { name: "ccMixter", url: "https://ccmixter.org/", tag: "DL/Stream/CC" },
            { name: "Cliggo", url: "https://music.cliggo.com/", tag: "MP3" },
            { name: "CoreRadio", url: "https://coreradio.online/", tag: "MP3/FLAC" },
            { name: "DeadPulpit", url: "https://www.deadpulpit.com/", tag: "MP3" },
            { name: "DiscogC", url: "https://www.discogc.com/", tag: "FLAC" },
            { name: "Exystence", url: "https://exystence.net/", tag: "MP3/FLAC" },
            { name: "Ezhevika", url: "https://ezhevika.blogspot.com/", tag: "192kb/MP3" },
            { name: "FindFlac", url: "https://findflac.com/", tag: "FLAC/MP3/MP4" },
            { name: "FLAC Attack", url: "https://flacattack.net/", tag: "FLAC" },
            { name: "FlacMusic", url: "https://www.flacmusic.info/", tag: "FLAC" },
            { name: "Gangster", url: "https://gangster.su/", tag: "MP3/FLAC" },
            { name: "Geocities Midis (Mirror)", url: "https://archive.org/details/archiveteam-geocities-midi-collection-2009" },
            { name: "GetRockMusic", url: "https://getrockmusic.net/", tag: "MP3/FLAC" },
            { name: "GloryBeats", url: "https://glorybeats.com/", tag: "MP3" },
            { name: "IntMusic", url: "https://intmusic.net/", tag: "MP3/FLAC" },
            { name: "iPlusFree", url: "https://www7.iplusfree.org/", tag: "iTunes M4A" },
            { name: "iTDMusic (Mirror)", url: "https://itdmusic.in/" },
            { name: "iTopMusic (Mirror)", url: "https://itopmusicx.com/" },
            { name: "Internet Archive", url: "https://archive.org/details/audio", tag: "MP3" },
            { name: "LEAKED", url: "https://leaked.cx/", tag: "MP3" },
            { name: "Lossless-FLAC", url: "https://lossless-flac.com/", tag: "FLAC" },
            { name: "Lossless-Music", url: "https://lossless-music.org/", tag: "FLAC" },
            { name: "LosslessAlbums", url: "https://losslessalbums.club/", tag: "FLAC" },
            { name: "Losslessma", url: "https://losslessma.net/", tag: "FLAC" },
            { name: "Mixupload", url: "https://mixupload.com/", tag: "MP3" },
            { name: "Moe:81", url: "https://rentry.co/FMHYBase64#moe81", tag: "MP3/FLAC" },
            { name: "mp3db", url: "https://mp3db.pro/", tag: "MP3" },
            { name: "Music Download Guide", url: "https://rentry.co/wheredownloadmusic", tag: "Indeks Stron" },
            { name: "Music Hoarders", url: "https://discord.gg/kQUQkuwSaT", tag: "Społeczność" },
            { name: "Music Rider", url: "https://musicrider.org/", tag: "MP3/FLAC" },
            { name: "musify", url: "https://musify.club/", tag: "320kb/MP3" },
            { name: "New Album Releases", url: "https://newalbumreleases.net/", tag: "MP3" },
            { name: "nodata", url: "https://nodata.tv/", tag: "MP3" },
            { name: "Plastinka", url: "https://plastinka.org/", tag: "MP3/FLAC" },
            { name: "punk.cat", url: "https://punkcata.blogspot.com/", tag: "320kb/MP3" },
            { name: "QMusic", url: "https://rentry.co/FMHYBase64#qmusic", tag: "MP3/FLAC" },
            { name: "RockDownload", url: "https://www.rockdownload.org/", tag: "320kb/MP3" },
            { name: "r/xTrill", url: "https://reddit.com/r/xTrill", tag: "Reddit/Aplikacja do Pobierania" },
            { name: "Saavn Web", url: "https://saavn-web-ui.vercel.app/", tag: "MP3" },
            { name: "ShareMania", url: "https://sharemania.us/", tag: "FLAC/MP3/M4A" },
            { name: "SongsLover", url: "https://songslover.li/", tag: "256kb/MP3" },
            { name: "SongStems", url: "https://songstems.net/", tag: "Pliki STEM" },
            { name: "SoundClick", url: "https://www.soundclick.com/default.cfm", tag: "MP3" },
            { name: "Tancpol", url: "https://tancpol.net/", tag: "MP3" },
            { name: "ThemFire", url: "https://themfire.pro/", tag: "MP3/FLAC" },
            { name: "TrackerHub (Mirror)", url: "https://trackerhub.cx/" },
            { name: "Tricotism (Mirror)", url: "https://www.tricotism.com/" },
            { name: "VGMusic (Mirror)", url: "https://www.vgmusic.com/" },
            { name: "VK::MP3", url: "https://metacpan.org/pod/VK::MP3", tag: "Narzędzie do Wyszukiwania VK" },
            { name: "xprm", url: "https://xprm.net/", tag: "DL/Stream/Prośby" },
            { name: "z3.fm", url: "https://z3.fm/", tag: "MP3" },
            { name: "zvu4no", url: "https://zvu4no.org/", tag: "MP3" }
          ]
        },
        {
          title: "YouTube & Multi-Platform Downloaders",
          links: [
            { name: "AZMP3", url: "https://azmp3.cc/" },
            { name: "BestMP3Converter", url: "https://www.bestmp3converter.com/" },
            { name: "CnvMP3", url: "https://cnvmp3.com/" },
            { name: "Convert2MP3", url: "https://convert2mp3.cc/" },
            { name: "DeezMate", url: "https://deezmate.com/", tag: "Deezer/Spotify" },
            { name: "EzMP3", url: "https://ezmp3.cc/" },
            { name: "FLVTO", url: "https://flvto.biz/" },
            { name: "Free MP3", url: "https://en2.freemp3.tube/" },
            { name: "iViGo", url: "https://ivigo.cc/" },
            { name: "Locoloader", url: "https://www.locoloader.com/" },
            { name: "Media-Downloader", url: "https://github.com/mhogomchungu/media-downloader/", tag: "GUI" },
            { name: "OFA Downloader", url: "https://oneforalldownloader.com/" },
            { name: "Open Video Downloader", url: "https://github.com/StefanLobbenmeier/youtube-dl-gui", tag: "Desktop" },
            { name: "Racoon", url: "https://shailendramaurya.github.io/racoon/", tag: "Multi-platform" },
            { name: "Stacher", url: "https://stacher.io/", tag: "GUI dla YT-DLP" },
            { name: "Tartube", url: "https://github.com/axcore/tartube/", tag: "Manager" },
            { name: "Y2Mate", url: "https://y2mate.is/" },
            { name: "YT-DLP", url: "https://github.com/yt-dlp/yt-dlp", tag: "Najlepszy CLI" },
            { name: "YT1s", url: "https://yt1s.com/" },
            { name: "YT1s Pro", url: "https://yt1s.pro/" },
            { name: "YTConv", url: "https://ytconv.net/" },
            { name: "yt-dlg", url: "https://oleksis.github.io/youtube-dl-gui/", tag: "GUI" },
            { name: "yt-dlp-gui", url: "https://github.com/dsymbol/yt-dlp-gui", tag: "Modern" },
            { name: "ytdlp-interface", url: "https://github.com/ErrorFlynn/ytdlp-interface" },
            { name: "ytDownloader", url: "https://github.com/aandrew-me/ytDownloader", tag: "Web UI" },
            { name: "ytDownloader Web", url: "https://ytdn.netlify.app/" },
            { name: "Ytmdl Web", url: "https://ytmdl.deepjyoti30.dev/" },
            { name: "YTMP3 CC", url: "https://ytmp3.cc/" },
            { name: "YTMP3 NU", url: "https://ytmp3.nu/" },
            { name: "YTMP3 Plus", url: "https://ytmp3.plus/" },
            { name: "YTMP3 Video", url: "https://ytmp3.video/" },
            { name: "YTMP3 Zone", url: "https://ytmp3.zone/" },
            { name: "YTMP3Hub", url: "https://ytmp3hub.com/" },
            { name: "YTPP3", url: "https://ytpp3.com/" },
            { name: "YTPP3 Org", url: "https://ytpp3.org/" },
            { name: "YouTubeMP3.to", url: "https://youtubemp3.to/" }
          ]
        },
        {
          title: "SoundCloud & Bandcamp Downloaders",
          links: [
            { name: "BandCamp-DL", url: "https://github.com/iheanyi/bandcamp-dl", tag: "CLI" },
            { name: "Bandcamp Downloader", url: "https://downloadmusicschool.com/bandcamp/" },
            { name: "BandcampMP3", url: "https://bandcampmp3.org/" },
            { name: "BCDownloader", url: "https://bcdownloader.com/" },
            { name: "DownloadSound.cloud", url: "https://downloadsound.cloud/" },
            { name: "Free Bandcamp Download", url: "https://freebandcampdownload.com/" },
            { name: "SCDL", url: "https://github.com/flyingrub/scdl", tag: "CLI" },
            { name: "SCDownloader IO", url: "https://scdownloader.io/" },
            { name: "SoundCloud to MP3", url: "https://soundcloudmp3.cc/" },
            { name: "SoundCloud to MP3 Pro", url: "https://soundcloud-to-mp3.com/" },
            { name: "SoundCloudMP3 Org", url: "https://soundcloudmp3.org/" },
            { name: "SoundCloudToMP3 App", url: "https://soundcloudtomp3.app/" }
          ]
        }
      ]
    },
    {
      id: "p2p-and-torrents",
      title: "🔄 P2P & Torrenty Muzyczne",
      subsections: [
        {
          title: "P2P Sieci",
          links: [
            { name: "Nicotine+", url: "https://nicotine-plus.org/", tag: "Klient Soulseek" },
            { name: "slsk-batchdl", url: "https://github.com/fiso64/slsk-batchdl", tag: "Pobieranie Wsadowe" },
            { name: "slskd", url: "https://github.com/slskd/slskd", tag: "Aplikacja Serwerowa" },
            { name: "Slsk Upload Stats Tracker", url: "https://github.com/mrusse/Slsk-Upload-Stats-Tracker" },
            { name: "Soulseek", url: "https://slsknet.org/", tag: "Udostępnianie Audio P2P" }
          ]
        },
        {
          title: "Torrenty Muzyczne",
          links: [
            { name: "Audio Torrent CSE", url: "https://cse.google.com/cse?cx=006516753008110874046:v75cyb4ci55", tag: "Wyszukiwarka Wielu Stron" },
            { name: "BlackTorrent", url: "https://blacktorrent.ru/", tag: "Metal" },
            { name: "iPlayMetal (Mirror)", url: "https://metal.iplay.ro/" },
            { name: "JapaneseTorrents", url: "https://japanesetorrents.wordpress.com/", tag: "Torrenty z Muzyką Japońską" },
            { name: "Metal Tracker", url: "https://en.metal-tracker.com/", tag: "Metal" },
            { name: "MixtapeTorrent", url: "http://www.mixtapetorrent.com/", tag: "Mixtape'y" },
            { name: "New-Team", url: "https://new-team.org/", tag: "MP3/FLAC" },
            { name: "NFO DB", url: "https://nfodb.net.ru/", tag: "Baza NFO" },
            { name: "Orpheus", url: "https://orpheus.network/", tag: "Prywatny Tracker" },
            { name: "PandaCD", url: "https://pandacd.io/", tag: "Muzyka od Użytkowników" },
            { name: "PreDB.eu", url: "https://predb.eu", tag: "PreDB Muzyki" },
            { name: "Redacted", url: "https://redacted.sh/", tag: "Elitarny Prywatny Tracker" },
            { name: "RockBox (Mirror)", url: "https://rawkbawx.rocks/" },
            { name: "RuTracker Music", url: "https://rutracker.org/forum/index.php?c=8", tag: "Ogromna Baza" },
            { name: "The /kpg/ torrent", url: "https://rentry.co/FMHYBase64#kpop-torrent", tag: "K-Pop" },
            { name: "TheMixingBowl", url: "https://themixingbowl.org/", tag: "Forum/Mixy" },
            { name: "TorrentTech", url: "https://torrents.torrentech.org/", tag: "Elektroniczna" },
            { name: "TPB Top 100 Music", url: "https://thepiratebay.org/search.php?q=top100:100", tag: "Popularne" },
            { name: "TribalMixes", url: "https://www.tribalmixes.com/", tag: "Mixy DJ-skie" }
          ]
        }
      ]
    },
    {
      id: "spotify-tools",
      title: "🎧 Spotify - Narzędzia i Mody",
      subsections: [
        {
          title: "Narzędzia i Mody",
          links: [
            { name: "Album Availability Map (Mirror)", url: "https://kaaes.github.io/albums-availability/" },
            { name: "BlockTheSpot", url: "https://github.com/mrpond/BlockTheSpot", tag: "Patcher bez Reklam" },
            { name: "Canvas Downloader", url: "https://www.canvasdownloader.com/", tag: "Pobieranie Canvas" },
            { name: "Chart My Music", url: "https://www.chartmymusic.com/spotify/", tag: "Generator Kolaży" },
            { name: "Kira", url: "https://kira.vercel.app/", tag: "Dostępność Regionalna" },
            { name: "Kotify", url: "https://github.com/dzirbel/kotify", tag: "Menedżer Biblioteki" },
            { name: "ListenByLabel", url: "https://www.lbl.fm/", tag: "Wyszukiwanie Wytwórni" },
            { name: "LoaderSpot", url: "https://loadspot.pages.dev/", tag: "Archiwum Instalatorów" },
            { name: "Lofi", url: "https://www.lofi.rocks/", tag: "Widget Mini Odtwarzacza" },
            { name: "Music Megathread", url: "https://github.com/MoonWalker440/Music-Megathread/", tag: "Indeks Strumieniowania" },
            { name: "Music Streaming Guide", url: "https://dan.valeena.dev/guides/music-streaming/", tag: "Porównania" },
            { name: "Opslagify", url: "https://opslagify.deruever.nl/", tag: "Kalkulator Rozmiaru" },
            { name: "Random Music Generator", url: "https://random-song.com/" },
            { name: "ReleaseFeed", url: "https://releasefeed.elomatreb.eu/", tag: "Kanały RSS" },
            { name: "Skiley (Mirror)", url: "https://skiley.net/" },
            { name: "Spicetify", url: "https://spicetify.app/", tag: "Motywy i Wtyczki" },
            { name: "Spicetify CLI (GitHub)", url: "https://github.com/spicetify/cli" },
            { name: "sptlrx (Mirror)", url: "https://github.com/raitonoberu/sptlrx" },
            { name: "Spotube", url: "https://github.com/KRTirtho/spotube", tag: "Klient open-source Spotify z YouTube jako źródłem" },
            { name: "SpotX", url: "https://github.com/SpotX-Official/SpotX", tag: "Patcher bez Reklam" },
            { name: "Syrics", url: "https://syrics-web-akashrchandran.vercel.app/", tag: "Pobieranie Zsynchronizowanych Tekstów" },
            { name: "Tierify", url: "https://tierify.app/", tag: "Listy Poziomów" },
            { name: "Trikatuka", url: "https://trikatuka.aknakn.eu/", tag: "Migracja Danych" },
            { name: "Versefy", url: "https://versefy.app/", tag: "Zsynchronizowane Teksty" },
            { name: "Wiki Comparisons (Mirror)", url: "https://en.wikipedia.org/wiki/Comparison_of_music_streaming_services" },
            { name: "xmplaylist", url: "https://xmplaylist.com/", tag: "Kanały SiriusXM" }
          ]
        },
        {
          title: "Narzędzia do Playlist",
          links: [
            { name: "chat jams (Mirror)", url: "https://www.chatjams.ai/" },
            { name: "Chosic (Mirror)", url: "https://www.chosic.com/" },
            { name: "Exportify", url: "https://exportify.app/", tag: "Eksport Playlist" },
            { name: "Exportify GitHub (Mirror)", url: "https://github.com/watsonbox/exportify" },
            { name: "Playlist Hospital", url: "https://playlisthospital.com/", tag: "Przywracanie Utworów" },
            { name: "Playlist Randomizer", url: "https://stevenaleong.com/tools/spotifyplaylistrandomizer", tag: "Lepsze Losowanie" },
            { name: "Playlist Sorter", url: "https://www.playlistsorter.com/" },
            { name: "Playlistor", url: "https://playlistor.io/", tag: "Apple Music do Spotify" },
            { name: "PlaylistProxy", url: "https://playlistproxy.net/", tag: "Udostępniaj Anonimowo" },
            { name: "playlists.cloud", url: "https://playlists.cloud/", tag: "Transfer Playlist" },
            { name: "Share Liked Songs", url: "https://nonnullish.github.io/share-liked-songs/", tag: "Udostępnianie Playlist" },
            { name: "Sort Your Music (Mirror)", url: "http://sortyourmusic.playlistmachinery.com/" },
            { name: "Spotify Dedup", url: "https://spotify-dedup.com/", tag: "Usuwanie Duplikatów" },
            { name: "Spotify Playlist Archive", url: "https://spotifyplaylistarchive.com/" },
            { name: "spotify-backup (Mirror)", url: "https://github.com/caseychu/spotify-backup" },
            { name: "Spotify2YouTubeMusic (Mirror)", url: "https://github.com/mahdi-y/Spotify2YoutubeMusic" },
            { name: "spotgen", url: "https://epsil.github.io/spotgen", tag: "Generator Playlist" },
            { name: "Spotlistr", url: "https://www.spotlistr.com/", tag: "Z Platformy na Spotify" },
            { name: "SpotTransfer (Mirror)", url: "https://spot-transfer.vercel.app/" },
            { name: "Tagify", url: "https://tagify.me/", tag: "Tagowanie Playlist" },
            { name: "Timelineify", url: "https://www.timelineify.com/", tag: "Dyskografia Artysty" },
            { name: "Trikatuka (Mirror)", url: "https://trikatuka.aknakn.eu/" },
            { name: "Unheard.FM (Mirror)", url: "https://unheard.fm/" }
          ]
        }
      ]
    },
    {
      id: "concerts-and-live-shows",
      title: "🎤 Koncerty & Live Showy",
      links: [
        { name: "365 Radio", url: "https://365.ilysm.nl/", tag: "Kanały DJ-skie na YouTube" },
        { name: "ASOTArchive (Mirror)", url: "http://www.asotarchive.org/" },
        { name: "BassBlog", url: "https://bassblog.pro/", tag: "Mixy DJ-skie" },
        { name: "BBC Radio 1 Essential Mix", url: "https://rentry.co/FMHYBase64#bbc-essential" },
        { name: "bt.etree", url: "https://bt.etree.org/", tag: "Torrenty z Koncertami" },
        { name: "Cadenza", url: "http://www.cadenza.org/", tag: "Koncerty Klasyczne" },
        { name: "ConcertArchives", url: "https://www.concertarchives.org/", tag: "Śledzenie/Baza Danych" },
        { name: "DimeADozen", url: "http://www.dimeadozen.org/", tag: "Torrenty z Koncertami" },
        { name: "etreedb", url: "https://etreedb.org/", tag: "Baza Danych Koncertów" },
        { name: "FindYourFest", url: "https://wwwfindyourfest.com/", tag: "Festiwale Muzyczne" },
        { name: "GOA PsyTrance Livesets", url: "https://rentry.co/FMHYBase64#goa-psytrance-livesets" },
        { name: "Guitars101", url: "https://www.guitars101.com/", tag: "Bootlegi Koncertowe" },
        { name: "hate5six", url: "https://hate5six.com/", tag: "Koncerty Hardcore" },
        { name: "JamBase", url: "https://www.jambase.com/videos", tag: "Nagrania Koncertowe" },
        { name: "LiveBootlegConcert", url: "https://livebootlegconcert.blogspot.com/" },
        { name: "Lossless Legs", url: "https://www.shnflac.net/", tag: "Torrenty z Koncertami" },
        { name: "MiroPPB", url: "https://miroppb.com/", tag: "Archiwa Trance" },
        { name: "Mixing.dj", url: "https://mixing.dj/", tag: "Mixy DJ-skie" },
        { name: "MuseBootlegs", url: "https://www.musebootlegs.com/", tag: "Torrenty z Bootlegami" },
        { name: "Phish.in", url: "https://phish.in/", tag: "Archiwum Phish" },
        { name: "Radio Nowhere", url: "https://rentry.co/FMHYBase64#radio-nowhere", tag: "Bruce Springsteen" },
        { name: "RATM.live", url: "https://ratm.live/", tag: "Archiwum Rage" },
        { name: "Rave Recording", url: "https://rentry.co/fmhybase64#rave-library", tag: "Archiwum" },
        { name: "Relisten", url: "https://relisten.net/", tag: "Nagrania Koncertowe" },
        { name: "RHCPLiveArchive", url: "https://www.rhcplivearchive.com/", tag: "Archiwum RHCP" },
        { name: "setlist.fm", url: "https://www.setlist.fm/", tag: "Baza Danych Setlist" },
        { name: "SongKick", url: "https://www.songkick.com/", tag: "Znajdź Koncerty" },
        { name: "TestPressing", url: "https://www.testpressing.org/", tag: "Rzadkie Mixy DJ-skie" },
        { name: "TheTradersDen", url: "http://www.thetradersden.org/", tag: "Torrenty z Koncertami" },
        { name: "ToolDriveProject", url: "https://tooldriveproject.net/", tag: "Archiwum na żywo Tool" },
        { name: "TopDJMixes", url: "https://topdjmixes.com/", tag: "Mixy DJ-skie" },
        { name: "Volume", url: "https://volume.com/", tag: "Koncerty na żywo" },
        { name: "WorldConcertHall", url: "https://www.worldconcerthall.com/en/schedule-list/", tag: "Transmisje na żywo" }
      ]
    },
    {
      id: "radio-streaming",
      title: "📻 Radio Streaming (Online)",
      subsections: [
        {
          title: "Globalne Stacje Radiowe",
          links: [
            { name: "AudioFilesDrive", url: "https://t.me/AudioFilesDrive", tag: "Pobieranie Słuchowisk" },
            { name: "BBC Sounds", url: "https://www.bbc.co.uk/sounds", tag: "Na Żywo i Archiwum" },
            { name: "Braggoscope", url: "https://www.braggoscope.com/", tag: "BBC In Our Time" },
            { name: "Broadcastify", url: "https://www.broadcastify.com/", tag: "Służby/Kolej" },
            { name: "Drive n Listen", url: "https://drivenlisten.com/", tag: "Symulatory Jazdy" },
            { name: "Flicker Radio", url: "https://flickermini.pages.dev/radiostations", tag: "Lekkie" },
            { name: "iHeartRadio", url: "https://www.iheart.com/" },
            { name: "ilovemusic", url: "https://ilovemusic.de/", tag: "Katalog Niemiecki" },
            { name: "Instant.audio", url: "https://instant.audio/", tag: "Minimalistyczne" },
            { name: "Internet Archive", url: "https://archive.org/details/audio?&sort=-downloads&page=1", tag: "Klasyczne Radio" },
            { name: "LiveATC", url: "https://www.liveatc.net/", tag: "Ruch Lotniczy" },
            { name: "LiveOnlineRadio", url: "https://liveonlineradio.net/", tag: "Globalny Katalog" },
            { name: "Mixcloud", url: "https://www.mixcloud.com/" },
            { name: "morsecode.me (Mirror)", url: "https://morsecode.me/" },
            { name: "myTuner", url: "https://mytuner-radio.com/", tag: "Globalne Radio i Podcasty" },
            { name: "Old Time Radio (Mirror)", url: "https://oldtime.radio/" },
            { name: "Old Time Radio Downloads", url: "https://www.oldtimeradiodownloads.com/" },
            { name: "OnlineRadioBox", url: "https://onlineradiobox.com/", tag: "Międzynarodowy Katalog" },
            { name: "OpenMHz", url: "https://openmhz.com/", tag: "Radio Policyjne" },
            { name: "QMPlay2", url: "https://github.com/zaps166/QMPlay2", tag: "Odtwarzacz Desktopowy" },
            { name: "raddio", url: "https://raddio.net/", tag: "Minimalistyczne" },
            { name: "Radio Browser", url: "https://www.radio-browser.info/users", tag: "Otwarta Baza Danych" },
            { name: "Radio Garden", url: "https://radio.garden/", tag: "Globalny Globus" },
            { name: "Radio Guide", url: "https://www.radioguide.fm/" },
            { name: "Radio.net", url: "https://www.radio.net/", tag: "Międzynarodowy Katalog" },
            { name: "radiobot", url: "https://t.me/radiobot", tag: "Bot na Telegram" },
            { name: "RadioFeeds (Mirror)", url: "http://www.radiofeeds.co.uk/" },
            { name: "radioline", url: "https://www.radioline.co/", tag: "Agregator" },
            { name: "RadioReference", url: "https://www.radioreference.com/", tag: "Kod Morse'a" },
            { name: "Relic Radio", url: "https://www.relicradio.com/", tag: "Klasyczne Radio" },
            { name: "StreamURL", url: "https://streamurl.link/", tag: "Wyszukiwarka URL" },
            { name: "Streema", url: "https://streema.com/", tag: "Globalny Katalog" },
            { name: "TheOneStopRadio", url: "https://theonestopradio.com/" },
            { name: "TuneIn", url: "https://tunein.com/" },
            { name: "TuneYou", url: "https://tuneyou.com/", tag: "Skupiony na Odkrywaniu" },
            { name: "Tvradiotuner", url: "https://tvradiotuner.com/", tag: "TV i Radio" },
            { name: "UKRadioLive", url: "https://ukradiolive.com/", tag: "Katalog UK" },
            { name: "VRadio", url: "https://www.akouradio.com/", tag: "Aplikacja" },
            { name: "vTuner", url: "https://vtuner.com/setupapp/guide/asp/BrowseStations/startpage.asp", tag: "Integracja Sprzętowa" },
            { name: "WorldRadioMap", url: "https://worldradiomap.com/", tag: "Globalna Mapa" },
            { name: "Worldwide Radio", url: "https://addons.mozilla.org/en-US/firefox/addon/worldwide-radio/", tag: "Rozszerzenie" },
            { name: "Xiph", url: "https://dir.xiph.org/", tag: "Icecast/Ogg" }
          ]
        },
        {
          title: "Internet Radio (Specjalistyczne)",
          links: [
            { name: "0nRadio", url: "https://www.0nradio.com/", tag: "Katalog" },
            { name: "0x40", url: "https://0x40.mon.im/", tag: "Elektroniczna/Anime" },
            { name: "1a Radio", url: "https://www.1aradio.com/", tag: "Katalog" },
            { name: "420.moe", url: "https://420.moe/", tag: "Radio 420" },
            { name: "AccuRadio", url: "https://www.accuradio.com/" },
            { name: "Audiophile", url: "https://audiophile.fm/" },
            { name: "BoxRadio", url: "https://boxradio.net/" },
            { name: "Campus FM", url: "https://www.campus-fm.com/", tag: "Radio Studenckie" },
            { name: "CoreRadio", url: "https://coreradio.online/listen", tag: "Metalcore/Hardcore" },
            { name: "Daft Punk Cafe", url: "https://daftpunk.cafe/", tag: "Daft Punk" },
            { name: "deepcut.fm", url: "https://deepcut.live/", tag: "Niszowe Utwory" },
            { name: "Di.fm", url: "https://www.di.fm/", tag: "Elektroniczna" },
            { name: "DubLab", url: "https://www.dublab.com/" },
            { name: "Freeform Radio", url: "https://www.freeformradio.directory/", tag: "Katalog" },
            { name: "HappyHardcore", url: "https://www.happyhardcore.com/radio/", tag: "Hardcore Dance" },
            { name: "HollowEarthRadio", url: "https://www.hollowearthradio.org/", tag: "Artyści z NW" },
            { name: "Internet-Radio", url: "https://internet-radio.com/", tag: "Katalog Stacji" },
            { name: "J1 Radio", url: "https://rec.torontocast.stream/player/", tag: "J-Pop" },
            { name: "KWSX Radio", url: "https://radio.kwsx.online/", tag: "Wspierane przez Słuchaczy" },
            { name: "LISTEN.moe", url: "https://listen.moe/", tag: "K-Pop" },
            { name: "Live365", url: "https://live365.com/", tag: "Stacje Użytkowników" },
            { name: "Nectarine", url: "https://www.scenestream.net/demovibes/streams/", tag: "Demoscena" },
            { name: "Nightride.fm", url: "https://nightride.fm/", tag: "Synthwave" },
            { name: "Nightwave Plaza", url: "https://plaza.one/", tag: "Vaporwave" },
            { name: "NTS Radio", url: "https://www.nts.live/", tag: "Audycje DJ-skie" },
            { name: "Ongaku", url: "https://ongaku.js.org/", tag: "Radio Anime" },
            { name: "Openings Moe", url: "https://openings.moe/", tag: "Motywy z Anime" },
            { name: "Pool Suite", url: "https://poolsuite.net/", tag: "Radio Letnie" },
            { name: "Q-3", url: "https://www.q-3.eu/" },
            { name: "Quasar Radio", url: "https://kuasark.com/en/", tag: "Katalog" },
            { name: "r-a-d.io (Mirror)", url: "https://r-a-d.io/" },
            { name: "radio.dubbeh", url: "https://radio.dubbeh.net/", tag: "Niezależne" },
            { name: "radio.uwu", url: "https://radio.uwu.network/", tag: "Subkultura" },
            { name: "Radiodeck", url: "https://www.radiodeck.com/", tag: "Odtwarzacz/Katalog" },
            { name: "Radiooooo", url: "https://radiooooo.com/", tag: "Wehikuł Czasu" },
            { name: "RadioParadise", url: "https://radioparadise.com/", tag: "Wspierane przez Słuchaczy" },
            { name: "RadioSide", url: "https://radioside.com/", tag: "Odbiornik" },
            { name: "Rekt FM", url: "https://rekt.network/", tag: "Chill/EDM" },
            { name: "ShoutCast", url: "https://directory.shoutcast.com/", tag: "Stacje Użytkowników" },
            { name: "SomaFM", url: "https://somafm.com/", tag: "Wspierane przez Użytkowników" },
            { name: "streamWriter", url: "https://streamwriter.org/en/", tag: "Pobieracz Audio" },
            { name: "Tilderadio", url: "https://tilderadio.org/", tag: "Społeczność" },
            { name: "UpBeat", url: "https://upbeatradio.net/", tag: "Społeczność" },
            { name: "Vidbox Radio", url: "https://vidbox.to/radio" },
            { name: "You Radio", url: "https://play.you.radio/" },
            { name: "Zeno.fm", url: "https://zeno.fm/", tag: "Stacje Użytkowników" }
          ]
        }
      ]
    },
    {
      id: "podcasts",
      title: "🎙️ Podcasty (Streaming & Aplikacje)",
      links: [
        { name: "Apple Podcasts", url: "https://podcasts.apple.com/us/home" },
        { name: "BBC Podcasts", url: "https://www.bbc.co.uk/sounds/podcasts", tag: "Downloader" },
        { name: "castero", url: "https://github.com/xgi/castero", tag: "Klient TUI" },
        { name: "EchoWalk", url: "https://www.echowalk.com/", tag: "Artykuły na Podcasty" },
        { name: "GPodder", url: "https://gpodder.github.io/", tag: "Klient Podcastów" },
        { name: "Grover", url: "https://www.microsoft.com/store/productId/9NBLGGH6C4BC", tag: "Klient Podcastów" },
        { name: "Listen Notes", url: "https://www.listennotes.com/", tag: "Wyszukiwarka" },
        { name: "OpenPodcast", url: "https://openpodcast.dev", tag: "Analityka" },
        { name: "Player FM", url: "https://player.fm/" },
        { name: "Pocket Casts", url: "https://play.pocketcasts.com/discover", tag: "Aplikacja Desktopowa" },
        { name: "Podbay", url: "https://podbay.fm/" },
        { name: "Podbean", url: "https://www.podbean.com/" },
        { name: "Podchaser", url: "https://www.podchaser.com/charts", tag: "Listy/Bazy Danych" },
        { name: "PodClips", url: "https://podclips.com/", tag: "Klipki z Podcastów" },
        { name: "PodDL (Mirror)", url: "https://github.com/freshe/poddl" },
        { name: "PodFetch (Mirror)", url: "https://www.samtv.fyi/PodFetch/" },
        { name: "PodGrab", url: "https://github.com/akhilrex/podgrab", tag: "Self-Hosted" },
        { name: "podcast-dl", url: "https://github.com/lightpohl/podcast-dl", tag: "Downloader CLI" },
        { name: "PodcastBulkDownloader (Mirror)", url: "https://github.com/cnovel/PodcastBulkDownloader" },
        { name: "Podcast Index", url: "https://podcastindex.org/" },
        { name: "PodParadise", url: "https://www.podparadise.com/" },
        { name: "Podcast Republic", url: "https://www.podcastrepublic.net/" },
        { name: "PodScripts", url: "https://podscripts.co/", tag: "Wyszukiwanie Transkryptów" },
        { name: "Podstatus (Mirror)", url: "https://podstatus.com/charts" },
        { name: "PodSync", url: "https://github.com/mxpv/podsync", tag: "YT na Podcasty" },
        { name: "Relay.fm", url: "https://www.relay.fm/" },
        { name: "Rephonic", url: "https://rephonic.com/graph", tag: "Podobne Podcasty" },
        { name: "Spotify Podcasts", url: "https://open.spotify.com/browse/podcasts", tag: "Popularne" }
      ]
    },
    {
      id: "ambient-and-relaxation",
      title: "🎧 Muzyka Ambient & Relaksacyjna",
      links: [
        { name: "Ambie", url: "https://ambieapp.com/", tag: "Aplikacja Desktopowa" },
        { name: "Ambient Mixer", url: "https://www.ambient-mixer.com/", tag: "Tworzone przez Użytkowników" },
        { name: "Ambient Sleeping Pill", url: "https://ambientsleepingpill.com/" },
        { name: "ambiphone", url: "https://ambiph.one/", tag: "Mikser" },
        { name: "Ambicular", url: "https://ambicular.com/", tag: "Radio Lofi" },
        { name: "Calmsound (Mirror)", url: "https://www.calmsound.com/" },
        { name: "CanvasCycle", url: "http://www.effectgames.com/demos/canvascycle/", tag: "Sceny 8-bitowe" },
        { name: "Chillhop", url: "https://chillhop.com/", tag: "Radio Lofi" },
        { name: "ChillOuts", url: "http://www.chillouts.com/", tag: "Pomoc w Medytacji" },
        { name: "CityHop", url: "https://www.cityhop.cafe/", tag: "Radio Lofi / Spacery po Mieście" },
        { name: "Click Bath", url: "https://hamishlang.github.io/clickbath/", tag: "Mikser ze Skalą" },
        { name: "Click Relax (Mirror)", url: "https://click-relax.com/" },
        { name: "Coding Cat", url: "https://hostrider.com/", tag: "Radio Lofi" },
        { name: "DevTunes FM", url: "https://radio.madza.dev/" },
        { name: "Drone Zone", url: "https://somafm.com/player/#/now-playing/dronezone", tag: "Ambient" },
        { name: "Earth.fm", url: "https://earth.fm/", tag: "Nagrania Terenowe" },
        { name: "Flow-fi", url: "https://www.flowfi.app/", tag: "Radio Lofi / 360+ Kanałów" },
        { name: "FlowTunes", url: "https://www.flowtunes.app/", tag: "Lofi + Skupienie" },
        { name: "FreeCodeCamp", url: "https://coderadio.freecodecamp.org/", tag: "Radio Lofi" },
        { name: "Generative.fm", url: "https://generative.fm/", tag: "Muzyka Generatywna" },
        { name: "HaloMe", url: "https://halome.nu/", tag: "Ekrany Menu Halo" },
        { name: "Homesick", url: "https://scoreascore.com/homesick", tag: "Dźwięki Domu" },
        { name: "IMissTheOffice", url: "https://imisstheoffice.eu/", tag: "Dźwięki Biura" },
        { name: "imissmycafe", url: "https://imissmycafe.com/", tag: "Dźwięki Kawiarni" },
        { name: "Japan Walkaround (Mirror)", url: "https://thatguyedd.github.io/" },
        { name: "Lofi and Games", url: "https://lofiandgames.com/", tag: "Lofi + Gry" },
        { name: "Lofi Generator (Mirror)", url: "https://lofigenerator.com/" },
        { name: "Lofi Limo", url: "https://lofi.limo/" },
        { name: "LofiCafe", url: "https://www.loficafe.net/" },
        { name: "LofiClub", url: "https://loficlub.vercel.app/" },
        { name: "Lofizen", url: "https://www.lofizen.co/", tag: "Lofi/Ambient" },
        { name: "lofi-player", url: "https://magenta.tensorflow.org/lofi-player", tag: "Stwórz Pokój" },
        { name: "Loofi", url: "https://loofi.netlify.app/" },
        { name: "Moodist (Mirror)", url: "https://moodist.app/" },
        { name: "Moon Phase Radio", url: "https://www.moonphaseradio.com/", tag: "Radio Lofi" },
        { name: "Moss Garden", url: "https://moss.garden/" },
        { name: "Moszen (Mirror)", url: "https://www.moszen.com/" },
        { name: "Music For Programming", url: "https://musicforprogramming.net/latest/", tag: "Playlisty do Skupienia" },
        { name: "myNoise", url: "https://mynoise.net/", tag: "Dostosowywalny Mikser" },
        { name: "NoisyLoop (Mirror)", url: "https://noisyloop.com/" },
        { name: "Pluvior (Mirror)", url: "https://pluvior.com/" },
        { name: "Rainbow Hunt", url: "https://rainbowhunt.com/", tag: "Deszcz Ambientowy" },
        { name: "Rainy Mood", url: "https://www.rainymood.com/", tag: "Deszcz Ambientowy" },
        { name: "Rainyscope (Mirror)", url: "https://rainyscope.com/" },
        { name: "Relaxing Sounds", url: "https://unifycosmos.com/relaxing-sounds/", tag: "Pejzaże Dźwiękowe" },
        { name: "Sounds of Maine (Mirror)", url: "https://soundsofmaine.life/" },
        { name: "TheWhiteNoiseMachine", url: "https://thewhitenoisemachine.com/", tag: "Biały Szum" },
        { name: "tree.fm (Mirror)", url: "https://www.tree.fm/" },
        { name: "VirtOcean", url: "https://virtocean.com/", tag: "Dźwięki Oceanu" },
        { name: "Wisdom Tree", url: "https://github.com/HACKER097/wisdom-tree/", tag: "Aplikacja TUI" },
        { name: "You are Listening To LA", url: "https://youarelistening.to/", tag: "Dźwięki Miasta" },
        { name: "Zen Sounds (Mirror)", url: "https://app.zenflowchart.com/zen-sounds" }
      ]
    },
    {
      id: "soundtracks",
      title: "🎮 Soundtracki (Gry, Filmy, Anime)",
      subsections: [
        {
          title: "Game Soundtracks",
          links: [
            { name: "8Beats", url: "https://8beats.co/", tag: "Radio z Muzyką z Gier" },
            { name: "Animal Crossing Radio", url: "https://animal-crossing-radio.com/" },
            { name: "Chip Player JS", url: "https://chiptune.app/", tag: "Odtwarzacz Web" },
            { name: "Cirrus Retro", url: "https://cirrusretro.com/", tag: "Radio z Muzyką z Gier" },
            { name: "exotica", url: "https://www.exotica.org.uk/", tag: "OST z Amigi" },
            { name: "Exotica (Wiki)", url: "https://www.exotica.org.uk/", tag: "Muzyka z Gier Retro" },
            { name: "GameOST", url: "https://gameost.net/", tag: "MP3" },
            { name: "Goldenrod Radio", url: "https://www.youtube.com/@GoldenrodRadio251", tag: "Muzyka z Pokémon" },
            { name: "GTA Radio Stations Music", url: "https://rentry.co/FMHYBase64#gta-radio-stations" },
            { name: "HCS Forum", url: "https://rentry.co/FMHYBase64#hcs-forum", tag: "Soundtracki z Gier" },
            { name: "HVSC", url: "https://www.hvsc.c64.org/", tag: "Muzyka z Commodore 64" },
            { name: "JetSetRadio", url: "https://jetsetradio.live/", tag: "Radio z Muzyką z Gier" },
            { name: "Khinsider", url: "https://downloads.khinsider.com/", tag: "MP3/FLAC/ALAC" },
            { name: "NSF j", url: "https://nsf.nesbbs.com/", tag: "Muzyka z NES" },
            { name: "OC Remix", url: "https://ocremix.org/", tag: "Remiksy" },
            { name: "Rainwave", url: "https://rainwave.cc/", tag: "Radio z Muzyką z Gier" },
            { name: "RetroTracks", url: "https://retro.sx/", tag: "OST z Gier Retro" },
            { name: "RPGGamers Radio", url: "http://www.rpgamers.net/radio/", tag: "Radio z Muzyką z Gier" },
            { name: "VGM", url: "https://vgm.mmosvc.com/", tag: "Radio z Muzyką z Gier" },
            { name: "VGMdb", url: "https://vgmdb.net/", tag: "Baza Danych" },
            { name: "VGMPF", url: "https://www.vgmpf.com/Wiki/index.php", tag: "OST z Gier Retro" },
            { name: "VGMRadio", url: "https://vgmradio.com/", tag: "Radio z Muzyką z Gier" },
            { name: "VGMRips", url: "https://vgmrips.net/packs/", tag: "Ripy Retro" },
            { name: "VIP VGM", url: "https://www.vipvgm.net/", tag: "Radio z Muzyką z Gier" },
            { name: "Zophar's", url: "https://www.zophar.net/music", tag: "Ripy Retro" }
          ]
        },
        {
          title: "Anime & Film Soundtracks",
          links: [
            { name: "3ost", url: "https://3ost.ru/", tag: "Soundtracki" },
            { name: "AMV", url: "https://www.animemusicvideos.org/", tag: "Anime Music Videos" },
            { name: "Anime Sharing", url: "https://koe.anime-sharing.com/", tag: "OST z Anime" },
            { name: "AniPlaylist", url: "https://aniplaylist.com/", tag: "OST z Anime" },
            { name: "DoujinStyle", url: "https://doujinstyle.com/", tag: "Muzyka Doujin" },
            { name: "FilmMusicSite", url: "https://www.filmmusicsite.com/en/", tag: "Baza Danych" },
            { name: "joshw", url: "https://pc.joshw.info/", tag: "Soundtracki" },
            { name: "KDramaOST", url: "https://kdramaost.com/en/", tag: "Soundtracki z KDram" },
            { name: "MusicDex", url: "https://musicdex.org/", tag: "OST z Anime" },
            { name: "OSAnime", url: "https://osanime.com/", tag: "OST z Anime" },
            { name: "OtakuOst", url: "https://otakuost.net/", tag: "Muzyka z Anime/Japońska" },
            { name: "RenovationRecords", url: "https://renovatiorecords.blogspot.com/", tag: "OST z Filmów HQ" },
            { name: "SakuraOST", url: "https://www.sakuraost.com/", tag: "OST z Anime" },
            { name: "Sitting on Clouds", url: "https://www.sittingonclouds.net/", tag: "OST z Anime/Gier" },
            { name: "Sitting on Clouds COM (Mirror)", url: "https://sittingonclouds.com/" },
            { name: "SoundtrackTracklist", url: "https://soundtracktracklist.com/", tag: "Baza Danych" },
            { name: "Squidify", url: "https://www.squidify.org", tag: "OST z Gier/Anime" },
            { name: "Squidify NET (Mirror)", url: "https://www.squidify.net/" }
          ]
        }
      ]
    },
    {
      id: "tracking-and-databases",
      title: "📊 Śledzenie & Bazy Danych Muzyki",
      links: [
        { name: "Brew.fm (Mirror)", url: "https://www.brew.fm/" },
        { name: "Discogs", url: "https://www.discogs.com/", tag: "Oceny/Recenzje/Baza Danych" },
        { name: "Drop Watch (Mirror)", url: "https://drop-watch.ghost.io/" },
        { name: "Has it Leaked", url: "https://hasitleaked.com/", tag: "Śledzenie Wycieków Albumów" },
        { name: "Last.fm", url: "https://www.last.fm/home", tag: "Śledzenie Nawyków" },
        { name: "libib", url: "https://www.libib.com/", tag: "Katalog Mediów Desktopowych" },
        { name: "ListenBrainz", url: "https://listenbrainz.org/", tag: "Scrobbler Open Source" },
        { name: "Maloja", url: "https://maloja.krateng.ch", tag: "Scrobbling Self-Hosted" },
        { name: "MediaTracker", url: "https://github.com/bonukai/MediaTracker", tag: "Self-Hosted" },
        { name: "Multi Scrobbler (Mirror)", url: "https://github.com/FoxxMD/multi-scrobbler" },
        { name: "Music Board", url: "https://musicboard.app/", tag: "Oceny/Recenzje" },
        { name: "MusicButler (Mirror)", url: "https://www.musicbutler.io/" },
        { name: "Muspy", url: "https://muspy.com/", tag: "Aktualizacje Wydań Albumów" },
        { name: "MyPitchFork", url: "https://mypitchfork.fun/", tag: "Ocenianie/Śledzenie Piosenek" },
        { name: "rate.house", url: "https://rate.house/", tag: "Śledzenie Mediów" },
        { name: "RateYourMusic", url: "https://rateyourmusic.com/", tag: "Oceny/Recenzje" },
        { name: "TuneMyMusic", url: "https://www.tunemymusic.com/", tag: "Transfer Playlist" }
      ]
    },
    {
      id: "discovery-and-recommendations",
      title: "💖 Odkrywanie Muzyki i Rekomendacje",
      subsections: [
        {
          title: "Indeksy & Listy",
          links: [
            { name: "1001 Albums Generator", url: "https://1001albumsgenerator.com/" },
            { name: "45Cat", url: "https://www.45cat.com/", tag: "Oceny Winylowe" },
            { name: "Acclaimed Music", url: "https://www.acclaimedmusic.net/", tag: "Odkrywaj Uznane" },
            { name: "AlbumOfTheYear", url: "https://www.albumoftheyear.org/", tag: "Oceny/Recenzje" },
            { name: "AllMusic", url: "https://www.allmusic.com/", tag: "Oceny/Recenzje" },
            { name: "AME", url: "https://gitlab.com/SuperSaltyGamer/ame", tag: "Userscripty Ulepszające" },
            { name: "AnyDecentMusic", url: "http://www.anydecentmusic.com/", tag: "Agregator Recenzji Albumów" },
            { name: "Best Ever Albums", url: "https://www.besteveralbums.com/index.php", tag: "Odkrywaj Albumy" },
            { name: "Charts and Culture", url: "https://pastebin.com/uRDJVGkL", tag: "Katalog" },
            { name: "ClassicRockHistory", url: "https://www.classicrockhistory.com/classic-rock-bands-list-and-directory/", tag: "Archiwum Zespołów" },
            { name: "DAHR", url: "https://adp.library.ucsb.edu/index.php", tag: "Nagrania Historyczne" },
            { name: "dbkpop", url: "https://dbkpop.com/", tag: "Baza Danych K-Pop" },
            { name: "DigitalDreamDoor", url: "https://digitaldreamdoor.com/", tag: "Listy 100 Najlepszych" },
            { name: "EveryNoise", url: "https://everynoise.com/", tag: "Odkrywaj Gatunki" },
            { name: "generasia", url: "https://www.generasia.com/", tag: "Wiki o Muzyce Azjatyckiej" },
            { name: "HappyHardcore", url: "https://www.happyhardcore.com/forums/", tag: "Forum" },
            { name: "IDM Discovery", url: "https://www.idmdiscovery.com/", tag: "Archiwum Artystów IDM" },
            { name: "Identifying Music Genres", url: "https://chunisama.github.io/Identifying-Music-Genres/" },
            { name: "KPop Fandom (Mirror)", url: "https://kpop.fandom.com/wiki/" },
            { name: "KPopping (Mirror)", url: "https://kpopping.com/" },
            { name: "Kworb", url: "https://kworb.net/", tag: "Listy Przebojów" },
            { name: "Loudness War", url: "https://dr.loudness-war.info/", tag: "Baza Zakresu Dynamicznego" },
            { name: "Map of Metal", url: "https://mapofmetal.com/", tag: "Historia Metalu" },
            { name: "Metal Archives", url: "https://www.metal-archives.com/", tag: "Archiwum Zespołów Metalowych" },
            { name: "Music Chart Maker", url: "https://musicchartmaker.com/", tag: "Kolaże z Albumów" },
            { name: "Music Discovery (Mirror)", url: "https://rentry.co/musicdiscovery" },
            { name: "Music Discovery Guide", url: "https://dan.valeena.dev/guides/music-discovery/", tag: "Przewodnik" },
            { name: "Music.ishkur", url: "https://music.ishkur.com/", tag: "Przewodnik po Elektronice" },
            { name: "MusicBrainz", url: "https://musicbrainz.org/", tag: "Oceny/Recenzje" },
            { name: "MusicGenreTree", url: "https://www.musicgenretree.org/chart.html", tag: "Odkrywaj po Gatunku" },
            { name: "Musicmap", url: "https://musicmap.info/", tag: "Historia Gatunków" },
            { name: "MusicTo", url: "https://www.musicto.com/", tag: "Kuratorowane przez Muzyków" },
            { name: "MusicTaste (Mirror)", url: "https://musictaste.space/" },
            { name: "Obscurify", url: "https://obscurifymusic.com/", tag: "Porównaj Gust" },
            { name: "OrbitMusic", url: "https://www.bbc.co.uk/orbitmusic", tag: "Nieodkryci Artyści" },
            { name: "r/ifyoulikeblank", url: "https://www.reddit.com/r/ifyoulikeblank/", tag: "Rekomendacje Artystów" },
            { name: "Random Song", url: "https://randomsong.org/", tag: "Losowe Piosenki z YT" },
            { name: "Random Song Generator (Mirror)", url: "https://randomsonggenerator.com/" },
            { name: "RemixSearch (Mirror)", url: "https://remixsearch.net/" },
            { name: "RYM Ultimate Box Set", url: "https://rateyourmusic.com/list/TheScientist/rym-ultimate-box-set/", tag: "Artysta wg Gatunku" },
            { name: "Samplette (Mirror)", url: "https://samplette.io/" },
            { name: "SecondHandSongs", url: "https://secondhandsongs.com/", tag: "Baza Coverów/Remixów" },
            { name: "Shfl", url: "https://theshfl.com/", tag: "Rekomendacje Albumów" },
            { name: "Spoqify", url: "https://spoqify.com/", tag: "Anonimowe Playlisty" },
            { name: "Spotify Charts (Mirror)", url: "https://charts.spotify.com/home" },
            { name: "Sputnik", url: "https://www.sputnikmusic.com/", tag: "Oceny/Recenzje" },
            { name: "Stage48 (Mirror)", url: "http://stage48.net/wiki/index.php/Main_Page" },
            { name: "SuperFridayChart (Mirror)", url: "https://www.superfridaychart.com/" },
            { name: "TheIndieRockPlaylist", url: "https://www.theindierockplaylist.com/", tag: "Archiwum Indie Rocka" },
            { name: "This Is What You Listen To", url: "https://tiwylt.musimap.io/", tag: "Analizator Gatunków" },
            { name: "TranceFix", url: "https://www.trancefix.nl/index.php", tag: "Forum" },
            { name: "Tunefind", url: "https://www.tunefind.com/", tag: "Muzyka z Filmów/Seriali" },
            { name: "WhoSampled (Mirror)", url: "https://www.whosampled.com/" }
          ]
        },
        {
          title: "Bazy Danych DJ Setów",
          links: [
            { name: "1001Tracklists (Mirror)", url: "https://www.1001tracklists.com/" },
            { name: "MixesDB", url: "https://www.mixesdb.com/", tag: "Baza Danych Setów DJ" },
            { name: "TrackID", url: "https://trackid.net/", tag: "Tracklisty z Setów na Żywo" }
          ]
        }
      ]
    },
    {
      id: "last-fm-tools",
      title: "📊 Last.fm - Narzędzia i Statystyki",
      links: [
        { name: "Awesome Spotify Stats", url: "https://github.com/hugo9655/awesome-spotify-stats", tag: "Indeks Statystyk" },
        { name: "bleh", url: "https://katelyn.moe/bleh/", tag: "Skrypt do Personalizacji" },
        { name: "Chart My Music", url: "https://www.chartmymusic.com/lastfm/", tag: "Kolaże z Albumów" },
        { name: "Decent.live", url: "https://descent.live/", tag: "Narzędzie 'Teraz Odtwarzane'" },
        { name: "Edit Scrobbles", url: "https://greasyfork.org/en/scripts/485278", tag: "Ręczna Edycja" },
        { name: "Last.fm Iceberg", url: "https://lastfm-iceberg.dawdle.space/" },
        { name: "Last.fm Labs", url: "https://www.last.fm/labs", tag: "Wizualizatory" },
        { name: "Last.fm Stats", url: "https://lastfmstats.com/", tag: "Dogłębne Statystyki" },
        { name: "Last.fm Tool List (Wiki)", url: "https://www.reddit.com/r/FREEMEDIAHECKYEAH/wiki/audio/#wiki_.25B7_last.fm_tools" },
        { name: "Mainstream Calc", url: "http://mainstream.ghan.nl/", tag: "Kalkulator" },
        { name: "MusicCoruMap (Mirror)", url: "https://musicorumapp.com/generate" },
        { name: "OpenScrobbler", url: "https://openscrobbler.com/", tag: "Ręczny Scrobble" },
        { name: "Pano Scrobbler", url: "https://github.com/kawaiiDango/pano-scrobbler", tag: "Multi-Platform" },
        { name: "RYM-Last.fm Stats", url: "https://github.com/dukhevych/rym-lastfm-stats", tag: "Integracja" },
        { name: "TagCloud", url: "https://tagcloud.rainosullivan.com/", tag: "Wizualizator Tagów" },
        { name: "TapMusic (Mirror)", url: "https://www.tapmusic.net/" },
        { name: "Web Scrobbler", url: "https://github.com/web-scrobbler/web-scrobbler", tag: "Scrobbluj Każdą Stronę" }
      ]
    },
    {
      id: "general-audio-tools",
      title: "🛠️ Ogólne Narzędzia Audio",
      subsections: [
        {
          title: "Konwertery i Uniwersalne Narzędzia",
          links: [
            { name: "Audio Glossary", url: "https://wotaku.wiki/glossary/audio", tag: "Terminy Audio" },
            { name: "AudioMarx", url: "https://audiomarx.mixa.site/", tag: "Zasoby Audio" },
            { name: "AudioToolSet (Mirror)", url: "https://audiotoolset.com/" },
            { name: "Binaural Audio", url: "https://binaural-audio.slite.page/p/i38zsD7728/Binaural-Audio", tag: "Audio 3D" },
            { name: "FFmpeg", url: "https://ffmpeg.org/", tag: "Uniwersalny CLI" },
            { name: "FlicFlac", url: "https://github.com/DannyBen/FlicFlac", tag: "Konwerter Audio" },
            { name: "fre:ac", url: "https://www.freac.org/", tag: "Konwerter Audio" },
            { name: "fre:ac GitHub (Mirror)", url: "https://github.com/enzo1982/freac" },
            { name: "Hydrogenaudio", url: "https://wiki.hydrogenaud.io/", tag: "Audio Wiki" },
            { name: "Karaoke Mugen", url: "https://mugen.karaokes.moe/en/", tag: "Aplikacja Karaoke" },
            { name: "LameXP", url: "https://sourceforge.net/projects/lamexp/", tag: "Konwerter Audio" },
            { name: "Librescore Downloader", url: "https://github.com/LibreScore/dl-librescore" },
            { name: "LRC Maker (Mirror)", url: "https://lrcmaker.com/" },
            { name: "M3Unator", url: "https://github.com/hasanbeder/M3Unator", tag: "Generuj M3U" },
            { name: "Phiola", url: "https://github.com/stsaz/phiola", tag: "Wielofunkcyjne Narzędzie Audio" },
            { name: "QO & SPECTRE (Mirror)", url: "https://docs.google.com/spreadsheets/u/0/d/1QEvWoGa10BctJ1yqDgZl3IoY8bhB3AwbHzgCHjJ5neI/htmlview" },
            { name: "Safeaudiokit (Mirror)", url: "https://safeaudiokit.com/" },
            { name: "Sox", url: "https://sourceforge.net/projects/sox/", tag: "Konwerter Audio" },
            { name: "Tunebat", url: "https://tunebat.com/", tag: "Baza Tonacji/BPM" },
            { name: "VB Cables", url: "https://rentry.co/FMHYBase64#vb-cables", tag: "Wirtualne Kable Audio" },
            { name: "Vocaroo", url: "https://vocaroo.com/", tag: "Rejestrator Głosu Online" },
            { name: "X-Minus", url: "https://x-minus.pro/", tag: "Twórz Karaoke" }
          ]
        },
        {
          title: "Odtwarzacze Audio",
          links: [
            { name: "AIMP", url: "https://www.aimp.ru/", tag: "Nowoczesny Odtwarzacz" },
            { name: "Audacious", url: "https://audacious-media-player.org/" },
            { name: "Butterchurn Visualizer", url: "https://butterchurnviz.com/" },
            { name: "CatNip (Mirror)", url: "https://github.com/noriah/catnip" },
            { name: "deadbeef", url: "https://deadbeef.sourceforge.io/" },
            { name: "Dopamine", url: "https://digimezzo.github.io/site/" },
            { name: "Exaile", url: "https://exaile.org/" },
            { name: "Feishin", url: "https://github.com/jeffvli/feishin", tag: "Jellyfin/Subsonic" },
            { name: "Foobar2000", url: "https://www.foobar2000.org/", tag: "Wysoce Konfigurowalny" },
            { name: "Harmonoid", url: "https://harmonoid.com/", tag: "Bogaty w Funkcje" },
            { name: "LedFx", url: "https://www.ledfx.app/", tag: "Synchronizacja Muzyki z LED" },
            { name: "Museeks", url: "https://museeks.io/" },
            { name: "MusicBee", url: "https://getmusicbee.com/", tag: "Menedżer Biblioteki" },
            { name: "MusikCube", url: "https://musikcube.com/", tag: "Oparty na Terminalu" },
            { name: "MusicVid (Mirror)", url: "https://musicvid.org/" },
            { name: "Namida (Mirror)", url: "https://github.com/namidaco/namida" },
            { name: "NCurses++", url: "https://github.com/ncmpcpp/ncmpcpp", tag: "Klient Terminalowy" },
            { name: "Nora", url: "https://noramusic.netlify.app/", tag: "Nowoczesny Odtwarzacz" },
            { name: "PartyEngine", url: "https://aggrocrab.itch.io/partyengine", tag: "Wizualizator Imprezowy" },
            { name: "quodlibet", url: "https://github.com/quodlibet/quodlibet/" },
            { name: "RockBox", url: "https://www.rockbox.org/", tag: "Niestandardowe FW Odtwarzacza" },
            { name: "Strawberry", url: "https://www.strawberrymusicplayer.org/" },
            { name: "Swing", url: "https://swingmx.com/", tag: "Web UI" },
            { name: "TimeStetch", url: "https://29a.ch/timestretch/", tag: "Oparty na Przeglądarce" },
            { name: "VinylEngine", url: "https://www.vinylengine.com/", tag: "Informacje o Gramofonach" },
            { name: "Vizzy (Mirror)", url: "https://vizzy.io/" },
            { name: "WACUP", url: "https://getwacup.com/", tag: "Fork Winampa" },
            { name: "XMPlay", url: "https://www.un4seen.com/", tag: "Przyjazny dla Modułów" }
          ]
        },
        {
          title: "Serwery Audio",
          links: [
            { name: "Airsonic", url: "https://airsonic.github.io/", tag: "Serwer Muzyczny" },
            { name: "Airsonic Advanced (Mirror)", url: "https://github.com/airsonic-advanced/airsonic-advanced" },
            { name: "Ampache", url: "https://ampache.org/", tag: "Serwer Muzyczny" },
            { name: "AudioRelay", url: "https://audiorelay.net/", tag: "Strumieniowanie Między Urządzeniami" },
            { name: "Black Candy", url: "https://github.com/blackcandy-org/blackcandy", tag: "Serwer Muzyczny" },
            { name: "Gonic", url: "https://github.com/sentriz/gonic", tag: "Serwer Muzyczny" },
            { name: "iBroadcast", url: "https://ibroadcast.com", tag: "Przechowywanie Muzyki w Chmurze" },
            { name: "koel", url: "https://koel.dev/", tag: "Serwer Muzyczny" },
            { name: "Lyrion", url: "https://lyrion.org/", tag: "Serwer Muzyczny" },
            { name: "Mopidy", url: "https://mopidy.com/", tag: "Serwer Muzyczny" },
            { name: "mStream", url: "https://mstream.io/", tag: "Serwer Muzyczny" },
            { name: "Music Player Daemon", url: "https://www.musicpd.org/" },
            { name: "Navidrome", url: "https://navidrome.org", tag: "Serwer Muzyczny" },
            { name: "Polaris", url: "https://github.com/agersant/polaris", tag: "Serwer Muzyczny" },
            { name: "SnapCast", url: "https://github.com/badaix/snapcast", tag: "Synchronizacja Systemu Dźwiękowego" },
            { name: "SonoBus", url: "https://sonobus.net/", tag: "Synchronizacja Systemu Dźwiękowego" },
            { name: "SynchronousAudioRouter", url: "https://github.com/eiz/SynchronousAudioRouter" }
          ]
        },
        {
          title: "Metadane Audio",
          links: [
            { name: "Beets", url: "https://beets.io/", tag: "Organizator Metadanych" },
            { name: "Imploded", url: "https://www.imploded.com/", tag: "Organizator Metadanych" },
            { name: "Kid3", url: "https://kid3.kde.org/", tag: "Organizator Metadanych" },
            { name: "MetaTogger", url: "https://luminescence-software.org/en/metatogger/about/", tag: "Organizator Metadanych" },
            { name: "MP3Tag", url: "https://www.mp3tag.de/en/", tag: "Organizator Metadanych" },
            { name: "MusicBrainz Picard", url: "https://picard.musicbrainz.org/", tag: "Automatyczne Tagowanie" },
            { name: "TagEditor", url: "https://github.com/Martchus/tageditor" },
            { name: "TagScanner", url: "https://www.xdlab.ru/en/", tag: "Organizator Metadanych" },
            { name: "tone (Mirror)", url: "https://github.com/sandreas/tone" },
            { name: "YADG", url: "https://yadg.cc/", tag: "Pobieranie Informacji o Wydaniu" }
          ]
        },
        {
          title: "Okładki Albumów",
          links: [
            { name: "Album Art Downloader", url: "https://sourceforge.net/projects/album-art/", tag: "Aplikacja Desktopowa" },
            { name: "Albumart.Digital (Mirror)", url: "https://albumart.digital/" },
            { name: "Apple Artwork", url: "https://artwork.thekvt.eu.org/", tag: "Okładki z Apple Music" },
            { name: "bigpictures (Mirror)", url: "https://bigpictures.xyz/" },
            { name: "Classic Rock Covers", url: "https://www.classic-rock-covers.com/" },
            { name: "Cover Search Engine", url: "https://covers.musichoarders.xyz", tag: "Wyszukiwarka Okładek" },
            { name: "Fetcher (Mirror)", url: "https://github.com/bunnykek/Fetcher" },
            { name: "kunst (Mirror)", url: "https://github.com/sdushantha/kunst" },
            { name: "MediUX Album Covers", url: "https://mediux.pro/albums", tag: "Okładki Soundtracków" },
            { name: "SpotifyArt", url: "https://spotify-art.vercel.app/", tag: "Okładki z Spotify" },
            { name: "spotifycover.art (Mirror)", url: "https://www.spotifycover.art/" }
          ]
        },
        {
          title: "Identyfikacja Utworów",
          links: [
            { name: "AHA Music", url: "https://www.aha-music.com/identify-songs-music-recognition-online", tag: "Rozszerzenie Chrome" },
            { name: "AmbientMusicMod", url: "https://github.com/KieronQuinn/AmbientMusicMod", tag: "Android" },
            { name: "Audile", url: "https://github.com/aleksey-saenko/MusicRecognizer", tag: "Android" },
            { name: "Audire", url: "https://github.com/alexmercerind/audire", tag: "Android" },
            { name: "AudioTag", url: "https://audiotag.info/", tag: "Web" },
            { name: "FlairMax", url: "https://apps.microsoft.com/detail/9pdzvj34ztxg", tag: "Aplikacja Windows" },
            { name: "Google Assistant", url: "https://assistant.google.com/", tag: "Rozpoznawanie Muzyki" },
            { name: "Librezam", url: "https://addons.mozilla.org/en-US/firefox/addon/librezam/", tag: "Rozszerzenie Shazam dla Firefox" },
            { name: "r/NameThatSong (Mirror)", url: "https://reddit.com/r/NameThatSong" },
            { name: "SampleSeek", url: "https://www.sampleseek.co.uk/", tag: "Znajdź Sample" },
            { name: "Shazam", url: "https://www.shazam.com/", tag: "Mobilne/Rozszerzenie Desktopowe" },
            { name: "Shazam Chrome (Mirror)", url: "https://chromewebstore.google.com/detail/shazam-find-song-names-fr/mmioliijnhnoblpgimnlajmefafdfilb" },
            { name: "SoundHound", url: "https://www.soundhound.com/soundhound", tag: "Android" },
            { name: "Vibra", url: "https://github.com/BayernMuller/vibra", tag: "Aplikacja Desktopowa Shazam" },
            { name: "WatZatSong", url: "https://www.watzatsong.com/en", tag: "Identyfikacja przez Społeczność" },
            { name: "WhatAmIHearing (Mirror)", url: "https://github.com/zemoto/WhatAmIHearing" }
          ]
        },
        {
          title: "Strony z Tekstami Piosenek",
          links: [
            { name: "AZLyrics", url: "https://www.azlyrics.com/", tag: "Wyszukiwarka Tekstów" },
            { name: "dumb", url: "https://github.com/rramiachraf/dumb", tag: "Wyjaśnienia Tekstów" },
            { name: "FindMusicByLyrics (Mirror)", url: "https://findmusicbylyrics.com/" },
            { name: "Genius", url: "https://genius.com/", tag: "Wyjaśnienia Tekstów" },
            { name: "Intellectual (Mirror)", url: "https://intellectual.insprill.net/" },
            { name: "LRCGET", url: "https://github.com/tranxuanthang/lrcget", tag: "Pobieranie Zsynchronizowanych Tekstów" },
            { name: "LRCLIB", url: "https://lrclib.net/", tag: "Wyszukiwarka Zsynchronizowanych Tekstów" },
            { name: "Lyrical Nonsense", url: "https://www.lyrical-nonsense.com/global/", tag: "Teksty Japońskie" },
            { name: "Lyricify", url: "https://github.com/WXRIW/Lyricify-App", tag: "Aplikacja Desktopowa" },
            { name: "Lyrics-In-Terminal (Mirror)", url: "https://github.com/Jugran/lyrics-in-terminal" },
            { name: "Lyrics.com (Mirror)", url: "https://www.lyrics.com/" },
            { name: "Lyricsify (Mirror)", url: "https://www.lyricsify.com/" },
            { name: "LyricsTranslate", url: "https://lyricstranslate.com/", tag: "Tłumacz Tekstów" },
            { name: "Versefy", url: "https://versefy.app/", tag: "Wyszukiwarka Tekstów" }
          ]
        },
        {
          title: "Nuty & Tabulatury",
          links: [
            { name: "Audiveris", url: "https://audiveris.github.io/audiveris/_pages/handbook/", tag: "Silnik OMR" },
            { name: "Chordly", url: "https://chordly.co.uk/", tag: "Kreator Akordów" },
            { name: "MC Musiceditor", url: "https://www.mcmusiceditor.com/", tag: "Oprogramowanie do Notacji" },
            { name: "music-reader", url: "https://music-reader.com/", tag: "Ćwiczenie Czytania" },
            { name: "MuseScore", url: "https://musescore.org/", tag: "Oprogramowanie do Notacji" },
            { name: "Nootka (Mirror)", url: "https://sourceforge.net/projects/nootka/" },
            { name: "Nutkus", url: "https://sourceforge.net/projects/nutkus/", tag: "Gra Edukacyjna" },
            { name: "Oemer", url: "https://github.com/BreezeWhite/oemer", tag: "Narzędzie OMR" },
            { name: "Omnizart", url: "https://github.com/Music-and-Culture-Technology-Lab/omnizart", tag: "Transkrypcja Muzyki" },
            { name: "Piascore", url: "https://apps.apple.com/app/piascore-hd/id406141702", tag: "Przeglądarka Nut na iOS" },
            { name: "r/sheetmusic", url: "https://reddit.com/r/sheetmusic", tag: "Społeczność" },
            { name: "Score Perfect Professional", url: "https://archive.org/details/score-perfect-professional-lite-5.1/", tag: "Oprogramowanie do Notacji" },
            { name: "Sheet Music Scanner", url: "https://sheetmusicscanner.com/", tag: "Mobilne OMR" },
            { name: "Sheethost", url: "https://sheet.host/", tag: "Publikowanie Nut" },
            { name: "Sound Slice", url: "https://soundslice.com/", tag: "Nauka z Nut" },
            { name: "The ABC Music Project", url: "https://abc.sourceforge.net/", tag: "Język Notacji" },
            { name: "VGLeadSheets", url: "https://www.vgleadsheets.com/", tag: "Muzyka z Gier Wideo" }
          ]
        },
        {
          title: "Analizatory Spektrum",
          links: [
            { name: "Audio Quality Check Guide", url: "https://redd.it/3l0yxp" },
            { name: "Cambia", url: "https://logs.musichoarders.xyz/", tag: "Sprawdzanie Logów Ripów CD" },
            { name: "Comparison of Audio Compression", url: "https://nigelcoldwell.co.uk/audio/" },
            { name: "Fakin' The Funk?", url: "https://fakinthefunk.net/", tag: "Sprawdzanie Jakości" },
            { name: "Friture", url: "https://friture.org/", tag: "Analizator" },
            { name: "Sonic Visualizer", url: "https://www.sonicvisualiser.org/", tag: "Analizator" },
            { name: "Spek", url: "https://www.spek.cc/", tag: "Analizator Widma" },
            { name: "Spectro (Mirror)", url: "http://spectro.enpts.com/" },
            { name: "Visual Analyser", url: "https://www.sillanumsoft.org/" },
            { name: "WhatsMyBitrate", url: "https://whatsmybitrate.com/", tag: "Sprawdzanie Bitrate" }
          ]
        },
        {
          title: "Edytory Audio (DAW & Trackery)",
          links: [
            { name: "16-Bits", url: "https://16-bits.org/", tag: "Tracker Muzyczny" },
            { name: "Ariamaestosa (Mirror)", url: "https://ariamaestosa.github.io/ariamaestosa/docs/index.html" },
            { name: "Audacity (Mirror)", url: "https://www.audacityteam.org/" },
            { name: "AudioZ (Mirror)", url: "https://audioz.download/" },
            { name: "Basic Pitch", url: "https://basicpitch.spotify.com/", tag: "Audio-do-MIDI" },
            { name: "Bespoke", url: "https://www.bespokesynth.com/", tag: "Modularne Audio" },
            { name: "Element", url: "https://kushview.net/element/", tag: "Modularne Audio" },
            { name: "Fadr", url: "https://fadr.com/", tag: "Kreator/Edytor STEM" },
            { name: "FamiStudio", url: "https://famistudio.org/", tag: "Edytor Audio NES" },
            { name: "FL Studio", url: "https://rentry.co/FMHYBase64#fl-studio", tag: "DAW" },
            { name: "Furnace", url: "https://tildearrow.org/furnace/", tag: "Tracker Muzyczny" },
            { name: "G-MEH (Mirror)", url: "https://g-meh.com/" },
            { name: "LittleSoundDJ", url: "https://www.littlesounddj.com/lsd/index.php", tag: "Edytor Game Boy" },
            { name: "LMMS", url: "https://lmms.io/", tag: "Darmowy DAW" },
            { name: "MilkyTracker (Mirror)", url: "https://milkytracker.org/" },
            { name: "Mixxx", url: "https://mixxx.org/", tag: "Oprogramowanie DJ" },
            { name: "Mod Archive", url: "https://modarchive.org/", tag: "Moduły Audio" },
            { name: "Moises", url: "https://moises.ai/", tag: "Mikser Muzyki na Żywo" },
            { name: "Music Experiment", url: "https://petersalomonsen.com/webassemblymusic/livecodev2/", tag: "Oparty na Kodzie" },
            { name: "ocenaudio", url: "https://www.ocenaudio.com/", tag: "Edytor Audio" },
            { name: "OpenMPT", url: "https://openmpt.org/", tag: "Tracker Muzyczny" },
            { name: "Ossia", url: "https://ossia.io/", tag: "Sekwencer Intermedialny" },
            { name: "plugdata", url: "https://plugdata.org/", tag: "Wizualny Edytor Audio" },
            { name: "Reaper", url: "https://www.reaper.fm/", tag: "Lekki DAW" },
            { name: "Rosegarden", url: "https://rosegardenmusic.com/", tag: "Midi/Notacja" },
            { name: "Schism Tracker (Mirror)", url: "https://schismtracker.org/" },
            { name: "Serato (Mirror)", url: "https://serato.com/" },
            { name: "Sonic-Pi", url: "https://sonic-pi.net/", tag: "Oparty na Kodzie" },
            { name: "StemRoller (Mirror)", url: "https://www.stemroller.com/" },
            { name: "Studel (Mirror)", url: "https://strudel.cc/" },
            { name: "SunVox", url: "https://warmplace.ru/soft/sunvox/", tag: "Modularne Audio" },
            { name: "SuperCollider (Mirror)", url: "https://supercollider.github.io/" },
            { name: "Team V.R releases", url: "https://rentry.co/FMHYBase64#team-vr", tag: "Indeks Edytorów Audio" },
            { name: "Tenacity", url: "https://tenacityaudio.org/", tag: "Edytor Audio" },
            { name: "VirtualDJ (Mirror)", url: "https://www.virtualdj.com/" },
            { name: "Waveform Free", url: "https://www.tracktion.com/products/waveform-free", tag: "DAW" },
            { name: "WaveTracker", url: "https://wavetracker.org/", tag: "Edytor Wavetable" },
            { name: "WebChuck IDE (Mirror)", url: "https://ccrma.stanford.edu/~tzfeng/webchuck-ide/" },
            { name: "Zrythm", url: "https://www.zrythm.org/en/index.html", tag: "DAW" }
          ]
        },
        {
          title: "Edytory / Syntezatory Przeglądarkowe",
          links: [
            { name: "AbyssBox (Mirror)", url: "https://choptop84.github.io/abyssbox-app/" },
            { name: "Acid Machine 2 (Mirror)", url: "https://errozero.co.uk/acid-machine/" },
            { name: "Audioalter", url: "https://audioalter.com/", tag: "Edytor Online" },
            { name: "AudioMass", url: "https://audiomass.co/", tag: "Edytor Online" },
            { name: "BandLab", url: "https://www.bandlab.com/", tag: "DAW Online" },
            { name: "BeatMachine", url: "https://beatmachine.branchpanic.me/", tag: "Edytor Tempa Audio" },
            { name: "BeepBox (Mirror)", url: "https://www.beepbox.co/" },
            { name: "bungee (Mirror)", url: "https://bungee.parabolaresearch.com/bungee-web-demo" },
            { name: "Draw Audio (Mirror)", url: "https://draw.audio/" },
            { name: "DrawBeats (Mirror)", url: "https://drawbeats.com/" },
            { name: "DrumBit (Mirror)", url: "https://drumbit.app/" },
            { name: "Drumhaus", url: "https://www.drumha.us/", tag: "Wirtualna Maszyna Perkusyjna" },
            { name: "Drummy (Mirror)", url: "https://drummy.io/" },
            { name: "editor.audio (Mirror)", url: "https://editor.audio/" },
            { name: "Efflux", url: "https://www.igorski.nl/application/efflux/", tag: "Tracker Online" },
            { name: "GoldBox (Mirror)", url: "https://aurysystem.github.io/goldbox/" },
            { name: "Hydrogen (Mirror)", url: "http://hydrogen-music.org/" },
            { name: "iO-808 (Mirror)", url: "https://io808.com/" },
            { name: "JummBox (Mirror)", url: "https://jummb.us/" },
            { name: "MIDI Recorder", url: "https://midi-recorder.web.app/", tag: "Rejestrator Klawiatury" },
            { name: "MK-1", url: "https://ericrosenbaum.github.io/MK-1/", tag: "Klawiatura do Samplowania Online" },
            { name: "NoiseCraft", url: "https://noisecraft.app/", tag: "Syntezator Modularny" },
            { name: "OnlineSequencer (Mirror)", url: "https://onlinesequencer.net/" },
            { name: "orDrumbox (Mirror)", url: "https://www.ordrumbox.com/" },
            { name: "Pantam Playground", url: "https://www.yishama.com/virtual-pantam-playground/", tag: "Wirtualny Pantam" },
            { name: "Petaporon", url: "https://pixwlk.itch.io/petaporon", tag: "Sekwencer Pianinowy" },
            { name: "Pianoboi (Mirror)", url: "https://pianoboi.site/" },
            { name: "PIXELSYNTH", url: "https://ojack.xyz/PIXELSYNTH/", tag: "Obraz na Dźwięk" },
            { name: "React Guitar", url: "https://react-guitar.com/", tag: "Wirtualna Gitara" },
            { name: "Roland50.studio (Mirror)", url: "https://roland50.studio/" },
            { name: "Sequencer", url: "https://sequencer.henryfellerhoff.com/", tag: "Sekwencer Skal" },
            { name: "Sequencer64 (Mirror)", url: "https://www.sequencer64.com/" },
            { name: "Signal", url: "https://signal.vercel.app/", tag: "Edytor MIDI" },
            { name: "Slowed and Reverb", url: "https://slowedandreverb.studio/", tag: "Edytor Tempa/Pogłosu" },
            { name: "Theremin", url: "https://femurdesign.com/theremin/", tag: "Wirtualny Theremin" },
            { name: "TwistedWave", url: "https://twistedwave.com/online", tag: "Edytor Online" },
            { name: "UltraBox", url: "https://ultrabox.github.io/", tag: "Sekwencer Online" },
            { name: "VirtualPiano", url: "https://virtualpiano.net/", tag: "Pianino w Przeglądarce" },
            { name: "VO Pads", url: "https://vo.odgn.net/", tag: "Sekwencer Sampli Wideo" },
            { name: "WavaCity", url: "https://wavacity.com/", tag: "Edytor Online" },
            { name: "WD-1", url: "https://www.worteldrie.com/WD5/", tag: "Twórcy DJ/Beatów Online" },
            { name: "WebSynths", url: "https://www.websynths.com/", tag: "Syntezatory w Przeglądarce" },
            { name: "xAudioPro", url: "https://www.xaudiopro.com/en/", tag: "Edytor Online" },
            { name: "YOU.DJ (Mirror)", url: "https://you.dj/" }
          ]
        },
        {
          title: "Pluginy Audio (VST/VSTi)",
          links: [
            { name: "AirWindows", url: "https://www.airwindows.com/", tag: "Wtyczki" },
            { name: "AudioTools", url: "https://audiotools.in/", tag: "Torrent/Wtyczki" },
            { name: "AudioWavePro", url: "https://t.me/AudioWavePro", tag: "Telegram/AudioZ" },
            { name: "AudioZ", url: "https://audioz.download/", tag: "Wtyczki Premium" },
            { name: "bobdule", url: "https://bobdule999.wixsite.com/bob-dule-factory-2", tag: "Kontakt/Native Instruments" },
            { name: "Cardinal (Mirror)", url: "https://cardinal.kx.studio/" },
            { name: "Chowdhury DSP (Mirror)", url: "https://chowdsp.com/products.html" },
            { name: "Decent Sampler", url: "https://www.decentsamples.com/product/decent-sampler-plugin/", tag: "Sampler VST" },
            { name: "Dexed", url: "https://asb2m10.github.io/dexed/", tag: "Emulacja Yamaha DX7" },
            { name: "Free VST Plugins", url: "https://bedroomproducersblog.com/free-vst-plugins/", tag: "Indeks" },
            { name: "G-MEH", url: "https://g-meh.com/", tag: "Wtyczki/Sample" },
            { name: "Helm", url: "https://tytel.org/helm/", tag: "Syntezator Wavetable" },
            { name: "HQVst", url: "https://t.me/HQVst", tag: "Telegram" },
            { name: "IEM Plug-in Suite", url: "https://plugins.iem.at/", tag: "Open-Source" },
            { name: "Igorski", url: "https://www.igorski.nl/download", tag: "Open-Source" },
            { name: "Krush", url: "https://www.tritik.com/product/krush/", tag: "Bitcrusher" },
            { name: "looperman (Mirror)", url: "https://www.looperman.com/free-music-software" },
            { name: "Maim", url: "https://github.com/ArdenButterfield/Maim", tag: "Wtyczka do Dystorsji" },
            { name: "ModularSamples (Mirror)", url: "https://www.modularsamples.com/Plugins.html" },
            { name: "Open-Source Audio Plugins", url: "https://openaudio.webprofusion.com/", tag: "Indeks" },
            { name: "Pianobook", url: "https://www.pianobook.co.uk/", tag: "Paczki Sampli" },
            { name: "Plugins4Free", url: "https://plugins4free.com/" },
            { name: "r/SynthRecipes", url: "https://www.reddit.com/r/synthrecipes/", tag: "Prośby o Syntezatory" },
            { name: "samplv1", url: "https://samplv1.sourceforge.io/", tag: "Syntezator Głosu" },
            { name: "sforzando (Mirror)", url: "https://www.plogue.com/products/sforzando.html" },
            { name: "SPARTA (Mirror)", url: "https://leomccormack.github.io/sparta-site/" },
            { name: "Surge XT", url: "https://surge-synthesizer.github.io/", tag: "Hybrydowy Syntezator" },
            { name: "Team V.R releases", url: "https://rentry.co/FMHYBase64#team-vr", tag: "Wtyczki Premium" },
            { name: "VCV Rack 2", url: "https://vcvrack.com/Rack", tag: "Symulator Eurorack" },
            { name: "Vital", url: "https://vital.audio/", tag: "Syntezator Wavetable" }
          ]
        },
        {
          title: "Efekty Dźwiękowe & Soundbanki",
          links: [
            { name: "101soundboards (Mirror)", url: "https://www.101soundboards.com/" },
            { name: "BandLab SFX", url: "https://www.bandlab.com/sounds/packs", tag: "Wymagana Rejestracja" },
            { name: "BBC Sound Effects", url: "https://sound-effects.bbcrewind.co.uk/" },
            { name: "Bfxr (Mirror)", url: "https://www.bfxr.net/" },
            { name: "ChipTone (Mirror)", url: "https://sfbgames.itch.io/chiptone" },
            { name: "Citizen DJ", url: "https://citizen-dj.labs.loc.gov/", tag: "Biblioteka Kongresu" },
            { name: "EXP Soundboard", url: "https://sourceforge.net/projects/expsoundboard/", tag: "Aplikacja Soundboard" },
            { name: "FindSounds", url: "https://www.findsounds.com/", tag: "Wyszukiwarka Dźwięków" },
            { name: "Free Adobe SFX", url: "https://www.adobe.com/products/audition/offers/AdobeAuditionDLCSFX.html" },
            { name: "Freesound (Mirror)", url: "https://freesound.org/" },
            { name: "FreeSoundsLibrary (Mirror)", url: "https://www.freesoundslibrary.com/" },
            { name: "GDC", url: "https://sonniss.com/gameaudiogdc", tag: "Royalty Free" },
            { name: "Kits4Beats", url: "https://kits4beats.com/", tag: "Pobieranie/Torrent" },
            { name: "looperman (Mirror)", url: "https://www.looperman.com/loops" },
            { name: "Musical Artifacts", url: "https://musical-artifacts.com/" },
            { name: "MyInstants", url: "https://www.myinstants.com/index/us/", tag: "Soundboardy Online" },
            { name: "OrangeFreeSounds", url: "https://orangefreesounds.com/", tag: "Darmowe do Użytku" },
            { name: "PLUGG SUPPLY", url: "https://t.me/pluggsupply", tag: "Telegram" },
            { name: "Resanance (Mirror)", url: "https://resanance.com/" },
            { name: "rFXGen (Mirror)", url: "https://raylibtech.itch.io/rfxgen" },
            { name: "r/LoopKits", url: "https://www.reddit.com/r/loopkits/", tag: "Dodane przez Użytkowników" },
            { name: "SampleBrain", url: "https://gitlab.com/then-try-this/samplebrain", tag: "Kreator SFX" },
            { name: "SampleSwap (Mirror)", url: "https://sampleswap.org/" },
            { name: "SFXR (Mirror)", url: "https://sfxr.me/" },
            { name: "SNES Soundfonts", url: "https://www.williamkage.com/snes_soundfonts/" },
            { name: "Soundboard.com (Mirror)", url: "https://www.soundboard.com/" },
            { name: "SoundGator (Mirror)", url: "https://www.soundgator.com/" },
            { name: "Sound Show (Mirror)", url: "https://soundshow.app/" },
            { name: "Soundux (Mirror)", url: "https://soundux.rocks/" },
            { name: "Voicy (Mirror)", url: "https://www.voicy.network/" }
          ]
        }
      ]
    }
  ],
  infoBox: {
    title: "💡 Wskazówki dla początkujących",
    items: [
      "<strong>Najlepsze do pobierania:</strong> Soulseek przez Nicotine+ - miliony utworów w wysokiej jakości. Dla szybkich pobrań online: Cobalt.tools lub DoubleDouble.",
      "<strong>Streaming bez reklam:</strong> Wypróbuj Spotube lub Nuclear jako alternatywne klienty.",
      "<strong>Najlepsza jakość (Lossless):</strong> Szukaj plików FLAC na Soulseeku lub korzystaj z ripperów takich jak Qobuz-DL/tidal-dl-ng, jeśli masz dostęp do konta Hi-Res.",
      "<strong>Soundtracki:</strong> Sitting on Clouds lub KHInsider to najlepsze źródła OST z gier, filmów i anime.",
      "<strong>Telegram boty:</strong> Są bardzo wygodne do szybkiego pobierania muzyki na telefon.",
      "<strong>Produkcja muzyczna:</strong> Zacznij od darmowych DAW takich jak LMMS i darmowych wtyczek VST, np. Vital lub Surge XT.",
      "<strong>Radio online:</strong> Radio Garden to fantastyczny sposób na odkrywanie stacji radiowych z całego świata.",
      "<strong>Spotify mods:</strong> SpotX dla Windows i xManager dla Androida to sprawdzone narzędzia do usuwania reklam.",
      "<strong>Zawsze używaj:</strong> <a href=\"privacy.html\" target=\"_blank\">AdBlockera</a> na stronach z reklamami, aby poprawić komfort korzystania."
    ]
  },
  warningBox: {
    title: "⚠️ Bezpieczeństwo i ważne informacje",
    items: [
      "Używaj <a href=\"privacy.html\" target=\"_blank\">VPN</a> przy torrentach i P2P, aby chronić swoją tożsamość.",
      "Zainstaluj <a href=\"privacy.html\" target=\"_blank\">uBlock Origin</a> przed wejściem na strony oferujące pirackie treści, aby uniknąć wyskakujących okienek i złośliwego oprogramowania.",
      "Uważaj na fałszywe przyciski pobierania i reklamy na stronach z darmową muzyką.",
      "Skanuj pobrane pliki antywirusem (<a href=\"https://www.virustotal.com/\" target=\"_blank\">VirusTotal</a>) przed otwarciem, zwłaszcza te z mniej zaufanych źródeł.",
      "Wspieraj artystów, kupując muzykę, gdy tylko masz taką możliwość."
    ]
  }
};