const pageData = {
    "featured": {
        "title": "🏆 Polecane dla Programistów",
        "links": [
            {
                "title": "VSCodium / VS Code",
                "description": "Najpopularniejszy edytor kodu z ogromnym ekosystemem rozszerzeń. VSCodium to wersja bez telemetrii Microsoftu.",
                "url": "https://vscodium.com/",
                "badge": "Edytor Kodu"
            },
            {
                "title": "StackOverflow",
                "description": "Niezastąpione forum i baza wiedzy dla każdego programisty. Znajdziesz tu odpowiedzi na niemal każde pytanie.",
                "url": "https://stackoverflow.com/",
                "badge": "Społeczność"
            },
            {
                "title": "DevToys",
                "description": "Szwajcarski scyzoryk dla deweloperów. Zestaw narzędzi offline do formatowania, konwersji i wielu innych.",
                "url": "https://devtoys.app/",
                "badge": "Narzędzia"
            },
            {
                "title": "Free for Developers",
                "description": "Ogromna, kuratorowana lista oprogramowania i usług, które oferują darmowe plany dla deweloperów.",
                "url": "https://free-for.dev/",
                "badge": "Zasoby"
            }
        ]
    },
    "sections": [
        {
            "id": "edytory-kodu-i-ide",
            "title": "📝 Edytory Kodu i IDE",
            "links": [
                { "name": "Acode", "url": "https://acode.app", "tag": "⭐ Android" },
                { "name": "Android Studio", "url": "https://developer.android.com/studio", "tag": "⭐ Android" },
                { "name": "Apache NetBeans", "url": "https://netbeans.apache.org/" },
                { "name": "Atheos", "url": "https://www.atheos.io/", "tag": "W chmurze" },
                { "name": "Bluefish", "url": "https://bluefish.openoffice.nl/index.html" },
                { "name": "Brackets", "url": "https://brackets.io/" },
                { "name": "CodeSandbox", "url": "https://codesandbox.io/", "tag": "⭐ W chmurze" },
                { "name": "CodeTasty", "url": "https://codetasty.com/", "tag": "W chmurze" },
                { "name": "CoderPad", "url": "https://pad.new/", "tag": "W chmurze" },
                { "name": "Competitive Editor", "url": "https://cpeditor.org/" },
                { "name": "CudaText", "url": "https://cudatext.github.io/" },
                { "name": "diohub", "url": "https://github.com/NamanShergill/diohub", "tag": "Android" },
                { "name": "droidvim", "url": "https://github.com/shiftrot/droidvim", "tag": "Android" },
                { "name": "ecode", "url": "https://github.com/SpartanJ/ecode" },
                { "name": "Edna", "url": "https://edna.arslexis.io/", "tag": "W chmurze" },
                { "name": "Emacs", "url": "https://www.gnu.org/software/emacs/", "tag": "⭐ Klasyk" },
                { "name": "Firebase", "url": "https://studio.firebase.google.com/", "tag": "W chmurze" },
                { "name": "Fleet", "url": "https://www.jetbrains.com/fleet/", "tag": "W chmurze" },
                { "name": "Geany", "url": "https://www.geany.org/" },
                { "name": "Google Colaboratory", "url": "https://colab.research.google.com/", "tag": "⭐ W chmurze" },
                { "name": "goormIDE", "url": "https://ide.goorm.io/", "tag": "⭐ W chmurze" },
                { "name": "HaystackEditor", "url": "https://haystackeditor.com/" },
                { "name": "Helix", "url": "https://helix-editor.com/" },
                { "name": "Heynote", "url": "https://heynote.com/" },
                { "name": "html-css-js", "url": "https://html-css-js.com/", "tag": "W chmurze" },
                { "name": "Ideone", "url": "https://www.ideone.com/", "tag": "W chmurze" },
                { "name": "JetBrains", "url": "https://jetbrains.com/", "tag": "⭐ Profesjonalne" },
                { "name": "JSFiddle", "url": "https://jsfiddle.net/", "tag": "W chmurze" },
                { "name": "JSON Hero", "url": "https://jsonhero.io/" },
                { "name": "judge0", "url": "https://ide.judge0.com/", "tag": "⭐ W chmurze" },
                { "name": "KDevelop", "url": "https://www.kdevelop.org/" },
                { "name": "Lapce", "url": "https://lap.dev/lapce/" },
                { "name": "Lazarus", "url": "https://www.lazarus-ide.org/" },
                { "name": "Lite XL", "url": "https://lite-xl.com/", "tag": "⭐ Lekki" },
                { "name": "Mitosis", "url": "https://mitosis.builder.io/" },
                { "name": "Neovim", "url": "https://neovim.io/", "tag": "⭐ Terminal" },
                { "name": "OpenShift", "url": "https://developers.redhat.com/products/openshift-dev-spaces/overview" },
                { "name": "PlayCode", "url": "https://playcode.io/", "tag": "W chmurze" },
                { "name": "Pragtical", "url": "https://pragtical.dev/" },
                { "name": "SciTE", "url": "https://www.scintilla.org/SciTE.html" },
                { "name": "Sora", "url": "https://github.com/Rosemoe/sora-editor", "tag": "Android" },
                { "name": "Spck Editor", "url": "https://play.google.com/store/apps/details?id=io.spck", "tag": "Android" },
                { "name": "Squircle-CE", "url": "https://github.com/massivemadness/Squircle-CE", "tag": "⭐ Android" },
                { "name": "StackBlitz", "url": "https://stackblitz.com/", "tag": "W chmurze" },
                { "name": "TidalCycles", "url": "https://tidalcycles.org/" },
                { "name": "Trinket", "url": "https://trinket.io/" },
                { "name": "VHEditor", "url": "https://github.com/vhqtvn/VHEditor-Android", "tag": "Android" },
                { "name": "Visual Code Space", "url": "https://github.com/Visual-Code-Space/Visual-Code-Space", "tag": "Android" },
                { "name": "Visual Studio Code", "url": "https://code.visualstudio.com/", "tag": "⭐ Polecane" },
                { "name": "VSCodium", "url": "https://vscodium.com/", "tag": "⭐ Bez telemetrii" },
                { "name": "WebDen", "url": "https://webden.dev/", "tag": "⭐ Playground" },
                { "name": "zed", "url": "https://zed.dev/", "tag": "⭐ Szybki" }
            ]
        },
        {
            "id": "kontrola-wersji-git-i-github",
            "title": "🔄 Kontrola Wersji (Git i GitHub)",
            "links": [
                { "name": "Active-Forks", "url": "https://techgaun.github.io/active-forks/index.html", "tag": "Wyszukiwarka" },
                { "name": "act", "url": "https://nektosact.com/", "tag": "Lokalne Akcje" },
                { "name": "Allstar", "url": "https://github.com/ossf/allstar", "tag": "Bezpieczeństwo" },
                { "name": "Codeberg", "url": "https://codeberg.org/", "tag": "⭐ Alternatywa" },
                { "name": "Delta", "url": "https://github.com/dandavison/delta", "tag": "Przeglądarka różnic" },
                { "name": "DownGit", "url": "https://downgit.evecalm.com/", "tag": "Pobieranie" },
                { "name": "Fork", "url": "https://git-fork.com/", "tag": "⭐ Klient GUI" },
                { "name": "Forgejo", "url": "https://forgejo.org/", "tag": "Self-hosted" },
                { "name": "Gitea", "url": "https://about.gitea.com/", "tag": "Alternatywa" },
                { "name": "GitHub Desktop", "url": "https://github.com/apps/desktop", "tag": "⭐ Klient GUI" },
                { "name": "GitKraken", "url": "https://www.gitkraken.com/", "tag": "Klient GUI" },
                { "name": "GitLab.com", "url": "https://about.gitlab.com/", "tag": "Alternatywa" },
                { "name": "Gource", "url": "https://gource.io/", "tag": "Wizualizacja" },
                { "name": "Gothub", "url": "https://codeberg.org/gothub/gothub", "tag": "Frontend" },
                { "name": "lazygit", "url": "https://github.com/jesseduffield/lazygit", "tag": "Klient TUI" },
                { "name": "Octotree", "url": "https://www.octotree.io/", "tag": "Rozszerzenie" },
                { "name": "refined-github", "url": "https://github.com/refined-github/refined-github", "tag": "Rozszerzenie" },
                { "name": "searchcode", "url": "https://searchcode.com/", "tag": "Wyszukiwarka kodu" },
                { "name": "sourcehut", "url": "https://sourcehut.org/", "tag": "Alternatywa" },
                { "name": "Sourcetree", "url": "https://www.sourcetreeapp.com/", "tag": "Klient GUI" },
                { "name": "up-for-grabs", "url": "https://up-for-grabs.net/", "tag": "Dla początkujących" }
            ]
        },
        {
            "id": "web-development",
            "title": "🌐 Web Development",
            "links": [
                { "name": "Animista", "url": "https://animista.net/", "tag": "CSS" },
                { "name": "Bootstrap", "url": "https://getbootstrap.com/", "tag": "Framework CSS" },
                { "name": "Can I Use?", "url": "https://caniuse.com/", "tag": "Kompatybilność" },
                { "name": "Clean CSS", "url": "https://www.cleancss.com/", "tag": "Narzędzia Online" },
                { "name": "Codepen", "url": "https://codepen.io/", "tag": "Playground" },
                { "name": "ColorHexa", "url": "https://www.colorhexa.com/", "tag": "⭐ Kolory" },
                { "name": "Component Party", "url": "https://component-party.dev/", "tag": "Frameworki JS" },
                { "name": "CSS Tricks", "url": "https://css-tricks.com/snippets/", "tag": "Poradniki CSS" },
                { "name": "de4js", "url": "https://lelinhtinh.github.io/de4js/", "tag": "Deobfuskator JS" },
                { "name": "Formulaer", "url": "https://formulaer.com/", "tag": "⭐ Formularze" },
                { "name": "FreeFrontend", "url": "https://freefrontend.com/", "tag": "⭐ Snippety" },
                { "name": "Get Waves", "url": "https://getwaves.io/", "tag": "Generator SVG" },
                { "name": "Glass UI", "url": "https://ui.glass/generator/", "tag": "Generator CSS" },
                { "name": "HTML Reference", "url": "https://htmlreference.io/", "tag": "⭐ Dokumentacja" },
                { "name": "PageSpeed", "url": "https://pagespeed.web.dev/", "tag": "⭐ Testowanie" },
                { "name": "Pattern Monster", "url": "https://pattern.monster/", "tag": "Generator SVG" },
                { "name": "Prettier", "url": "https://prettier.io/", "tag": "Formater kodu" },
                { "name": "Ray.st", "url": "https://ray.st/", "tag": "⭐ Analiza" },
                { "name": "Realtime Colors", "url": "https://realtimecolors.com/", "tag": "⭐ Kolory" },
                { "name": "Regex Vis", "url": "https://regex-vis.com/", "tag": "⭐ Regex" },
                { "name": "regex101", "url": "https://regex101.com/", "tag": "⭐ Regex" },
                { "name": "Responsive Viewer", "url": "https://responsiveviewer.org/", "tag": "Testowanie" },
                { "name": "shadcn-ui", "url": "https://ui.shadcn.com/", "tag": "Komponenty UI" },
                { "name": "SVGO", "url": "https://github.com/svg/svgo", "tag": "Optymalizacja SVG" },
                { "name": "Tally", "url": "https://tally.so/", "tag": "Formularze" },
                { "name": "ThemeWagon", "url": "https://themewagon.com/theme-price/free/", "tag": "⭐ Szablony" },
                { "name": "Wappalyzer", "url": "https://www.wappalyzer.com/", "tag": "Analiza" },
                { "name": "Web Dev Checklist", "url": "https://www.toptal.com/developers/webdevchecklist", "tag": "Checklista" },
                { "name": "You Don't Need JavaScript", "url": "https://github.com/you-dont-need/You-Dont-Need-JavaScript", "tag": "⭐ Inspiracje CSS" }
            ]
        },
        {
            "id": "kreatory-stron-i-cms",
            "title": "🏗️ Kreatory Stron i CMS",
            "links": [
                { "name": "Astro", "url": "https://astro.build/" },
                { "name": "Docusaurus", "url": "https://docusaurus.io/", "tag": "⭐ Dokumentacja" },
                { "name": "Eleventy", "url": "https://11ty.dev/", "tag": "⭐ Statyczne" },
                { "name": "Framer", "url": "https://www.framer.com/", "tag": "⭐ Wizualny" },
                { "name": "GitBook", "url": "https://www.gitbook.com/" },
                { "name": "Hugo", "url": "https://gohugo.io/", "tag": "⭐ Statyczne" },
                { "name": "Jekyll", "url": "https://jekyllrb.com/" },
                { "name": "Joomla", "url": "https://www.joomla.org/" },
                { "name": "Mobirise", "url": "https://mobirise.com/" },
                { "name": "Pelican", "url": "https://getpelican.com/" },
                { "name": "Potion", "url": "https://potion.so/", "tag": "Z Notion" },
                { "name": "Publii", "url": "https://getpublii.com/" },
                { "name": "Retype", "url": "https://retype.com/", "tag": "Dokumentacja" },
                { "name": "VitePress", "url": "https://vitepress.dev/", "tag": "⭐ Statyczne" },
                { "name": "Webstudio", "url": "https://webstudio.is/", "tag": "⭐ Wizualny" },
                { "name": "Wordpress", "url": "https://wordpress.org/", "tag": "CMS" },
                { "name": "Zola", "url": "https://www.getzola.org/" }
            ]
        },
        {
            "id": "chmura-hosting-i-domeny",
            "title": "☁️ Chmura, Hosting i Domeny",
            "links": [
                { "name": "alwaysdata.com", "url": "https://www.alwaysdata.com/en/", "tag": "⭐ Hosting" },
                { "name": "Check-Host", "url": "https://check-host.net/", "tag": "⭐ Monitoring" },
                { "name": "Cloudflare Pages", "url": "https://pages.cloudflare.com/", "tag": "⭐ Hosting Statyczny" },
                { "name": "Cloudflare Workers", "url": "https://workers.cloudflare.com/", "tag": "⭐ Serverless" },
                { "name": "deSEC", "url": "https://desec.io/", "tag": "⭐ DNS" },
                { "name": "DuckDNS", "url": "https://www.duckdns.org/", "tag": "DNS" },
                { "name": "Firebase", "url": "https://firebase.google.com/products/hosting", "tag": "⭐ Hosting" },
                { "name": "GitHub Pages", "url": "https://docs.github.com/en/pages", "tag": "⭐ Hosting Statyczny" },
                { "name": "Heroku-Alt", "url": "https://rentry.co/Heroku-Alt", "tag": "Index" },
                { "name": "netlify", "url": "https://www.netlify.com/", "tag": "⭐ Hosting" },
                { "name": "Neocities", "url": "https://neocities.org/", "tag": "Hosting Statyczny" },
                { "name": "ngrok", "url": "https://ngrok.com/", "tag": "Tunelowanie" },
                { "name": "Profreehost", "url": "https://profreehost.com/", "tag": "Hosting" },
                { "name": "Serv00.com", "url": "https://www.serv00.com/", "tag": "⭐ Hosting" },
                { "name": "Sourcehut Pages", "url": "https://srht.site/", "tag": "Hosting Statyczny" },
                { "name": "surge", "url": "https://surge.sh/", "tag": "⭐ Hosting Statyczny" },
                { "name": "TLD-List", "url": "https://tld-list.com/", "tag": "⭐ Domeny" },
                { "name": "Uptime Kuma", "url": "https://github.com/louislam/uptime-kuma", "tag": "Monitoring" },
                { "name": "vercel", "url": "https://vercel.com/", "tag": "⭐ Hosting" }
            ]
        },
        {
            "id": "bazy-danych",
            "title": "🗃️ Bazy Danych",
            "links": [
                { "name": "Awesome Big Data", "url": "https://github.com/oxnr/awesome-bigdata", "tag": "Index" },
                { "name": "ChartDB", "url": "https://chartdb.io/" },
                { "name": "DB Browser", "url": "https://sqlitebrowser.org/", "tag": "⭐ SQLite" },
                { "name": "DB Engines", "url": "https://db-engines.com/en/ranking", "tag": "Ranking" },
                { "name": "DBeaver", "url": "https://dbeaver.io/", "tag": "Klient Uniwersalny" },
                { "name": "DuckDB", "url": "https://duckdb.org/" },
                { "name": "franchise", "url": "https://franchise.cloud/" },
                { "name": "Grafana", "url": "https://grafana.com/", "tag": "Wizualizacja" },
                { "name": "HeidiSQL", "url": "https://www.heidisql.com/", "tag": "Klient SQL" },
                { "name": "Ingestr", "url": "https://bruin-data.github.io/ingestr/" },
                { "name": "NocoDB", "url": "https://www.nocodb.com/", "tag": "No-code" },
                { "name": "Qdrant", "url": "https://qdrant.tech/" },
                { "name": "QueryStorm", "url": "https://querystorm.com/" },
                { "name": "SQL Lite Studio", "url": "https://sqlitestudio.pl/", "tag": "SQLite" },
                { "name": "SQLook", "url": "https://sqlook.com/", "tag": "SQLite" }
            ]
        },
        {
            "id": "api-i-uczenie-maszynowe",
            "title": "🤖 API i Uczenie Maszynowe",
            "links": [
                { "name": "Any API", "url": "https://any-api.com/", "tag": "Index API" },
                { "name": "Awesome Machine Learning", "url": "https://github.com/josephmisiti/awesome-machine-learning", "tag": "Index ML" },
                { "name": "Beeceptor", "url": "https://beeceptor.com/" },
                { "name": "Bruno", "url": "https://www.usebruno.com/", "tag": "Klient API" },
                { "name": "Deep playground", "url": "http://playground.tensorflow.org/", "tag": "⭐ Playground" },
                { "name": "DeepSpeed", "url": "https://www.deepspeed.ai/" },
                { "name": "Firecamp", "url": "https://firecamp.dev/", "tag": "Kreator API" },
                { "name": "hoppscotch", "url": "https://hoppscotch.io/", "tag": "⭐ Kreator API" },
                { "name": "HTTPie", "url": "https://httpie.io/" },
                { "name": "Hugging Face", "url": "https://huggingface.co/", "tag": "⭐ Zasoby ML" },
                { "name": "Insomnia", "url": "https://insomnia.rest/", "tag": "Klient API" },
                { "name": "Mockable", "url": "https://www.mockable.io/", "tag": "Mock API" },
                { "name": "Netron", "url": "https://github.com/lutzroeder/netron", "tag": "Wizualizator" },
                { "name": "OpenML", "url": "https://www.openml.org/", "tag": "Zasoby ML" },
                { "name": "Pipedream", "url": "https://pipedream.com/" },
                { "name": "Posting", "url": "https://posting.sh/" },
                { "name": "Public APIs", "url": "https://github.com/public-apis/public-apis", "tag": "⭐ Index API" },
                { "name": "ReDoc", "url": "https://redocly.github.io/redoc/" },
                { "name": "Shizuku", "url": "https://shizuku.rikka.app/", "tag": "⭐ Android" },
                { "name": "Stein", "url": "https://steinhq.com/" },
                { "name": "Strapi", "url": "https://strapi.io/", "tag": "Kreator API" },
                { "name": "Unsloth", "url": "https://github.com/unslothai/unsloth", "tag": "Finetuning LLM" }
            ]
        },
        {
            "id": "cyberbezpieczenstwo",
            "title": "🛡️ Cyberbezpieczeństwo",
            "links": [
                { "name": "AbuseIPDB", "url": "https://www.abuseipdb.com/", "tag": "Sprawdzanie IP" },
                { "name": "Awesome Cryptography", "url": "https://github.com/sobolevn/awesome-cryptography", "tag": "⭐ Index" },
                { "name": "Awesome Hacking", "url": "https://github.com/Hack-with-Github/Awesome-Hacking", "tag": "Index" },
                { "name": "Canarytokens", "url": "https://canarytokens.org/generate", "tag": "Monitoring" },
                { "name": "censys", "url": "https://search.censys.io/", "tag": "⭐ Skaner" },
                { "name": "Crowdsec", "url": "https://crowdsec.net/" },
                { "name": "CVE Details", "url": "https://www.cvedetails.com/", "tag": "Podatności" },
                { "name": "DNSDumpster", "url": "https://dnsdumpster.com/", "tag": "Narzędzia DNS" },
                { "name": "Exploit DB", "url": "https://www.exploit-db.com/", "tag": "Baza exploitów" },
                { "name": "Fail2Ban", "url": "https://github.com/fail2ban/fail2ban", "tag": "Ochrona" },
                { "name": "GHIDRA", "url": "https://ghidra-sre.org/", "tag": "⭐ Inżynieria Wsteczna" },
                { "name": "Hydra", "url": "https://github.com/ory/hydra" },
                { "name": "KrebsOnSecurity", "url": "https://krebsonsecurity.com/", "tag": "⭐ Wiadomości" },
                { "name": "Let's Encrypt", "url": "https://letsencrypt.org/", "tag": "Certyfikaty" },
                { "name": "MalShare", "url": "https://malshare.com/", "tag": "Baza malware" },
                { "name": "mess with dns", "url": "https://messwithdns.net/", "tag": "⭐ Playground DNS" },
                { "name": "Metasploit", "url": "https://www.metasploit.com/", "tag": "Pentesting" },
                { "name": "mitmproxy", "url": "https://mitmproxy.org/", "tag": "Analiza Ruchu" },
                { "name": "Nmap", "url": "https://nmap.org/", "tag": "Skaner Sieci" },
                { "name": "Nuclei", "url": "https://docs.projectdiscovery.io/tools/nuclei" },
                { "name": "pyWhat", "url": "https://github.com/bee-san/pyWhat", "tag": "⭐ Analizator" },
                { "name": "SSLLabs", "url": "https://www.ssllabs.com/", "tag": "Testowanie SSL" },
                { "name": "ThreatMap", "url": "https://threatmap.checkpoint.com/", "tag": "Mapa Zagrożeń" },
                { "name": "URLhaus", "url": "https://urlhaus.abuse.ch/" },
                { "name": "WebAuthn", "url": "https://webauthn.guide/", "tag": "Uwierzytelnianie" },
                { "name": "x64dbg", "url": "https://x64dbg.com/", "tag": "⭐ Debugger" },
                { "name": "ZAP", "url": "https://www.zaproxy.org/", "tag": "Testowanie" }
            ]
        },
        {
            "id": "tworzenie-gier-gamedev",
            "title": "🎲 Tworzenie Gier (Gamedev)",
            "links": [
                { "name": "AssetRipper", "url": "https://github.com/AssetRipper/AssetRipper", "tag": "Ekstraktor" },
                { "name": "Awesome Game Dev", "url": "https://github.com/Calinou/awesome-gamedev", "tag": "⭐ Index" },
                { "name": "Bleeper", "url": "https://pixwlk.itch.io/bleeper", "tag": "Tworzenie SFX" },
                { "name": "Dev Assets", "url": "https://devassets.com/", "tag": "Zasoby" },
                { "name": "EnginesDatabase", "url": "https://enginesdatabase.com/", "tag": "Baza Silników" },
                { "name": "Fantasy Consoles / Computers", "url": "https://github.com/paladin-t/fantasy", "tag": "Index" },
                { "name": "Game Sounds", "url": "https://gamesounds.xyz/", "tag": "Dźwięki" },
                { "name": "Game-icons", "url": "https://game-icons.net/", "tag": "Ikony" },
                { "name": "HiddenPalace", "url": "https://hiddenpalace.org/", "tag": "Archiwum" },
                { "name": "Itch.io Assets", "url": "https://itch.io/game-assets/free", "tag": "Zasoby" },
                { "name": "jfxr", "url": "https://jfxr.frozenfractal.com/", "tag": "Tworzenie SFX" },
                { "name": "Kenney", "url": "https://www.kenney.nl/", "tag": "Zasoby" },
                { "name": "LDtk", "url": "https://ldtk.io/", "tag": "Edytor Poziomów" },
                { "name": "List of Game Engines", "url": "https://en.wikipedia.org/wiki/List_of_game_engines", "tag": "Index" },
                { "name": "OpenGameArt.org", "url": "https://opengameart.org/", "tag": "Zasoby" },
                { "name": "Quaternius", "url": "https://quaternius.com/", "tag": "Zasoby" },
                { "name": "Sprite Fusion", "url": "https://www.spritefusion.com/", "tag": "⭐ Edytor Map" },
                { "name": "SteamGridDB", "url": "https://www.steamgriddb.com/", "tag": "Grafiki" },
                { "name": "Tiled", "url": "https://www.mapeditor.org/", "tag": "Edytor Map" },
                { "name": "Tilesetter", "url": "https://www.tilesetter.org/", "tag": "Edytor Map" }
            ]
        },
        {
            "id": "spolecznosci-i-wiadomosci",
            "title": "🗣️ Społeczności i Wiadomości",
            "links": [
                { "name": "Blind", "url": "https://www.teamblind.com/", "tag": "Forum" },
                { "name": "CodeProject", "url": "https://www.codeproject.com/", "tag": "Forum" },
                { "name": "daily.dev", "url": "https://app.daily.dev/posts", "tag": "Wiadomości" },
                { "name": "DEV Community", "url": "https://dev.to/", "tag": "Forum" },
                { "name": "DevBuddies", "url": "https://buddies.dev/" },
                { "name": "DevURLs", "url": "https://devurls.com/", "tag": "Wiadomości" },
                { "name": "IndieHackers", "url": "https://www.indiehackers.com/", "tag": "Forum" },
                { "name": "jimmyr", "url": "https://jimmyr.com/", "tag": "Wiadomości" },
                { "name": "KrebsOnSecurity", "url": "https://krebsonsecurity.com/", "tag": "⭐ Bezpieczeństwo" },
                { "name": "Lobsters", "url": "https://lobste.rs/", "tag": "⭐ Wiadomości" },
                { "name": "Spiceworks Community", "url": "https://community.spiceworks.com/", "tag": "Forum" },
                { "name": "StackOverflow", "url": "https://stackoverflow.com/", "tag": "⭐ Forum" },
                { "name": "Tech-Blogs", "url": "https://tech-blogs.dev/", "tag": "Blogi" },
                { "name": "TheSecMaster", "url": "https://x.com/TheSecMaster1", "tag": "Blog" },
                { "name": "XDA", "url": "https://xdaforums.com/", "tag": "⭐ Forum" }
            ]
        }
    ],
    "info": {
        "title": "💡 Wskazówki i Dobre Praktyki",
        "toc_title": "💡 Wskazówki",
        "tips": [
            "<strong>Kontrola wersji to podstawa:</strong> Używaj Gita dla każdego projektu, nawet tego najmniejszego. Ułatwia to śledzenie zmian, współpracę i powrót do poprzednich wersji.",
            "<strong>Czytaj dokumentację:</strong> Zanim zadasz pytanie na StackOverflow, spróbuj znaleźć odpowiedź w oficjalnej dokumentacji narzędzia lub języka.",
            "<strong>Nie wymyślaj koła na nowo:</strong> Przeglądaj istniejące biblioteki i frameworki. Często ktoś już rozwiązał problem, z którym się mierzysz.",
            "<strong>Bezpieczeństwo od początku:</strong> Myśl o bezpieczeństwie na każdym etapie tworzenia aplikacji, a nie jako o dodatku na sam koniec."
        ]
    }
};