const pageData = {
  sections: [
    {
      id: "niezbedne-blokery-prywatnosc",
      title: "⭐ Niezbędne - Blokery Reklam i Prywatność",
      links: [
        { name: "uBlock Origin", url: "https://ublockorigin.com/", description: "Najlepszy bloker reklam. Szybki, lekki i niezwykle skuteczny." },
        { name: "I Still Don't Care About Cookies", url: "https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies", description: "Automatycznie akceptuje lub ukrywa irytujące okienka z prośbą o zgodę na ciasteczka." },
        { name: "Privacy Badger", url: "https://www.eff.org/privacybadger", description: "Automatycznie uczy się i blokuje niewidzialne skrypty śledzące." },
        { name: "ClearURLs", url: "https://github.com/ClearURLs/Addon", description: "Automatycznie usuwa elementy śledzące z adresów URL." },
        { name: "Canvas Blocker", url: "https://github.com/CanvasBlocker/CanvasBlocker", description: "Chroni przed zaawansowaną techniką śledzenia (fingerprinting)." },
        { name: "Decentraleyes", url: "https://decentraleyes.org/", description: "Chroni przed śledzeniem przez CDN dostarczając lokalne kopie bibliotek." },
        { name: "LocalCDN", url: "https://www.localcdn.org/", description: "Ulepszona wersja Decentraleyes z większą bazą bibliotek." },
        { name: "Cookie AutoDelete", url: "https://github.com/Cookie-AutoDelete/Cookie-AutoDelete", description: "Automatycznie usuwa ciasteczka po zamknięciu karty." },
        { name: "HTTPS Everywhere", url: "https://github.com/Synzvato/decentraleyes", description: "Wymusza bezpieczne połączenia HTTPS gdzie to możliwe." },
        { name: "Temporary Containers", url: "https://addons.mozilla.org/en-US/firefox/addon/temporary-containers/", description: "Otwiera każdą kartę w izolowanym kontenerze (Firefox)." },
        { name: "Firefox Multi-Account Containers", url: "https://github.com/stoically/firefox-multi-account-containers", description: "Separuje różne aspekty życia online w kolorowe karty." },
        { name: "NoScript", url: "https://noscript.net/", description: "Blokuje JavaScript, Java, Flash i inne pluginy." },
        { name: "TrackMeNot", url: "https://github.com/TrackMeNot/trackmenot", description: "Chroni prywatność poprzez zaciemnianie Twoich wyszukiwań." },
        { name: "Trace", url: "https://github.com/dullage/flatnotes", description: "Chroni przed śledzeniem online." },
        { name: "Windscribe VPN", url: "https://github.com/Windscribe/browser-extension", description: "Darmowy VPN z 10GB miesięcznie." },
        { name: "uMatrix", url: "https://github.com/gorhill/uMatrix", description: "Zaawansowana kontrola nad tym co ładuje strona." },
        { name: "HTTPZ", url: "https://github.com/claustromaniac/httpz", description: "Automatycznie przełącza na HTTPS." },
        { name: "Arkenfox user.js", url: "https://github.com/arkenfox/user.js", description: "Kompletna konfiguracja Firefox dla prywatności." },
        { name: "Buster", url: "https://github.com/dessant/buster", description: "Rozwiązuje CAPTCHA z pomocą mowy." },
        { name: "Block Google Analytics", url: "https://github.com/M-Reimer/no-google-analytics", description: "Blokuje Google Analytics na wszystkich stronach." }
      ]
    },
    {
      id: "youtube-wideo",
      title: "🎥 YouTube i Wideo",
      links: [
        { name: "SponsorBlock", url: "https://sponsor.ajay.app/", description: "Automatycznie pomija segmenty sponsorowane w filmach YouTube." },
        { name: "Return YouTube Dislike", url: "https://www.returnyoutubedislike.com/", description: "Przywraca widoczność licznika \"łapek w dół\"." },
        { name: "Clickbait Remover", url: "https://github.com/pietervanheijningen/clickbait-remover-for-youtube", description: "Zastępuje clickbaitowe miniatury klatką z filmu." },
        { name: "BlockTube", url: "https://www.blocktube.app/", description: "Blokuje kanały i filmy na YouTube według słów kluczowych." },
        { name: "Unhook", url: "https://unhook.app/", description: "Usuwa rozpraszające elementy z YouTube (rekomendacje, komentarze)." },
        { name: "YouTube Center", url: "https://github.com/YePpHa/YouTubeCenter/wiki", description: "Zaawansowane opcje personalizacji YouTube." },
        { name: "Enhancer for YouTube", url: "https://www.enhancer-for-youtube.com/", description: "Dodaje wiele przydatnych funkcji do YouTube." },
        { name: "ImprovedTube", url: "https://github.com/ImprovedTube/ImprovedTube", description: "Ponad 100 funkcji ulepszających YouTube." },
        { name: "YouTube Redux", url: "https://github.com/code-charity/youtube", description: "Przywraca klasyczny wygląd YouTube." },
        { name: "Iridium for YouTube", url: "https://github.com/ParticleCore/Iridium", description: "Lekkie ulepszenia dla YouTube." },
        { name: "YouTube Auto HD", url: "https://github.com/alexbol99/youtube-auto-hd", description: "Automatycznie ustawia najwyższą jakość wideo." },
        { name: "YouTube AutoLike", url: "https://github.com/brunolemos/youtube-autolike", description: "Automatycznie lajkuje filmy ulubionych twórców." },
        { name: "YouTube Geotag Remover", url: "https://github.com/joe-damore/yt-geotag-remover", description: "Usuwa tagi lokalizacji z YouTube." },
        { name: "YouTube Popout Player", url: "https://github.com/trustedtomato/youtube-popout-player", description: "Odłącza odtwarzacz YouTube w osobnym oknie." },
        { name: "YouTube AutoClose Ads", url: "https://github.com/lawrencehook/youtube-autoclose-ads", description: "Automatycznie zamyka reklamy." },
        { name: "Refined YouTube", url: "https://github.com/Anarios/youtube-refined", description: "Usprawnia interfejs YouTube." },
        { name: "GoFullPage", url: "https://github.com/mrcoles/full-page-screen-capture-chrome-extension", description: "Robi zrzut całej strony." },
        { name: "View Image", url: "https://github.com/dessant/view-image", description: "Przywraca przycisk \"Zobacz obraz\" w Google Images." },
        { name: "Google Images Restored", url: "https://github.com/bijij/ViewImage", description: "Przywraca funkcje Google Images." },
        { name: "Facebook Container", url: "https://github.com/mozilla/contain-facebook", description: "Izoluje Facebook od reszty sieci." }
      ]
    },
    {
      id: "omijanie-ograniczen",
      title: "🌐 Omijanie Ograniczeń",
      links: [
        { name: "FastForward", url: "https://fastforward.team/", description: "Omija strony pośredniczące i skracacze linków." },
        { name: "Universal Bypass", url: "https://universal-bypass.org/", description: "Automatycznie omija setki skracaczy linków." },
        { name: "Bypass Paywalls", url: "https://github.com/iamadamdev/bypass-paywalls-chrome", description: "Omija paywalle na stronach newsowych." },
        { name: "Bypass Paywalls Clean", url: "https://gitlab.com/magnolia1234/bypass-paywalls-firefox-clean", description: "Czystsza wersja dla Firefox." },
        { name: "Buster", url: "https://github.com/dessant/buster", description: "Automatycznie rozwiązuje reCAPTCHA." },
        { name: "NopeCHA", url: "https://github.com/NopeCHA/NopeCHA", description: "Automatyczne rozwiązywanie CAPTCHA." },
        { name: "AntiCaptcha Resolver", url: "https://github.com/unixfox/antiCaptchaResolver", description: "Kolejny solver CAPTCHA." },
        { name: "Hoxx VPN Proxy", url: "https://www.hoxx.com/", description: "Darmowy VPN w przeglądarce." },
        { name: "SetupVPN", url: "https://www.setupvpn.com/", description: "Lifetime darmowy VPN." },
        { name: "Windscribe", url: "https://windscribe.com/browser-extensions", description: "VPN z darmowym limitem 10GB." },
        { name: "ModHeader", url: "https://modheader.com/", description: "Modyfikuje nagłówki HTTP." },
        { name: "Requestly", url: "https://requestly.io/", description: "Modyfikuje żądania HTTP i przekierowania." },
        { name: "LibRedirect", url: "https://github.com/libredirect/libredirect", description: "Przekierowuje na prywatne alternatywy serwisów." },
        { name: "Privacy Redirect", url: "https://github.com/SimonBrazell/privacy-redirect", description: "Przekierowuje na prywatne frontendy." },
        { name: "Alternative Front-ends", url: "https://github.com/mendel5/alternative-front-ends", description: "Lista alternatywnych frontendów." },
        { name: "Redirector", url: "https://github.com/einaregilsson/Redirector", description: "Automatyczne przekierowania URL." },
        { name: "Skip Redirect", url: "https://github.com/sblask-webextensions/webextension-skip-redirect", description: "Pomija strony przekierowujące." },
        { name: "Request Control", url: "https://github.com/tumpio/requestcontrol", description: "Kontrola nad żądaniami HTTP." },
        { name: "Unclickable", url: "https://github.com/Unclickable/unclickable-extension", description: "Odblokuj kopiowanie i zaznaczanie." },
        { name: "Allow Copy", url: "https://github.com/iamadamdev/extensions", description: "Włącza kopiowanie na stronach które to blokują." }
      ]
    },
    {
      id: "pobieranie-zarzadzanie",
      title: "📥 Pobieranie i Zarządzanie",
      links: [
        { name: "DownThemAll!", url: "https://www.downthemall.org/", description: "Potężny menadżer pobierania." },
        { name: "Video DownloadHelper", url: "https://github.com/FlareSolverr/FlareSolverr", description: "Pobiera wideo z większości stron." },
        { name: "Image Downloader", url: "https://www.download-helper.net/", description: "Masowe pobieranie obrazów ze strony." },
        { name: "Save All Resources", url: "https://chrome.google.com/webstore/detail/save-all-resources/abpdnfjocnmdomablahdcfnoggeeiedb", description: "Zapisuje wszystkie zasoby strony." },
        { name: "SingleFile", url: "https://www.httrack.com/page/2/en/index.html", description: "Zapisuje całą stronę w jednym pliku HTML." },
        { name: "SingleFileZ", url: "https://github.com/gildas-lormeau/SingleFileZ", description: "Zapisuje strony jako pliki ZIP." },
        { name: "Webrecorder", url: "https://webrecorder.net/", description: "Archiwizuje interaktywne strony." },
        { name: "Print Friendly & PDF", url: "https://addons.mozilla.org/en-US/firefox/addon/print-friendly-pdf/", description: "Czyści strony przed drukowaniem/PDF." },
        { name: "Web Archives", url: "https://github.com/dessant/web-archives", description: "Szuka zarchiwizowanych wersji stron." },
        { name: "Archiveror", url: "https://github.com/rahiel/archiveror", description: "Archiwizuje strony w Archive.org." },
        { name: "Percollate", url: "https://github.com/danburzo/percollate", description: "Konwertuje strony na czytelne PDF." },
        { name: "OneTab", url: "https://www.one-tab.com/", description: "Konwertuje wszystkie karty na listę." },
        { name: "Tab Manager Plus", url: "https://github.com/alyssaxuu/flowy", description: "Zaawansowane zarządzanie kartami." },
        { name: "Dual Column", url: "https://github.com/dualcolumn/dualcolumn-web-extension", description: "Dzieli ekran na dwie kolumny." },
        { name: "Search by Image", url: "https://github.com/dessant/search-by-image", description: "Wyszukiwanie obrazem w wielu wyszukiwarkach." },
        { name: "Download Manager", url: "https://github.com/Bowen7/regex-vis", description: "Prosty menadżer pobierania." },
        { name: "ZIP Download", url: "https://github.com/stefansundin/zip-download", description: "Pobiera wiele plików jako ZIP." },
        { name: "Bulk Media Downloader", url: "https://github.com/inbasic/bulk-media-downloader", description: "Masowe pobieranie mediów." },
        { name: "Save as MHTML", url: "https://github.com/brian-girko/save-as-mhtml", description: "Zapisuje strony jako MHTML." },
        { name: "Save as MHT", url: "https://github.com/vsDizzy/SaveAsMHT", description: "Zapisuje kompletne strony." }
      ]
    },
    {
      id: "reddit-social-media",
      title: "🎨 Reddit i Social Media",
      links: [
        { name: "Reddit Enhancement Suite", url: "https://redditenhancementsuite.com/", description: "Niezbędne rozszerzenie dla Reddita." },
        { name: "Old Reddit Redirect", url: "https://github.com/tom-james-watson/old-reddit-redirect", description: "Zawsze używa old.reddit.com." },
        { name: "Reddit Moderator Toolbox", url: "https://github.com/honestbleeps/Reddit-Enhancement-Suite", description: "Narzędzia dla moderatorów." },
        { name: "Old Twitter Layout", url: "https://github.com/ClearlyClaire/old-twitter-layout", description: "Przywraca stary wygląd Twittera." },
        { name: "Eight Dollars", url: "https://github.com/wseagar/eight-dollars", description: "Pokazuje kto zapłacił za Twitter Blue." },
        { name: "OldTwitter", url: "https://github.com/dimdenGD/OldTwitter", description: "Klasyczny wygląd Twittera." },
        { name: "Facebook Container", url: "https://facebookcontainer.com/", description: "Izoluje Facebook od reszty sieci." },
        { name: "FB Purity", url: "https://www.fbpurity.com/", description: "Czyści Facebook z śmieci." },
        { name: "Google Unlocked", url: "https://github.com/Ibit-to/google-unlocked", description: "Odblokowuje ukryte wyniki Google." },
        { name: "Search by Image", url: "https://github.com/dessant/search-by-image", description: "Wyszukiwanie obrazem w wielu wyszukiwarkach." },
        { name: "Startpage Privacy Protection", url: "https://www.startpage.com/en/privacy-please/startpage-extension", description: "Prywatne wyszukiwanie." },
        { name: "DuckDuckGo Privacy Essentials", url: "https://duckduckgo.com/app", description: "Blokuje trackery i wymusza szyfrowanie." },
        { name: "Twemoji", url: "https://github.com/twitter/twemoji", description: "Twitter emoji wszędzie." },
        { name: "Nitter Redirect", url: "https://github.com/zedeus/nitter", description: "Przekierowuje Twitter na Nitter." },
        { name: "Reddit Masstagger", url: "https://github.com/ccomeaux/BoardGameRadar", description: "Taguje użytkowników Reddita." },
        { name: "Distraction Free Instagram", url: "https://github.com/MobileFirstLLC/social-media-hacker-list", description: "Usuwa rozpraszacze z Instagrama." },
        { name: "Tweaks for Twitter", url: "https://github.com/jbmagination/Tweaks-for-Twitter", description: "Usprawnienia dla Twittera." },
        { name: "Better TweetDeck", url: "https://github.com/sreechar/TweetDeck-Enhancer", description: "Ulepsza TweetDeck." },
        { name: "TweetDeck Enhancer", url: "https://github.com/eramdam/BetterTweetDeck", description: "Dodaje funkcje do TweetDeck." },
        { name: "Reddit Sidebar Hider", url: "https://github.com/Kiuryy/Bookmark_Sidebar", description: "Ukrywa sidebar na Reddit." }
      ]
    },
    {
      id: "narzedzia-deweloperskie",
      title: "🛠️ Narzędzia Deweloperskie",
      links: [
        { name: "Wappalyzer", url: "https://www.wappalyzer.com/", description: "Identyfikuje technologie używane na stronach." },
        { name: "ColorZilla", url: "https://www.colorzilla.com/", description: "Próbnik kolorów i generator gradientów." },
        { name: "Lighthouse", url: "https://github.com/GoogleChrome/lighthouse", description: "Audyt wydajności stron." },
        { name: "JSON Viewer", url: "https://jsonview.com/", description: "Formatuje i koloruje JSON." },
        { name: "EditThisCookie", url: "https://www.editthiscookie.com/", description: "Menadżer ciasteczek." },
        { name: "Fonts Ninja", url: "https://fontface.ninja/", description: "Identyfikuje czcionki na stronach." },
        { name: "WhatFont", url: "https://www.whatfont.co/", description: "Łatwa identyfikacja czcionek." },
        { name: "User-Agent Switcher", url: "https://github.com/fcapano/User-Agent-Switcher", description: "Zmienia user agent przeglądarki." },
        { name: "Web Developer", url: "https://github.com/microsoft/PowerToys", description: "Zestaw narzędzi dla web developerów." },
        { name: "Pesticide", url: "https://pesticide.io/", description: "Pokazuje kontury elementów CSS." },
        { name: "Refined GitHub", url: "https://github.com/sindresorhus/refined-github", description: "Upraszcza interfejs GitHub." },
        { name: "Octotree", url: "https://github.com/ovity/octotree", description: "Drzewo plików dla GitHub." },
        { name: "OctoLinker", url: "https://github.com/OctoLinker/OctoLinker", description: "Linkuje zależności w kodzie na GitHub." },
        { name: "GitHunt", url: "https://github.com/kamranahmedse/githunt", description: "Trendy z GitHub na nowej karcie." },
        { name: "GitHub Hovercard", url: "https://github.com/Justineo/github-hovercard", description: "Podgląd użytkowników i repozytoriów." },
        { name: "Wide GitHub", url: "https://github.com/xthexder/wide-github", description: "Szerszy interfejs GitHub." },
        { name: "Lovely Forks", url: "https://github.com/musically-ut/lovely-forks", description: "Pokazuje popularne forki." },
        { name: "GitHub VSCode Icons", url: "https://github.com/dderevjanik/github-vscode-icons", description: "Ikony VS Code na GitHub." },
        { name: "GitHub Dark Theme", url: "https://github.com/StylishThemes/GitHub-Dark", description: "Ciemny motyw dla GitHub." },
        { name: "BuiltWith", url: "https://github.com/allstarschh/Firefox-Extension-BuiltWith", description: "Technologie użyte na stronie." }
      ]
    },
    {
      id: "produktywnosc-organizacja",
      title: "📝 Produktywność i Organizacja",
      links: [
        { name: "Notion Web Clipper", url: "https://www.notion.so/web-clipper", description: "Zapisuje strony do Notion." },
        { name: "Todoist", url: "https://todoist.com/downloads/extensions", description: "Szybkie dodawanie zadań." },
        { name: "Grammarly", url: "https://www.grammarly.com/", description: "Sprawdza gramatykę i pisownię." },
        { name: "LanguageTool", url: "https://www.languagetool.org/", description: "Darmowa alternatywa Grammarly." },
        { name: "LastPass", url: "https://www.lastpass.com/", description: "Menadżer haseł." },
        { name: "Bitwarden", url: "https://bitwarden.com/", description: "Open source menadżer haseł." },
        { name: "KeePass", url: "https://keepass.info/", description: "Darmowy menadżer haseł." },
        { name: "Raindrop.io", url: "https://raindrop.io/", description: "Inteligentne zakładki." },
        { name: "Instapaper", url: "https://www.instapaper.com/", description: "Zapisz do przeczytania później." },
        { name: "Pocket", url: "https://getpocket.com/", description: "Zapisuje artykuły na później." },
        { name: "Evernote Web Clipper", url: "https://www.evernote.com/webclipper", description: "Zapisuje strony do Evernote." },
        { name: "Obsidian Web Clipper", url: "https://obsidian.md/", description: "Zapisuje do Obsidian." },
        { name: "Universal Web Clipper", url: "https://github.com/webclipper/web-clipper", description: "Zapisuje do wielu serwisów." },
        { name: "Bookmark Organizer", url: "https://github.com/mdn/webextension-examples", description: "Organizuje zakładki." },
        { name: "PDF Viewer", url: "https://github.com/jhiesey/pdfjs", description: "Wbudowany czytnik PDF." },
        { name: "Save as eBook", url: "https://github.com/alexadam/save-as-ebook", description: "Zapisuje strony jako eBook." },
        { name: "Bookmark Sidebar", url: "https://github.com/Kiuryy/Bookmark_Sidebar", description: "Sidebar z zakładkami." },
        { name: "Session Manager", url: "https://github.com/PleaseDontKillMe/Sessionic", description: "Zarządza sesjami przeglądarki." },
        { name: "Sidebery", url: "https://github.com/mbnuqw/sidebery", description: "Pionowe karty w sidebarze." },
        { name: "Tree Style Tab", url: "https://github.com/piroor/treestyletab", description: "Karty w formie drzewa." }
      ]
    },
    {
      id: "gaming-streaming",
      title: "🎮 Gaming i Streaming",
      links: [
        { name: "FrankerFaceZ", url: "https://www.frankerfacez.com/", description: "Emotki i ulepszenia dla Twitch." },
        { name: "BetterTTV", url: "https://betterttv.com/", description: "Więcej emotek na Twitch i YouTube." },
        { name: "7TV", url: "https://7tv.app/", description: "Jeszcze więcej emotek dla Twitch." },
        { name: "Twitch Ad Solutions", url: "https://github.com/pixeltris/TwitchAdSolutions", description: "Blokuje reklamy na Twitch." },
        { name: "Purple AdBlock", url: "https://github.com/saucenaopls/Purple-adblock", description: "Alternatywny bloker dla Twitch." },
        { name: "Augmented Steam", url: "https://www.augmented-steam.com/", description: "Ulepsza stronę Steam." },
        { name: "SteamDB", url: "https://steamdb.info/extension/", description: "Dodaje dane z SteamDB do Steam." },
        { name: "IsThereAnyDeal", url: "https://es.isthereanydeal.com/", description: "Porównuje ceny gier." },
        { name: "Epic Games Freebies", url: "https://github.com/Revadike/epicgames-freebies-claimer", description: "Automatycznie odbiera darmowe gry." },
        { name: "Steam Database", url: "https://github.com/SteamDatabase/BrowserExtension", description: "Integracja SteamDB ze Steam." },
        { name: "Steam Inventory Helper", url: "https://steamcommunity.com/groups/SteamInventoryHelper", description: "Zarządzanie ekwipunkiem Steam." },
        { name: "CRX Viewer", url: "https://github.com/Rob--W/crxviewer", description: "Podgląd kodu rozszerzeń." },
        { name: "nightTab", url: "https://github.com/zombieFox/nightTab", description: "Personalizowana strona nowej karty." },
        { name: "Twitch NoSub", url: "https://github.com/Poolitzer/TwitchNoSub", description: "Ukrywa elementy dla subskrybentów." },
        { name: "Twitch Previews", url: "https://github.com/pwltr/twitch-previews", description: "Podgląd streamów na hover." },
        { name: "Twitch Auto Claim", url: "https://github.com/saucettv/WorkerHelper", description: "Automatycznie odbiera punkty." },
        { name: "Global Twitch Emotes", url: "https://github.com/mikeyaworski/Twitch-Chat-Emotes", description: "Emotki Twitch wszędzie." },
        { name: "TTV Tools", url: "https://github.com/Nerixyz/ttv-tools", description: "Zestaw narzędzi dla Twitch." },
        { name: "Alternative Twitch Player", url: "https://github.com/crackededed/Xtra", description: "Alternatywny odtwarzacz Twitch." },
        { name: "Auto Chess Helper", url: "https://github.com/antosubash/AbemaTVChromeExtension", description: "Pomocnik do Auto Chess." }
      ]
    },
    {
      id: "narzedzia-uzytkowe",
      title: "🔧 Narzędzia Użytkowe",
      links: [
        { name: "Violentmonkey", url: "https://violentmonkey.github.io/", description: "Manager skryptów użytkownika." },
        { name: "Tampermonkey", url: "https://www.tampermonkey.net/", description: "Najpopularniejszy manager userscripts." },
        { name: "Greasemonkey", url: "https://www.greasespot.net/", description: "Oryginalny manager skryptów." },
        { name: "Stylus", url: "https://github.com/openstyles/stylus", description: "Manager stylów CSS." },
        { name: "Dark Reader", url: "https://darkreader.org/", description: "Ciemny motyw dla każdej strony." },
        { name: "Vimium", url: "https://github.com/philc/vimium", description: "Nawigacja klawiaturą jak w Vim." },
        { name: "Surfingkeys", url: "https://github.com/brookhong/Surfingkeys", description: "Skróty klawiszowe do wszystkiego." },
        { name: "Imagus", url: "https://imagus.app/", description: "Powiększa obrazy po najechaniu." },
        { name: "Hover Zoom+", url: "https://chrome.google.com/webstore/detail/hover-zoom%2B/pccckmaobkjjboncdfnnofkonhgpceea", description: "Powiększanie obrazów na hover." },
        { name: "Pushbullet", url: "https://www.pushbullet.com/", description: "Synchronizacja między urządzeniami." },
        { name: "Google Translate", url: "https://translate.google.com/intl/en/about/", description: "Tłumaczenie stron i tekstów." },
        { name: "Immersive Translate", url: "https://github.com/immersive-translate/immersive-translate", description: "Dwujęzyczne tłumaczenie stron." },
        { name: "10ten Japanese Reader", url: "https://github.com/10ten-me/10ten-ja-reader", description: "Tłumacz japoński na hover." },
        { name: "Rikaikun", url: "https://github.com/rikai/rikai-kun", description: "Słownik japoński." },
        { name: "Enable Right Click", url: "https://github.com/Unclickable/unclickable-extension", description: "Odblokowuje prawy przycisk myszy." },
        { name: "Behind The Overlay", url: "https://github.com/mdn/webextensions-examples", description: "Usuwa nakładki ze stron." },
        { name: "CyberChef Extension", url: "https://github.com/gchq/CyberChef", description: "Narzędzia do kodowania/dekodowania." },
        { name: "DeArrow", url: "https://github.com/ajayyy/DeArrow", description: "Usuwa clickbait z YouTube." },
        { name: "Scroll To Top", url: "https://github.com/lindylex/Scroll_To_Top", description: "Szybki przewijanie do góry." },
        { name: "Auto Refresh", url: "https://github.com/KamalDGRT/TickTick-Extension", description: "Automatyczne odświeżanie stron." }
      ]
    },
    {
      id: "media-rozrywka",
      title: "🎬 Media i Rozrywka",
      links: [
        { name: "Substital", url: "https://www.substital.com/", description: "Dodaje napisy do wideo online." },
        { name: "Subtitle for Netflix", url: "https://github.com/gignac-cha/subtitle-for-netflix", description: "Własne napisy w Netflix." },
        { name: "Super Netflix", url: "https://github.com/super-netflix/super-netflix", description: "Ulepsza interfejs Netflix." },
        { name: "Netflix 1080p", url: "https://github.com/ranisalt/netflix-1080p", description: "Wymusza 1080p na Netflix." },
        { name: "Ratings Preview", url: "https://www.ratingsextension.com/", description: "Pokazuje oceny IMDb na Netflix." },
        { name: "Letterboxd Userscript", url: "https://github.com/cvzi/Letterboxd-userscript", description: "Integracja z Letterboxd." },
        { name: "Traktr", url: "https://github.com/k4l3b/TraktRoller", description: "Scrobbluje do Trakt.tv." },
        { name: "JustWatch Buttons", url: "https://github.com/freaktechnik/justwatch-buttons", description: "Dodaje przyciski JustWatch." },
        { name: "Bilibili Subtitle", url: "https://github.com/Tsuk1ko/bilibili-subtitle", description: "Napisy dla Bilibili." },
        { name: "Bilibili Helper", url: "https://github.com/ipcjs/bilibili-helper", description: "Ulepsza Bilibili." },
        { name: "Audible Helper", url: "https://github.com/kodxana/OpenAudible", description: "Dodatki dla Audible." },
        { name: "Web Scrobbler", url: "https://github.com/web-scrobbler/web-scrobbler", description: "Scrobbluje muzykę do Last.fm." },
        { name: "MAL-Sync", url: "https://github.com/Animeboynz/Anime-Web-Extension", description: "Synchronizuje postęp anime." },
        { name: "MAL Cover CSS", url: "https://github.com/Trinovantes/MAL-Cover-CSS", description: "Ulepsza MyAnimeList." },
        { name: "MALSync Official", url: "https://github.com/MALSync/MALSync", description: "Oficjalna synchronizacja MAL." },
        { name: "Anime Skip Player", url: "https://github.com/anime-skip/player", description: "Pomija opening/ending w anime." },
        { name: "Better Crunchyroll", url: "https://github.com/LelouchFR/better-crunchyroll", description: "Ulepsza Crunchyroll." },
        { name: "Improve Crunchyroll", url: "https://github.com/ThomasTavernier/Improve-Crunchyroll", description: "Więcej ulepszeń Crunchyroll." },
        { name: "Crunchyroll Plus", url: "https://github.com/destroyerpro/Crunchyroll-Plus", description: "Dodatkowe funkcje Crunchyroll." },
        { name: "Kitsu Enhancer", url: "https://github.com/Pitu/Kitsu-Enhancer", description: "Ulepsza Kitsu.io." }
      ]
    },
    {
      id: "bezpieczenstwo",
      title: "🛡️ Bezpieczeństwo",
      links: [
        { name: "Malwarebytes Browser Guard", url: "https://www.malwarebytes.com/browserguard", description: "Blokuje malware i scamy." },
        { name: "Avast Online Security", url: "https://www.avast.com/en-us/avast-online-security", description: "Sprawdza reputację stron." },
        { name: "Bitdefender TrafficLight", url: "https://www.bitdefender.com/solutions/trafficlight.html", description: "Blokuje niebezpieczne strony." },
        { name: "VT4Browsers", url: "https://www.virustotal.com/gui/home/upload", description: "Skanuje linki przez VirusTotal." },
        { name: "Hybrid Analysis", url: "https://www.joesandbox.com/", description: "Analizuje podejrzane pliki." },
        { name: "Have I Been Pwned", url: "https://haveibeenpwned.com/", description: "Sprawdza wycieki danych." },
        { name: "Click&Clean", url: "https://clickclean.online/", description: "Czyści dane przeglądania." },
        { name: "HTTPS Everywhere", url: "https://www.eff.org/https-everywhere", description: "Wymusza połączenia HTTPS." },
        { name: "Clean Links", url: "https://github.com/Cimbali/CleanLinks", description: "Usuwa przekierowania." },
        { name: "Block Google Analytics", url: "https://github.com/M-Reimer/no-google-analytics", description: "Blokuje Google Analytics." },
        { name: "Smart HTTPS", url: "https://github.com/escapewindow/Smart-HTTPS", description: "Automatyczne HTTPS." },
        { name: "Privacy Possum", url: "https://www.eff.org/pages/badger-faq", description: "Agresywne blokowanie trackerów." },
        { name: "Password Alert", url: "https://github.com/FriendsOfGalaxy/galaxy-integration-steam", description: "Ostrzega przed phishingiem." },
        { name: "JavaScript Restrictor", url: "https://github.com/gorhill/uBlock-for-firefox-legacy", description: "Ogranicza JavaScript APIs." },
        { name: "Browser Fingerprinting", url: "https://github.com/fingerprint-suite/browser-fingerprinting", description: "Zapobiega fingerprintingowi." },
        { name: "Font Fingerprint Defender", url: "https://github.com/Synzvato/decentraleyes", description: "Chroni przed font fingerprinting." },
        { name: "WebRTC Leak Prevent", url: "https://github.com/aghorler/WebRTC-Leak-Prevent", description: "Zapobiega wyciekom WebRTC." },
        { name: "AudioContext Fingerprint Defender", url: "https://github.com/Chris-Bitler/twitch-filtered-chat", description: "Chroni przed audio fingerprinting." },
        { name: "WebGL Fingerprint Defender", url: "https://github.com/nikrolls/uBlock-Edge", description: "Chroni przed WebGL fingerprinting." },
        { name: "Amazon Container", url: "https://github.com/stoically/contain-amazon", description: "Izoluje Amazon jak Facebook Container." }
      ]
    },
    {
      id: "specjalistyczne-niszowe",
      title: "🎯 Specjalistyczne i Niszowe",
      links: [
        { name: "Tridactyl", url: "https://github.com/tridactyl/tridactyl", description: "Vim dla Firefox." },
        { name: "Vim Vixen", url: "https://github.com/ueokande/vim-vixen", description: "Kolejny Vim dla Firefox." },
        { name: "Link Hints", url: "https://github.com/lydell/LinkHints", description: "Szybka nawigacja linkami." },
        { name: "Saka Key", url: "https://github.com/lusakasa/saka-key", description: "Skróty klawiszowe wszędzie." },
        { name: "Shortkeys", url: "https://github.com/cmcaine/tridactyl", description: "Własne skróty klawiszowe." },
        { name: "History AutoDelete", url: "https://github.com/1History/1History", description: "Automatyczne czyszczenie historii." },
        { name: "History Merger", url: "https://github.com/lucaseverini/Firefox-History-Merger", description: "Łączy historię z różnych profili." },
        { name: "Gesturefy", url: "https://github.com/Robbendebiene/Gesturefy", description: "Gesty myszy." },
        { name: "smartUp Gestures", url: "https://github.com/Simounet/lilo-plus", description: "Gesty i skróty." },
        { name: "Space Pirate", url: "https://github.com/foooomio/space-pirate", description: "Usuwa zbędne spacje." },
        { name: "Copy Text Link", url: "https://github.com/dessant/copy-text-link", description: "Kopiuje link z tekstem." },
        { name: "Emoji Substitution", url: "https://github.com/mdn/webextensions-examples/tree/master/emoji-substitution", description: "Automatyczne emoji." },
        { name: "Offline QR Code Generator", url: "https://github.com/rugk/offline-qr-code", description: "Generuje kody QR offline." },
        { name: "Quick Note", url: "https://github.com/mdn/webextensions-examples/tree/master/quicknote", description: "Szybkie notatki." },
        { name: "Copy On Select", url: "https://github.com/Robbendebiene/Copy-On-Select", description: "Automatyczne kopiowanie zaznaczenia." },
        { name: "Clippings", url: "https://github.com/aecreations/clippings", description: "Zarządza szablonami tekstu." },
        { name: "Bookmark All Tabs", url: "https://github.com/dralletje/Bookmark-All-Tabs", description: "Dodaje wszystkie karty do zakładek." },
        { name: "Witchcraft", url: "https://github.com/luciopaiva/witchcraft", description: "Lokalne skrypty JS i CSS." },
        { name: "UserCSS", url: "https://github.com/openstyles/stylus/wiki/Usercss", description: "Własne style CSS." },
        { name: "GitHub Userscripts", url: "https://github.com/Mottie/GitHub-userscripts", description: "Kolekcja skryptów dla GitHub." }
      ]
    },
    {
      id: "eksperymentalne-beta",
      title: "🔮 Eksperymentalne i Beta",
      links: [
        { name: "Memex", url: "https://github.com/WorldBrain/Memex", description: "Organizuje wiedzę z internetu." },
        { name: "Hypothesis", url: "https://github.com/hypothesis/browser-extension", description: "Adnotacje na stronach." },
        { name: "Mind Map Tab", url: "https://github.com/oliver-moran/mind-map", description: "Mapy myśli w przeglądarce." },
        { name: "Peek", url: "https://github.com/peek-dev/peek", description: "Podgląd linków bez otwierania." },
        { name: "Tab Organizer", url: "https://github.com/Pauan/tab-organizer", description: "Zaawansowane zarządzanie kartami." },
        { name: "Offline First", url: "https://github.com/kesselborn/offline-first", description: "Zapisuje strony offline." },
        { name: "Side by Side", url: "https://github.com/JuanitoFatas/side-by-side", description: "Porównuje strony obok siebie." },
        { name: "Firefox Notes", url: "https://github.com/mozilla/notes", description: "Synchronizowane notatki." },
        { name: "Voice Fill", url: "https://github.com/mozilla/voice-web", description: "Wypełnianie głosem." },
        { name: "Side View", url: "https://github.com/mozilla/side-view", description: "Mobilny widok obok." },
        { name: "Cliqz", url: "https://github.com/cliqz-oss/browser-core", description: "Prywatne wyszukiwanie." },
        { name: "Hyphenopoly", url: "https://github.com/Hyphenopoly/Hyphenopoly", description: "Dzielenie wyrazów." },
        { name: "Markdown Here", url: "https://github.com/adam-p/markdown-here", description: "Pisanie w Markdown wszędzie." },
        { name: "Web Highlights", url: "https://github.com/noembryo/KoHighlights", description: "Zaznaczanie na stronach." },
        { name: "Storex Sync", url: "https://github.com/WorldBrain/storex-sync", description: "Synchronizacja danych." },
        { name: "Floccus", url: "https://github.com/floccusaddon/floccus", description: "Synchronizuje zakładki z chmurą." },
        { name: "OwnCloud Bookmarks", url: "https://github.com/owncloud/bookmarks", description: "Zakładki w OwnCloud." },
        { name: "Shiori", url: "https://github.com/go-shiori/shiori-web-ext", description: "Prosty menadżer zakładek." },
        { name: "Web Clipper Collector", url: "https://github.com/webclipper/web-clipper-browser-extension", description: "Zbiera informacje ze stron." },
        { name: "Powerlet", url: "https://github.com/anthonyec/powerlet", description: "Bookmarklety na sterydach." }
      ]
    }
  ],
  infoBoxes: [
    {
      type: 'info',
      title: '💡 Wskazówka',
      items: [
        "Nie instaluj zbyt wielu rozszerzeń naraz - mogą spowalniać przeglądarkę. Wybierz tylko te, których naprawdę potrzebujesz. Pamiętaj też o regularnych aktualizacjach! Dla maksymalnej prywatności polecamy: uBlock Origin + Privacy Badger + ClearURLs + LocalCDN."
      ]
    },
    {
      type: 'warning',
      title: '⚠️ Uwaga',
      items: [
        "Zawsze sprawdzaj uprawnienia rozszerzeń przed instalacją. Unikaj rozszerzeń z podejrzanie małą liczbą użytkowników lub złymi recenzjami. Pobieraj rozszerzenia tylko z oficjalnych źródeł (Chrome Web Store, Firefox Add-ons)."
      ]
    }
  ]
};