const pageData = {
    "featured": {
        "title": "🏆 Polecane Narzędzia Wideo",
        "links": [
            {
                "title": "yt-dlp",
                "description": "Niezastąpione narzędzie linii komend do pobierania wideo z setek stron. Potężne i elastyczne.",
                "url": "https://github.com/yt-dlp/yt-dlp",
                "badge": "Pobieranie"
            },
            {
                "title": "OBS Studio",
                "description": "Standard branżowy do nagrywania ekranu i streamingu. Darmowy, open-source i niezwykle konfigurowalny.",
                "url": "https://obsproject.com/",
                "badge": "Nagrywanie"
            },
            {
                "title": "HandBrake",
                "description": "Wszechstronny transkoder wideo. Idealny do konwersji formatów i zmniejszania rozmiaru plików.",
                "url": "https://handbrake.fr/",
                "badge": "Konwersja"
            },
            {
                "title": "VLC Media Player",
                "description": "Odtwarza wszystko. Legendarny odtwarzacz multimedialny, który obsługuje niemal każdy format.",
                "url": "https://www.videolan.org/",
                "badge": "Odtwarzacz"
            }
        ]
    },
    "sections": [
        {
            "id": "pobieranie-wideo",
            "title": "📥 Pobieranie Wideo",
            "links": [
                { "name": "9xbuddy", "url": "https://9xbuddy.com/", "tag": "⭐ Online" },
                { "name": "CD(R)M-Project", "url": "https://cdm-project.com/explore/repos", "tag": "DRM" },
                { "name": "cobalt", "url": "https://cobalt.tools/", "tag": "⭐ Online" },
                { "name": "FetchV", "url": "https://fetchv.net/", "tag": "Rozszerzenie" },
                { "name": "GetWVKeys", "url": "https://getwvkeys.cc/", "tag": "DRM" },
                { "name": "Hitomi Downloader", "url": "https://github.com/KurtBestor/Hitomi-Downloader" },
                { "name": "hls extension", "url": "https://webextension.org/listing/hls-downloader.html", "tag": "HLS" },
                { "name": "hls-downloader", "url": "https://github.com/puemos/hls-downloader", "tag": "HLS" },
                { "name": "hlsloader", "url": "https://www.hlsloader.com/", "tag": "HLS" },
                { "name": "MPMux", "url": "https://mpmux.com/", "tag": "Rozszerzenie" },
                { "name": "Musvkrobot", "url": "https://t.me/musvkrobot", "tag": "Telegram" },
                { "name": "myfaveTT", "url": "https://myfavett.com/", "tag": "TikTok" },
                { "name": "Piner", "url": "https://piner.io/", "tag": "Pinterest" },
                { "name": "SCrawler", "url": "https://github.com/AAndyProgram/SCrawler" },
                { "name": "SSSTik", "url": "https://ssstik.io/", "tag": "TikTok" },
                { "name": "Threads Downloader", "url": "https://threadsdownloader.com/", "tag": "Threads" },
                { "name": "tiktok-to-ytdlp", "url": "https://github.com/Dinoosauro/tiktok-to-ytdlp", "tag": "TikTok" },
                { "name": "Video DownloadHelper", "url": "https://www.downloadhelper.net/", "tag": "⭐ Rozszerzenie" },
                { "name": "VideoFK", "url": "https://www.videofk.com/", "tag": "Online" },
                { "name": "YTDL-PATCHED", "url": "https://github.com/ytdl-patched/ytdl-patched", "tag": "CLI" },
                { "name": "you-get", "url": "https://you-get.org/", "tag": "CLI" },
                { "name": "yt-dlp", "url": "https://github.com/yt-dlp/yt-dlp", "tag": "⭐ CLI" }
            ]
        },
        {
            "id": "edycja-wideo",
            "title": "🎬 Edycja Wideo",
            "links": [
                { "name": "Auto-Editor", "url": "https://auto-editor.com/", "tag": "CLI" },
                { "name": "Avidemux", "url": "http://fixounet.free.fr/avidemux/" },
                { "name": "avisynth", "url": "http://avisynth.nl/index.php/Main_Page" },
                { "name": "Convert2Video", "url": "https://convert2video.com/", "tag": "Online" },
                { "name": "Crop Video", "url": "https://crop-video.com/", "tag": "Online" },
                { "name": "Crossfade", "url": "https://crossfade.io/", "tag": "Online" },
                { "name": "DaVinci Resolve", "url": "https://www.blackmagicdesign.com/products/davinciresolve", "tag": "⭐ Na komputer" },
                { "name": "EZVid", "url": "https://www.ezvid.com/" },
                { "name": "FreeMoCap", "url": "https://freemocap.org/" },
                { "name": "kdenlive", "url": "https://kdenlive.org/en/", "tag": "⭐ Na komputer" },
                { "name": "Kurku", "url": "https://app.kurku.tech/" },
                { "name": "Lightworks", "url": "https://lwks.com/" },
                { "name": "LoopVid", "url": "https://loopvid.kastden.org/", "tag": "Online" },
                { "name": "LosslessCut", "url": "https://github.com/mifi/lossless-cut", "tag": "⭐ Na komputer" },
                { "name": "Mastershot", "url": "https://mastershot.app/", "tag": "⭐ Online" },
                { "name": "MoviePy", "url": "https://zulko.github.io/moviepy/", "tag": "Python" },
                { "name": "Olive", "url": "https://www.olivevideoeditor.org/" },
                { "name": "Omniclip", "url": "https://omniclip.app/", "tag": "Online" },
                { "name": "OpenRV", "url": "https://github.com/AcademySoftwareFoundation/OpenRV" },
                { "name": "OpenShot", "url": "https://www.openshot.org/" },
                { "name": "Opus", "url": "https://www.opus.pro/" },
                { "name": "Panzoid", "url": "https://panzoid.com/", "tag": "Online" },
                { "name": "Pikimov", "url": "https://pikimov.com/", "tag": "⭐ Online" },
                { "name": "Pitivi", "url": "https://www.pitivi.org/" },
                { "name": "Remotion", "url": "https://www.remotion.dev/" },
                { "name": "Shotcut", "url": "https://shotcut.org/", "tag": "⭐ Na komputer" },
                { "name": "Source Filmmaker", "url": "https://store.steampowered.com/app/1840/Source_Filmmaker/" },
                { "name": "suckless-cut", "url": "https://github.com/couleur-tweak-tips/suckless-cut" },
                { "name": "VapourSynth", "url": "https://www.vapoursynth.com/" },
                { "name": "vidcutter", "url": "https://github.com/ozmartian/vidcutter" },
                { "name": "Video Cutter", "url": "https://video-cutter-js.com/", "tag": "Online" },
                { "name": "Video2Edit", "url": "https://www.video2edit.com/", "tag": "Online" },
                { "name": "VideoCandy", "url": "https://videocandy.com/", "tag": "Online" },
                { "name": "Vididoo", "url": "https://vididoo.vercel.app/", "tag": "Online" },
                { "name": "VidLouder", "url": "https://www.videolouder.com/", "tag": "Online" },
                { "name": "vidmix", "url": "https://vidmix.app/", "tag": "Online" },
                { "name": "Visla", "url": "https://www.visla.us/" },
                { "name": "VSDC", "url": "https://www.videosoftdev.com/" },
                { "name": "Webm Generator", "url": "https://github.com/dfaker/WebmGenerator" },
                { "name": "wide.video", "url": "https://wide.video/", "tag": "⭐ Online" },
                { "name": "Windows Movie Maker", "url": "https://www.majorgeeks.com/files/details/windows_movie_maker.html" }
            ]
        },
        {
            "id": "efekty-animacja-i-vfx",
            "title": "✨ Efekty, Animacja i VFX",
            "links": [
                { "name": "3DThis", "url": "https://3dthis.com/" },
                { "name": "AEDownloadPro", "url": "https://aedownloadpro.com/", "tag": "After Effects" },
                { "name": "AERiver", "url": "https://aeriver.com/", "tag": "After Effects" },
                { "name": "AETemp", "url": "https://t.me/AETemp", "tag": "After Effects" },
                { "name": "Animaker", "url": "https://www.animaker.com/" },
                { "name": "Animated Drawings", "url": "https://sketch.metademolab.com/" },
                { "name": "AnimeEffects", "url": "https://github.com/AnimeEffectsDevs/AnimeEffects" },
                { "name": "Aseprite", "url": "https://github.com/aseprite/aseprite" },
                { "name": "BestSnip", "url": "https://bestsnip.com/animation/", "tag": "Online" },
                { "name": "Blender Open Movies", "url": "https://youtube.com/playlist?list=PLav47HAVZMjnTFVZL-aImCQIC0uLZtNCz" },
                { "name": "blur", "url": "https://github.com/f0e/blur", "tag": "Motion Blur" },
                { "name": "Cascadeur", "url": "https://cascadeur.com/" },
                { "name": "Cavalry", "url": "https://cavalry.scenegroup.co/" },
                { "name": "cgplugdump", "url": "https://t.me/cgplugdump" },
                { "name": "cgsoftbox", "url": "https://t.me/cgsoftbox" },
                { "name": "Clipnote Studio", "url": "https://calcium-chan.itch.io/clipnote" },
                { "name": "Dandere2x", "url": "https://github.com/akai-katto/dandere2x" },
                { "name": "Download Pirate", "url": "https://www.downloadpirate.com/" },
                { "name": "Endorphin", "url": "https://rentry.co/FMHYBase64#endorphin" },
                { "name": "Enhancr", "url": "https://github.com/mafiosnik777/enhancr" },
                { "name": "enve", "url": "https://maurycyliebner.github.io/" },
                { "name": "Eyecandy", "url": "https://eyecannndy.com/", "tag": "⭐ Inspiracje" },
                { "name": "FAIR Animated Drawings", "url": "https://fairanimateddrawings.com/site/home" },
                { "name": "flex_cg_vfx", "url": "https://t.me/flex_cg_vfx" },
                { "name": "FliiipBook", "url": "https://www.fliiipbook.com/", "tag": "Online" },
                { "name": "FlipAnim", "url": "https://flipanim.com/" },
                { "name": "Flowframes", "url": "https://nmkd.itch.io/flowframes", "tag": "Interpolacja" },
                { "name": "FootageCrate", "url": "https://footagecrate.com/" },
                { "name": "Fractorium", "url": "http://fractorium.com/" },
                { "name": "FragM", "url": "https://github.com/3Dickulus/FragM" },
                { "name": "FreeVideoEffect", "url": "https://freevideoeffect.com/" },
                { "name": "FreshLUTs", "url": "https://freshluts.com/", "tag": "Filtry LUT" },
                { "name": "Glaxnimate", "url": "https://glaxnimate.mattbas.org/" },
                { "name": "GraphicsGale", "url": "https://graphicsgale.com/us/" },
                { "name": "Gyroflow", "url": "https://gyroflow.xyz/", "tag": "Stabilizacja" },
                { "name": "HunterAE", "url": "https://hunterae.com/", "tag": "After Effects" },
                { "name": "IFSRenderer", "url": "https://github.com/bezo97/IFSRenderer" },
                { "name": "Immersity AI", "url": "https://www.immersity.ai/", "tag": "⭐ AI" },
                { "name": "Intro HD", "url": "https://intro-hd.net/", "tag": "After Effects" },
                { "name": "JWildfire", "url": "https://jwildfire.overwhale.com/" },
                { "name": "JPixel", "url": "https://emad.itch.io/jpixel" },
                { "name": "LibreSprite", "url": "https://libresprite.github.io/" },
                { "name": "LuxCoreRender", "url": "https://luxcorerender.org/" },
                { "name": "Mandelbulber", "url": "https://mandelbulber.com/" },
                { "name": "Mega Scans", "url": "https://quixel.com/megascans" },
                { "name": "Mixamo", "url": "https://www.mixamo.com/" },
                { "name": "Mixer", "url": "https://quixel.com/mixer" },
                { "name": "MMHuman3D", "url": "https://github.com/open-mmlab/mmhuman3d" },
                { "name": "MonsterMash", "url": "https://monstermash.zone/" },
                { "name": "MoonRay", "url": "https://openmoonray.org/" },
                { "name": "MotorPen", "url": "https://motorpen.com/" },
                { "name": "Mutsuacen", "url": "https://mutsuacen.com/" },
                { "name": "OpenColorIO", "url": "https://opencolorio.org/" },
                { "name": "OpenToonz", "url": "https://opentoonz.github.io/e/" },
                { "name": "Pencil2D", "url": "https://www.pencil2d.org/" },
                { "name": "Physically Based", "url": "https://physicallybased.info/" },
                { "name": "Picrew", "url": "https://picrew.me/" },
                { "name": "Plask", "url": "https://plask.ai/", "tag": "Online" },
                { "name": "PlanetSide", "url": "https://planetside.co.uk/" },
                { "name": "ProPainter", "url": "https://github.com/sczhou/ProPainter" },
                { "name": "RenderChan", "url": "https://morevnaproject.org/renderchan/" },
                { "name": "Rive", "url": "https://rive.app/", "tag": "Online" },
                { "name": "ScribbleDiffusion", "url": "https://scribblediffusion.com/" },
                { "name": "ShareAE", "url": "https://www.shareae.com/", "tag": "After Effects" },
                { "name": "Sketch Machine", "url": "https://sketchmachine.net/", "tag": "Online" },
                { "name": "SketchUp", "url": "https://www.sketchup.com/" },
                { "name": "Smoothie", "url": "https://github.com/couleur-tweak-tips/smoothie-rs", "tag": "Motion Blur" },
                { "name": "SpookyGhost", "url": "https://encelo.itch.io/spookyghost" },
                { "name": "Spritesheet Generator", "url": "https://spritesheetgenerator.online/", "tag": "Online" },
                { "name": "Storyboarder", "url": "https://wonderunit.com/storyboarder/" },
                { "name": "SVP", "url": "https://www.svp-team.com/", "tag": "Interpolacja" },
                { "name": "Synfig", "url": "https://www.synfig.org/" },
                { "name": "Talking Face Avatar", "url": "https://github.com/Yazdi9/Talking_Face_Avatar" },
                { "name": "Team V.R releases", "url": "https://rentry.co/FMHYBase64#team-vr" },
                { "name": "TheAnimeScripter", "url": "https://github.com/NevermindNilas/TheAnimeScripter" },
                { "name": "Trangram", "url": "https://www.trangram.com/" },
                { "name": "TupiTube", "url": "https://tupitube.com/" },
                { "name": "Twinmotion", "url": "https://www.twinmotion.com/en-US" },
                { "name": "Unreal Engine", "url": "https://www.unrealengine.com/", "tag": "⭐ Silnik 3D" },
                { "name": "VFXLoot", "url": "https://vfxloot.com/" },
                { "name": "VFXmed", "url": "https://www.vfxmed.com/" },
                { "name": "Video Enhance AI", "url": "https://lrepacks.net/repaki-programm-dlya-grafiki/" },
                { "name": "Video2x", "url": "https://github.com/k4yt3x/video2x" },
                { "name": "VideoColorizerColab", "url": "https://colab.research.google.com/github/jantic/DeOldify/blob/master/VideoColorizerColab.ipynb", "tag": "Koloryzacja" },
                { "name": "VideoCoPilot", "url": "https://www.videocopilot.net/" },
                { "name": "Viggle", "url": "https://viggle.ai/" },
                { "name": "Visual Effects Pack", "url": "https://t.me/visual_effects_pack", "tag": "After Effects" },
                { "name": "Waifu2x GUI", "url": "https://github.com/AaronFeng753/Waifu2x-Extension-GUI", "tag": "⭐ Upscaling" },
                { "name": "Wick Editor", "url": "https://www.wickeditor.com/editor/" }
            ]
        },
        {
            "id": "przetwarzanie-i-kodowanie",
            "title": "⚙️ Przetwarzanie i Kodowanie",
            "links": [
                { "name": "8mb.video", "url": "https://8mb.video/", "tag": "Online" },
                { "name": "archived-things", "url": "https://sometimes-archives-things.github.io/archived-things/", "tag": "⭐ Poradnik" },
                { "name": "autocompressor", "url": "https://autocompressor.net/", "tag": "Online" },
                { "name": "Av1an", "url": "https://github.com/master-of-zen/Av1an" },
                { "name": "Basics to the Art of Remuxing", "url": "https://claraiscute.github.io/Guides/remuxing/", "tag": "⭐ Poradnik" },
                { "name": "Codec Wiki", "url": "https://wiki.x266.mov/", "tag": "Poradnik" },
                { "name": "Compress Video Online", "url": "https://compress-video-online.com/", "tag": "Online" },
                { "name": "DDVT", "url": "https://forum.doom9.org/showthread.php?t=183479" },
                { "name": "FastFlix", "url": "https://fastflix.org/" },
                { "name": "FFmpeg", "url": "https://ffmpeg.org/", "tag": "⭐ Na komputer" },
                { "name": "HandBrake", "url": "https://handbrake.fr/", "tag": "⭐ Na komputer" },
                { "name": "IFME", "url": "https://github.com/Anime4000/IFME" },
                { "name": "MKV Muxing Batch GUI", "url": "https://github.com/yaser01/mkv-muxing-batch-gui" },
                { "name": "MKVToolNix", "url": "https://mkvtoolnix.download/", "tag": "⭐ Na komputer" },
                { "name": "MP4Compress", "url": "https://www.mp4compress.com/", "tag": "Online" },
                { "name": "NEAV1E", "url": "https://github.com/Alkl58/NotEnoughAV1Encodes" },
                { "name": "Restream Tools", "url": "https://restream.io/tools", "tag": "Online" },
                { "name": "Rotato", "url": "https://tools.rotato.app/", "tag": "Online" },
                { "name": "selur", "url": "https://www.selur.de/" },
                { "name": "Shutter Encoder", "url": "https://www.shutterencoder.com/", "tag": "⭐ Na komputer" },
                { "name": "sickbeard_mp4_automator", "url": "https://github.com/mdhiggins/sickbeard_mp4_automator" },
                { "name": "staxrip", "url": "https://github.com/staxrip/staxrip/" },
                { "name": "The Encoding Guide", "url": "https://encoding-guide.neocities.org/", "tag": "Poradnik" },
                { "name": "VERT", "url": "https://vert.sh/", "tag": "Online" },
                { "name": "Video Express Converter", "url": "https://vc.germanov.dev/", "tag": "Online" },
                { "name": "VideoConverter", "url": "https://www.movavi.com/video-converter/", "tag": "Online" },
                { "name": "VideoSmaller", "url": "https://www.videosmaller.com/", "tag": "Online" },
                { "name": "vvdec", "url": "https://github.com/fraunhoferhhi/vvdec" },
                { "name": "VVCEasy", "url": "https://github.com/MartinEesmaa/VVCEasy" },
                { "name": "vvenc", "url": "https://github.com/fraunhoferhhi/vvenc" },
                { "name": "Winnydows", "url": "https://winnydows.com/" },
                { "name": "XMedia Recode", "url": "https://www.xmedia-recode.de/en/" },
                { "name": "YouCompress", "url": "https://www.youcompress.com/", "tag": "Online" }
            ]
        },
        {
            "id": "odtwarzacze-wideo-i-synchronizacja",
            "title": "▶️ Odtwarzacze Wideo i Synchronizacja",
            "links": [
                { "name": "AVPlayer", "url": "http://www.awesomevideoplayer.com/" },
                { "name": "baked.live", "url": "https://baked.live/", "tag": "Sync" },
                { "name": "Caracal Club", "url": "https://caracal.club/", "tag": "Sync" },
                { "name": "Codec Guide", "url": "https://www.codecguide.com/" },
                { "name": "CyTube", "url": "https://cytu.be/", "tag": "Sync" },
                { "name": "Flyleaf", "url": "https://github.com/SuRGeoNix/Flyleaf" },
                { "name": "Free-Codecs", "url": "https://www.free-codecs.com/" },
                { "name": "GridPlayer", "url": "https://github.com/vzhd1701/gridplayer" },
                { "name": "HyperBeam", "url": "https://hyperbeam.com/", "tag": "Sync" },
                { "name": "ImPlay", "url": "https://github.com/tsl0922/ImPlay" },
                { "name": "KikoPlay", "url": "https://kikoplay.fun/" },
                { "name": "Kosmi", "url": "https://kosmi.io/", "tag": "⭐ Sync" },
                { "name": "Metastream", "url": "https://getmetastream.com/", "tag": "Sync" },
                { "name": "MoonPlayer", "url": "https://github.com/coslyk/moonplayer" },
                { "name": "MotionMonkey", "url": "https://omega.gg/MotionMonkey/" },
                { "name": "MovieNight", "url": "https://github.com/zorchenhimer/MovieNight", "tag": "Sync" },
                { "name": "MPC-BE", "url": "https://sourceforge.net/projects/mpcbe/" },
                { "name": "MPC-HC", "url": "https://github.com/clsid2/mpc-hc/", "tag": "⭐ Polecane" },
                { "name": "MPC-QT", "url": "https://mpc-qt.github.io/" },
                { "name": "MPV", "url": "https://mpv.io/", "tag": "⭐ Polecane" },
                { "name": "neko", "url": "https://neko.m1k1o.net/", "tag": "⭐ Sync" },
                { "name": "OpenTogetherTube", "url": "https://opentogethertube.com/", "tag": "Sync" },
                { "name": "panoptic", "url": "https://panoptic.live/" },
                { "name": "Plyr", "url": "https://plyr.io/" },
                { "name": "polsy.org.uk", "url": "https://polsy.org.uk/" },
                { "name": "PotPlayer", "url": "https://potplayer.daum.net/" },
                { "name": "Rave.io", "url": "https://rave.io/", "tag": "Sync" },
                { "name": "Rise Media Player", "url": "https://github.com/Rise-Software/Rise-Media-Player" },
                { "name": "Screenbox", "url": "https://github.com/huynhsontung/Screenbox" },
                { "name": "SPlayer", "url": "https://www.splayer.org/" },
                { "name": "SMPlayer", "url": "https://www.smplayer.info/" },
                { "name": "StreamLink", "url": "https://streamlink.github.io/" },
                { "name": "SyncPlay", "url": "https://syncplay.pl/", "tag": "⭐ Sync" },
                { "name": "SyncWatch", "url": "https://github.com/Semro/syncwatch", "tag": "⭐ Sync" },
                { "name": "Trast", "url": "https://trast.live/", "tag": "Sync" },
                { "name": "TurtleTV", "url": "https://turtletv.app/", "tag": "Sync" },
                { "name": "twoseven", "url": "https://twoseven.xyz/", "tag": "Sync" },
                { "name": "uView", "url": "https://www.idruf.com/" },
                { "name": "VideoTogether", "url": "https://2gether.video/en-us/", "tag": "Sync" },
                { "name": "VLC", "url": "https://www.videolan.org/", "tag": "⭐ Polecane" },
                { "name": "Watch2Gether", "url": "https://w2g.tv/", "tag": "⭐ Sync" },
                { "name": "WatchParty", "url": "https://www.watchparty.me/", "tag": "⭐ Sync" }
            ]
        },
        {
            "id": "serwery-mediow",
            "title": "🖥️ Serwery Mediów",
            "links": [
                { "name": "Chocolate", "url": "https://github.com/ChocolateApp/Chocolate" },
                { "name": "Dim", "url": "https://github.com/Dusk-Labs/dim" },
                { "name": "dizqueTV", "url": "https://github.com/vexorian/dizquetv" },
                { "name": "Emby", "url": "https://emby.media/" },
                { "name": "ErsatzTV", "url": "https://ersatztv.org/" },
                { "name": "Fixarr", "url": "https://github.com/sachinsenal0x64/fixarr" },
                { "name": "FlexGet", "url": "https://flexget.com/" },
                { "name": "Frames", "url": "https://github.com/Eleven-am/frames" },
                { "name": "Gerbera", "url": "https://gerbera.io/" },
                { "name": "Homehost", "url": "https://github.com/ridhwaans/homehost" },
                { "name": "HTPC Download Box", "url": "https://github.com/sebgl/htpc-download-box" },
                { "name": "Huntarr", "url": "https://github.com/plexguide/Huntarr.io" },
                { "name": "Jellyfin", "url": "https://jellyfin.org/", "tag": "⭐ Polecane" },
                { "name": "Jellyseerr", "url": "https://github.com/Fallenbagel/jellyseerr" },
                { "name": "Kawaii-Player", "url": "https://github.com/kanishka-linux/kawaii-player" },
                { "name": "Kodi", "url": "https://kodi.tv/", "tag": "⭐ Polecane" },
                { "name": "Kyoo", "url": "https://github.com/zoriya/Kyoo" },
                { "name": "Media-Hoarder", "url": "https://github.com/theMK2k/Media-Hoarder" },
                { "name": "MSX", "url": "https://msx.benzac.de/info/" },
                { "name": "Ombi", "url": "https://github.com/Ombi-app/Ombi" },
                { "name": "OSMC", "url": "https://osmc.tv/" },
                { "name": "Plex", "url": "https://www.plex.tv/" },
                { "name": "Prowlarr", "url": "https://github.com/Prowlarr/Prowlarr" },
                { "name": "Reiverr", "url": "https://github.com/aleksilassila/reiverr" },
                { "name": "Seanime", "url": "https://seanime.app/" },
                { "name": "Streama", "url": "https://github.com/streamaserver/streama" },
                { "name": "TRaSH Guides", "url": "https://trash-guides.info/", "tag": "Poradnik" },
                { "name": "Universal Media Server", "url": "https://www.universalmediaserver.com/" },
                { "name": "xTeVe", "url": "https://github.com/xteve-project/xTeVe" },
                { "name": "YTDL-Sub", "url": "https://ytdl-sub.readthedocs.io/en/" }
            ]
        },
        {
            "id": "transmisje-na-zywo-i-nagrywanie",
            "title": "🔴 Transmisje na Żywo i Nagrywanie",
            "links": [
                { "name": "Amuse", "url": "https://6klabs.com/amuse", "tag": "Nakładka" },
                { "name": "Annotate Screen", "url": "https://annotatescreen.com/" },
                { "name": "AnnotateWeb", "url": "https://annotateweb.com/" },
                { "name": "Cap", "url": "https://cap.so/" },
                { "name": "Chat-Downloader", "url": "https://github.com/xenova/chat-downloader" },
                { "name": "FFmpeg", "url": "https://ffmpeg.org/" },
                { "name": "glnk", "url": "https://github.com/geovens/gInk" },
                { "name": "Google Screen Recorder", "url": "https://toolbox.googleapps.com/apps/screen_recorder/", "tag": "Online" },
                { "name": "Live Draw", "url": "https://github.com/antfu/live-draw" },
                { "name": "LiveStreamDVR", "url": "https://github.com/MrBrax/LiveStreamDVR" },
                { "name": "MythTV", "url": "https://www.mythtv.org/" },
                { "name": "NVIDIA Broadcast", "url": "https://www.nvidia.com/en-us/geforce/broadcasting/broadcast-app/" },
                { "name": "OBS Studio", "url": "https://obsproject.com/", "tag": "⭐ Polecane" },
                { "name": "Owncast", "url": "https://owncast.online/", "tag": "Self-hosted" },
                { "name": "ppInk", "url": "https://github.com/PubPub-zz/ppInk/" },
                { "name": "real-url", "url": "https://github.com/wbt5/real-url" },
                { "name": "RecordScreen", "url": "https://recordscreen.io/", "tag": "Online" },
                { "name": "Restream", "url": "https://restream.io/" },
                { "name": "Restreamer", "url": "https://github.com/datarhei/restreamer", "tag": "Self-hosted" },
                { "name": "ScreenREC", "url": "https://screen-rec.vercel.app/", "tag": "Online" },
                { "name": "Shar.ec", "url": "https://shar.ec/", "tag": "Online" },
                { "name": "ShareX", "url": "https://getsharex.com/" },
                { "name": "Shinobi", "url": "https://shinobi.video/" },
                { "name": "Songify", "url": "https://songify.overcode.tv/", "tag": "Nakładka" },
                { "name": "Stream Elements", "url": "https://streamelements.com/" },
                { "name": "StreamLabs", "url": "https://streamlabs.com/" },
                { "name": "Strem", "url": "https://github.com/strem-app/strem" },
                { "name": "TwitchChat", "url": "https://twitchat.fr/" },
                { "name": "VDO Ninja", "url": "https://vdo.ninja/" },
                { "name": "vokoscreenNG", "url": "https://linuxecke.volkoh.de/vokoscreen/vokoscreen.html" },
                { "name": "WDFlat", "url": "https://www.wdflat.com/" }
            ]
        },
        {
            "id": "narzedzia-dyskowe-i-uzytkowe",
            "title": "💿 Narzędzia Dyskowe i Użytkowe",
            "links": [
                { "name": "Alcohol Soft", "url": "https://www.alcohol-soft.com/" },
                { "name": "BatchGuy", "url": "https://github.com/yaboy58/BatchGuy" },
                { "name": "CDBurnerXP", "url": "https://cdburnerxp.se/" },
                { "name": "Deep-Live-Cam", "url": "https://github.com/hacksider/Deep-Live-Cam", "tag": "Face Swap" },
                { "name": "DeepBurner", "url": "https://www.deepburner.com/" },
                { "name": "DGDemux", "url": "https://www.rationalqm.us/dgdemux/dgdemux.html" },
                { "name": "DVDStyler", "url": "https://www.dvdstyler.org/en/" },
                { "name": "ICAT", "url": "https://www.nvidia.com/en-us/geforce/technologies/icat/" },
                { "name": "ImgBurn", "url": "https://www.majorgeeks.com/files/details/imgburn.html" },
                { "name": "Kast", "url": "https://kast.gg/" },
                { "name": "MakeMKV", "url": "https://www.makemkv.com/" },
                { "name": "MP4Recover", "url": "https://github.com/ActiveTK/MP4Recover" },
                { "name": "PgcDemux", "url": "https://www.videohelp.com/software/PgcDemux" },
                { "name": "Redump", "url": "http://redump.org/" },
                { "name": "Reincubate Camo", "url": "https://reincubate.com/camo/", "tag": "⭐ Kamera" },
                { "name": "Roop", "url": "https://github.com/s0md3v/roop", "tag": "Face Swap" },
                { "name": "Rope", "url": "https://github.com/Hillobar/Rope", "tag": "Face Swap" },
                { "name": "Screen Share Party", "url": "https://ba.net/screen/" },
                { "name": "Screenz", "url": "https://screenz.agst.dev/" },
                { "name": "SimSwap", "url": "https://github.com/neuralchen/SimSwap", "tag": "Face Swap" },
                { "name": "UHD Drives Flashing Guide", "url": "https://forum.makemkv.com/forum/viewtopic.php?f=16&t=19634", "tag": "Poradnik" },
                { "name": "VidClue", "url": "https://vidclue.com/" },
                { "name": "VidCoder", "url": "https://vidcoder.net/" },
                { "name": "videoduplicatefinder", "url": "https://github.com/0x90d/videoduplicatefinder" },
                { "name": "VideoHelp Forum", "url": "https://forum.videohelp.com/" },
                { "name": "VHS Decode", "url": "https://github.com/oyvindln/vhs-decode" },
                { "name": "XReveal", "url": "https://www.xreveal.com/" }
            ]
        },
        {
            "id": "hosting-plikow-wideo",
            "title": "☁️ Hosting Plików Wideo",
            "links": [
                { "name": "AnonTransfer", "url": "https://anontransfer.com/" },
                { "name": "Catbox", "url": "https://catbox.moe/", "tag": "⭐ Polecane" },
                { "name": "Darkibox", "url": "https://darkibox.com/" },
                { "name": "DoodStream", "url": "https://doodstream.com/", "tag": "⭐ Polecane" },
                { "name": "Dubz", "url": "https://dubz.co/" },
                { "name": "FEX.NET", "url": "https://fex.net/" },
                { "name": "FileMoon", "url": "https://filemoon.sx/" },
                { "name": "Gofile", "url": "https://gofile.io/", "tag": "⭐ Polecane" },
                { "name": "Hexupload", "url": "https://hexload.com/" },
                { "name": "Litterbox", "url": "https://litterbox.catbox.moe/", "tag": "⭐ Polecane" },
                { "name": "Luluvdoo", "url": "https://luluvdoo.com/" },
                { "name": "MixDrop", "url": "https://mixdrop.ag/" },
                { "name": "Send.now", "url": "https://send.now/", "tag": "⭐ Polecane" },
                { "name": "Streamable", "url": "https://streamable.com/" },
                { "name": "Streamplay", "url": "https://streamplay.to/" },
                { "name": "Streamtape", "url": "https://streamtape.com/" },
                { "name": "uguu", "url": "https://uguu.se/" },
                { "name": "Videy", "url": "https://videy.co/" },
                { "name": "Vidmoly", "url": "https://vidmoly.me/" },
                { "name": "Vidoza", "url": "https://vidoza.net/" },
                { "name": "VOE", "url": "https://voe.sx/" },
                { "name": "webmshare", "url": "https://webmshare.com/" }
            ]
        },
        {
            "id": "wideo-stockowe-i-zasoby",
            "title": "🖼️ Wideo Stockowe i Zasoby",
            "links": [
                { "name": "4K Media", "url": "https://4kmedia.org/" },
                { "name": "Awesome Stock Resources", "url": "https://github.com/neutraltone/awesome-stock-resources#videos", "tag": "⭐ Index" },
                { "name": "BeachFrontBroll", "url": "https://www.beachfrontbroll.com/" },
                { "name": "CuteStockFootage", "url": "https://cutestockfootage.com/free/video", "tag": "Index" },
                { "name": "Dareful", "url": "https://dareful.com/" },
                { "name": "DroneStock", "url": "https://dronestock.com/" },
                { "name": "ineedfx", "url": "https://ineedfx.com/" },
                { "name": "MixKit", "url": "https://mixkit.co/" },
                { "name": "Monzoom", "url": "https://www.monzoom.com/" },
                { "name": "MotionPlaces", "url": "https://www.motionplaces.com/" },
                { "name": "MovieTools", "url": "https://movietools.info/" },
                { "name": "Pexels", "url": "https://www.pexels.com/" },
                { "name": "veed.io", "url": "https://www.veed.io/videos" },
                { "name": "Videvo", "url": "https://www.videvo.net/" },
                { "name": "VidsPlay", "url": "https://www.vidsplay.com/" }
            ]
        }
    ],
    "info": {
        "title": "💡 Wskazówki i Dobre Praktyki",
        "toc_title": "💡 Wskazówki",
        "tips": [
            "<strong>Kodeki i Kontenery:</strong> Zrozumienie różnicy między kontenerem (np. .mkv, .mp4) a kodekiem (np. H.264, AV1) jest kluczowe dla efektywnej edycji i odtwarzania wideo.",
            "<strong>Bitrate:</strong> Wyższy bitrate oznacza lepszą jakość, ale i większy rozmiar pliku. Dopasuj go do swoich potrzeb – inne wartości będą optymalne dla YouTube, a inne do archiwizacji.",
            "<strong>Streaming:</strong> Używając narzędzi do streamingu, zawsze sprawdzaj regulaminy serwisów. Niektóre z nich mogą blokować nieoficjalne aplikacje.",
            "<strong>Zawsze używaj:</strong> <a href=\"privacy.html\">AdBlockera</a>, aby uniknąć natrętnych reklam na wielu z tych stron."
        ]
    }
};